"""Build Evergreen_Reveal/Reveal_Data.lua from the WoW Forever beta client's own
WorldMapOverlay + WorldMapOverlayTile DB2s (read from local CASC via Hearthbreak's
forever-port reader). Run: python build_reveal.py"""
import sys, os, math, collections
sys.path.insert(0, r"E:\Project HearthBreak\tools\forever-port\casc")
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import forever_casc, wdc5

r = forever_casc.Reader()
ov = wdc5.read(r.read(1134579))
tl = wdc5.read(r.read(1957212))
build = r.build_key[:8]

tiles = collections.defaultdict(list)
for tid, overlay, (row, col, layer, fid) in tl["rows"]:
    tiles[overlay].append((layer, row, col, fid))

byart = collections.defaultdict(list)
bad = 0
for _id, _rel, v in ov["rows"]:
    oid, art, w, h, x, y = v[0], v[1], v[2], v[3], v[4], v[5]
    t = sorted(x for x in tiles.get(oid, []) if x[0] == 0)
    need = math.ceil(w / 256) * math.ceil(h / 256)
    if not t or len(t) != need:
        bad += 1
        print("skip overlay", oid, "art", art, "size", w, h, "tiles", len(t), "need", need)
        continue
    byart[art].append("%d:%d:%d:%d:%s" % (w, h, x, y, ",".join(str(f) for *_, f in t)))

out = os.path.join(os.path.dirname(__file__), "..", "Evergreen_Reveal", "Reveal_Data.lua")
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w", newline="\n") as f:
    f.write("-- GENERATED by addon/tools/build_reveal.py from the WoW Forever beta client\n")
    f.write("-- (WorldMapOverlay + WorldMapOverlayTile DB2). Do not edit by hand.\n")
    f.write("-- [uiMapArtID] = { \"width:height:offsetX:offsetY:fileDataID,...\" }\n")
    f.write("local _, ns = ...\n\nns.RevealData = {\n")
    for art in sorted(byart):
        f.write("\t[%d] = {\n" % art)
        for s in sorted(byart[art]):
            f.write("\t\t\"%s\",\n" % s)
        f.write("\t},\n")
    f.write("}\n")
print("maps", len(byart), "overlays", sum(len(v) for v in byart.values()), "skipped", bad, "->", os.path.normpath(out))
