"""Build Evergreen_Journal/Journal_MapData.lua: the dungeon map tiles the WoW Forever client ships.

The Forever client has no dungeon uiMaps (its UiMap table only holds the world, continents and zones),
but the classic dungeon map artwork is still in its data: interface/worldmap/<folder>/<folder><floor>_<n>.blp,
12 tiles of 256x256 per floor laid out 4 wide by 3 high (1002x668 used). This script finds each
floor's tile fileDataIDs in the listfile, keeps only the floors whose 12 tiles all read from the local
Forever CASC, and writes them per journal dungeon key. Run: python build_maps.py
"""
import os, re, sys, collections
sys.path.insert(0, r"E:\Project HearthBreak\tools\forever-port\casc")
import forever_casc

LISTFILE = r"E:\Project HearthBreak\tools\forever-port\MultiConverter-bin\listfile.csv"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "Evergreen_Journal", "Journal_MapData.lua")

# journal key -> (map folder, floors to show, floor labels). None = every floor the client has.
# Scarlet Monastery floors are its wings in the classic order (Graveyard, Library, Armory, Cathedral).
DUNGEONS = {
    "Ragefire": ("ragefire", None, None),
    "TheDeadmines": ("deadmineswestfall", None, ["The Deadmines"]),
    "WailingCaverns": ("wailingcaverns", None, None),
    "ShadowfangKeep": ("shadowfangkeep", None, None),
    "BlackfathomDeeps": ("blackfathomdeeps", None, None),
    "TheStockade": ("thestockade", None, None),
    "Gnomeregan": ("gnomeregan", [1, 2, 3, 4], None),
    "ScarletMonasteryGraveyard": ("scarletmonastery", [1], ["Graveyard"]),
    "ScarletMonasteryLibrary": ("scarletmonastery", [2], ["Library"]),
    "ScarletMonasteryArmory": ("scarletmonastery", [3], ["Armory"]),
    "ScarletMonasteryCathedral": ("scarletmonastery", [4], ["Cathedral"]),
    "RazorfenKraul": ("razorfenkraul", None, None),
    "RazorfenDowns": ("razorfendowns", None, None),
    "Uldaman": ("uldaman", [1, 2], None),
    "Maraudon": ("maraudon", None, None),
    "TheTempleOfAtal'Hakkar": ("thetempleofatalhakkar", None, None),
    "BlackrockDepths": ("blackrockdepths", None, None),
    "LowerBlackrockSpire": ("blackrockspire", None, None),
    "UpperBlackrockSpire": ("blackrockspire", None, None),
    "DireMaulEast": ("diremaul", None, None),
    "DireMaulNorth": ("diremaul", None, None),
    "DireMaulWest": ("diremaul", None, None),
    "Stratholme": ("stratholme", None, None),
    "Scholomance": ("scholomance", None, None),
    "MoltenCore": ("moltencore", None, None),
    "BlackwingLair": ("blackwinglair", None, None),
    "Onyxia": ("onyxiaslair", None, None),
    "TheRuinsofAhnQiraj": ("ruinsofahnqiraj", None, None),
    "TheTempleofAhnQiraj": ("ahnqiraj", None, None),
    "Naxxramas": ("naxxramas", None, None),
}

# folder -> floor -> {tile index: fileDataID}. "<folder>_<n>.blp" (no floor number) counts as floor 1.
tiles = collections.defaultdict(lambda: collections.defaultdict(dict))
want = {v[0] for v in DUNGEONS.values()}
pat = re.compile(r"interface/worldmap/([a-z']+)/([a-z']+?)(\d*)_(\d+)\.blp$")
for line in open(LISTFILE, encoding="utf-8", errors="ignore"):
    fid, _, path = line.strip().partition(";")
    m = pat.match(path)
    if m and m.group(1) in want and m.group(2) == m.group(1):
        tiles[m.group(1)][int(m.group(3) or 1)][int(m.group(4))] = int(fid)

r = forever_casc.Reader()
def readable(fid):
    try:
        r.read(fid)
        return True
    except Exception:
        return False

have = {}   # folder -> {floor: [12 fids]}
for folder in sorted(want):
    have[folder] = {}
    for floor, t in sorted(tiles[folder].items()):
        if sorted(t) == list(range(1, 13)) and all(readable(t[k]) for k in range(1, 13)):
            have[folder][floor] = [t[k] for k in range(1, 13)]

lines = [
    "-- GENERATED by addon/tools/build_maps.py. Do not edit by hand.",
    "-- Dungeon map tiles shipped in the WoW Forever client (classic interface/worldmap artwork):",
    "-- per journal dungeon key, its floors; each floor is 12 tile fileDataIDs, 4 wide x 3 high, 256 px each.",
    "local _, ns = ...",
    "",
    "ns.DungeonMaps = {",
]
missing = []
for key in sorted(DUNGEONS):
    folder, pick, labels = DUNGEONS[key]
    floors = sorted(have[folder]) if pick is None else [f for f in pick if f in have[folder]]
    if not floors:
        missing.append(key)
        continue
    parts = []
    for i, f in enumerate(floors):
        name = labels[i] if labels and i < len(labels) else ("Level %d" % (i + 1) if len(floors) > 1 else "Map")
        parts.append('{name=%s,tiles={%s}}' % ('"%s"' % name, ",".join(str(x) for x in have[folder][f])))
    lines.append('  ["%s"] = {%s},' % (key, ",".join(parts)))
lines.append("}")
open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
print("wrote", OUT, "-", len(DUNGEONS) - len(missing), "dungeons with maps; missing:", ", ".join(missing) or "none")
