-- Professions module: WoW-Professions.com's WoW Forever leveling guides in game.
--
-- Picks the guide for each profession this character has, finds the step for the current skill,
-- counts the step's materials in the bags (and bank), lists the trainers for the player's faction
-- with "go" waypoints, and keeps a ticked shopping list per character.
--
-- Data: Prof_Data.lua (ns.ProfessionsData), generated by tools/import_wowprof_professions.py. The
-- guide text belongs to WoW-Professions.com, so the file is not in the repo; without it the window
-- says how to make it. The window itself is Professions_UI.lua.
-- /prof (or /eg prof) toggles the window; /prof <name> opens a profession; /prof clear drops the waypoint.

local ADDON, ns = ...

local P = { ui = {} }
ns.Professions = P
local HEX = ns.Skin.HEX
P.HEX = HEX

local DB, CDB
P.TIER_CAP = { Apprentice = 75, Journeyman = 150, Expert = 225, Artisan = 300 }

function P.say(msg) print("|cff7fd35eEvergreen Professions:|r " .. msg) end
local say = P.say

-- A value this client hides from addons (names, GUIDs in combat on WoW Forever) is never compared.
local function plain(v)
  if v == nil then return nil end
  if issecretvalue and issecretvalue(v) then return nil end
  return v
end
P.plain = plain

-- ------------------------------------------------------------------ data
function P.Data()
  local d = ns.ProfessionsData
  if type(d) == "table" and type(d.guides) == "table" and #d.guides > 0 then return d end
  return nil
end

function P.Guides()
  local d = P.Data()
  return d and d.guides or {}
end

function P.Guide(key)
  for _, g in ipairs(P.Guides()) do if g.key == key then return g end end
  return nil
end

function P.NPC(slug)
  local d = P.Data()
  return d and d.npcs and d.npcs[slug] or nil
end

function P.Faction()
  local f = plain(UnitFactionGroup and UnitFactionGroup("player"))
  return f == "Alliance" and "A" or f == "Horde" and "H" or nil
end

-- an NPC this faction can use (neutral ones and unknown ones count)
function P.ForMe(npc)
  local f = P.Faction()
  return not (npc and npc.f and f and npc.f ~= f)
end

-- ------------------------------------------------------------------ skills
-- name -> { rank, max }. Tries every API this client might have: GetProfessions /
-- GetProfessionInfo (modern), GetNumSkillLines / GetSkillLineInfo (classic; Questie may provide it
-- on clients without it), and the open trade skill window (C_TradeSkillUI).
P.skills = {}
local fromWindow = {}

local function addSkill(out, name, rank, max)
  name, rank, max = plain(name), plain(rank), plain(max)
  if type(name) ~= "string" or name == "" or type(rank) ~= "number" then return end
  local e = out[name]
  if not e or rank > e.rank then out[name] = { rank = rank, max = (type(max) == "number" and max > 0) and max or nil } end
end

function P.ScanSkills()
  local out = {}
  if type(GetProfessions) == "function" and type(GetProfessionInfo) == "function" then
    local ok, a, b, c, d, e, f = pcall(GetProfessions)
    if ok then
      for _, idx in pairs({ a, b, c, d, e, f }) do
        local ok2, name, _, rank, max = pcall(GetProfessionInfo, idx)
        if ok2 then addSkill(out, name, rank, max) end
      end
    end
  end
  if type(GetNumSkillLines) == "function" and type(GetSkillLineInfo) == "function" then
    local ok, n = pcall(GetNumSkillLines)
    if ok and type(n) == "number" then
      for i = 1, math.min(n, 200) do
        local ok2, name, isHeader, _, rank, _, _, max = pcall(GetSkillLineInfo, i)
        if ok2 and not isHeader then addSkill(out, name, rank, max) end
      end
    end
  end
  for name, e in pairs(fromWindow) do addSkill(out, name, e.rank, e.max) end
  P.skills = out
  return out
end

-- The trade skill window knows its own profession's level even where the skill APIs do not.
function P.ReadTradeSkillWindow()
  local T = C_TradeSkillUI
  if type(T) ~= "table" or type(T.GetBaseProfessionInfo) ~= "function" then return end
  local ok, info = pcall(T.GetBaseProfessionInfo)
  if not ok or type(info) ~= "table" then return end
  local name, rank, max = plain(info.professionName), plain(info.skillLevel), plain(info.maxSkillLevel)
  if type(T.GetChildProfessionInfo) == "function" then
    local ok2, child = pcall(T.GetChildProfessionInfo)
    if ok2 and type(child) == "table" and type(plain(child.skillLevel)) == "number" and child.skillLevel > 0 then
      rank, max = child.skillLevel, plain(child.maxSkillLevel) or max
    end
  end
  if type(name) == "string" and type(rank) == "number" then
    -- "Classic Alchemy" and the like: keep the guide's own name
    for _, g in ipairs(P.Guides()) do
      if name:lower():find(g.skill:lower(), 1, true) then name = g.skill end
    end
    fromWindow[name] = { rank = rank, max = max }
  end
end

function P.Skill(name)
  if not name then return nil end
  local e = P.skills[name]
  if not e then
    local lname = name:lower()
    for n, v in pairs(P.skills) do if n:lower() == lname then e = v end end
  end
  return e and e.rank or nil, e and e.max or nil
end

-- the guides this character has the skill for, in guide order (the combined Fishing & Cooking
-- guide only when both are known)
function P.Learned()
  local out = {}
  for _, g in ipairs(P.Guides()) do
    local r = P.Skill(g.skill)
    if r and (g.key ~= "fishing-and-cooking" or P.Skill("Cooking")) then out[#out + 1] = g end
  end
  return out
end

-- ------------------------------------------------------------------ steps
function P.Variant(g, gid)
  local v = DB and DB.variants and DB.variants[g.key] and DB.variants[g.key][gid]
  return v or 1
end

function P.SetVariant(g, gid, i)
  DB.variants = DB.variants or {}
  DB.variants[g.key] = DB.variants[g.key] or {}
  DB.variants[g.key][gid] = i
end

function P.Visible(g, e)
  if e.fac and P.Faction() and e.fac ~= P.Faction() then return false end
  if e.var and P.Variant(g, e.var.g) ~= e.var.i then return false end
  return true
end

-- The entry for the character's skill: the first visible step not finished yet. Guides written as
-- prose (Fishing) have no steps, so their ranged headings count instead, per skill.
function P.CurrentIndex(g)
  local hasSteps = {}
  for _, e in ipairs(g.entries or {}) do if e.k == "s" then hasSteps[e.skill or g.skill] = true end end
  for i, e in ipairs(g.entries or {}) do
    local sk = e.skill or g.skill
    if e.to and P.Visible(g, e) and (e.k == "s" or (e.k == "h" and not hasSteps[sk])) then
      local r = P.Skill(sk)
      if r and r < e.to then return i, e end
    end
  end
  return nil
end

-- ------------------------------------------------------------------ materials
local function itemCount(item)
  if item == nil then return 0 end
  local f = (C_Item and C_Item.GetItemCount) or GetItemCount
  if type(f) ~= "function" then return 0 end
  local ok, n = pcall(f, item, true)
  if ok and type(n) == "number" then return n end
  return 0
end

-- in the bags and the bank (the client remembers the bank once it has been opened); by item ID,
-- by name when the guide named a material without a link
function P.Have(mat)
  local n = itemCount(mat.i)
  if n == 0 and mat.n then n = itemCount(mat.n) end
  return n
end

-- all the materials of a step, summed per material (pick "one": only the first craft)
-- (need: what is still needed at this skill, see P.MatNeed)
function P.StepMats(e, skill)
  local list, by = {}, {}
  local crafts = e.crafts or {}
  if e.pick == "one" then crafts = { crafts[1] } end
  for _, c in ipairs(crafts) do
    local left = P.CraftsLeft(e, c, skill)
    for _, m in ipairs(c.mats or {}) do
      local key = m.i or m.n
      local t = by[key]
      if not t then t = { n = m.n, i = m.i, c = 0, need = 0 }; by[key] = t; list[#list + 1] = t end
      t.c = t.c + (m.c or 0)
      t.need = t.need + P.MatNeed(m, c, left)
    end
  end
  return list
end

-- Crafts still to make for this step at the given skill: the guide's count scaled by the skill
-- points left in the step's range (all of them below the range, none once past it).
function P.CraftsLeft(e, c, skill)
  if not c.c then return nil end
  if not (skill and e and e.from and e.to and e.to > e.from) then return c.c end
  if skill >= e.to then return 0 end
  local from = math.max(skill, e.from)
  return math.min(c.c, math.ceil(c.c * (e.to - from) / (e.to - e.from)))
end

-- How many of a material the remaining crafts use (the guide lists the total for all c.c crafts).
function P.MatNeed(m, c, left)
  if not (left and c.c and c.c > 0) then return m.c or 0 end
  return math.ceil((m.c or 0) * left / c.c)
end

-- Unit price to buy a material now, from Everbid (when installed): the cheaper of the last scan's
-- cheapest listing and a vendor price Everbid has seen. Returns price, "AH" or "vendor".
function P.UnitPrice(itemID)
  local eb = Everbid
  if not (itemID and type(eb) == "table" and eb.PriceDB and eb.PriceDB.Get) then return nil end
  local ok, rec = pcall(eb.PriceDB.Get, eb.PriceDB, tostring(itemID))
  local ah = ok and type(rec) == "table" and rec.min or nil
  local vendor = type(eb.db) == "table" and eb.db.vendorBuy and eb.db.vendorBuy[itemID] or nil
  if ah and vendor then
    if vendor <= ah then return vendor, "vendor" end
    return ah, "AH"
  end
  if ah then return ah, "AH" end
  if vendor then return vendor, "vendor" end
  return nil
end

function P.HasPrices()
  return type(Everbid) == "table" and Everbid.PriceDB ~= nil
end

function P.Money(copper)
  copper = math.floor((copper or 0) + 0.5)
  if type(Everbid) == "table" and Everbid.Money then
    local ok, s = pcall(Everbid.Money, copper)
    if ok and s then return s end
  end
  if GetCoinTextureString then
    local ok, s = pcall(GetCoinTextureString, copper)
    if ok and s then return s end
  end
  local g, s, c = math.floor(copper / 10000), math.floor(copper / 100) % 100, copper % 100
  if g > 0 then return string.format("%dg %ds %dc", g, s, c) end
  if s > 0 then return string.format("%ds %dc", s, c) end
  return c .. "c"
end

-- Cost to buy what's missing for a list of { mat, need } pairs: total, missing items without a price.
function P.BuyCost(list)
  local total, unpriced = 0, 0
  for _, x in ipairs(list) do
    local short = math.max(0, (x.need or 0) - P.Have(x.mat))
    if short > 0 then
      local price = P.UnitPrice(x.mat.i)
      if price then total = total + price * short else unpriced = unpriced + 1 end
    end
  end
  return total, unpriced
end

-- ------------------------------------------------------------------ trainers
-- next training: the tier whose skill cap is above what the character can reach now
function P.NextTier(g)
  local rank, max = P.Skill(g.skill)
  for _, t in ipairs(g.tiers or {}) do
    local cap = P.TIER_CAP[t.name]
    if not rank then return t end
    if max and cap and cap > max then return t end
    if not max and t.from and t.from > rank then return t end
  end
  return nil
end

function P.TrainersFor(tier)
  local f = P.Faction()
  local out = {}
  local lists = tier and tier.trainers or {}
  for _, fk in ipairs(f and { f } or { "H", "A" }) do
    for _, x in ipairs(lists[fk] or {}) do out[#out + 1] = x end
  end
  return out
end

-- ------------------------------------------------------------------ waypoints
P.ZONES = {
  [1411]="Durotar", [1412]="Mulgore", [1413]="The Barrens", [1416]="Alterac Mountains", [1417]="Arathi Highlands",
  [1418]="Badlands", [1419]="Blasted Lands", [1420]="Tirisfal Glades", [1421]="Silverpine Forest", [1422]="Western Plaguelands",
  [1423]="Eastern Plaguelands", [1424]="Hillsbrad Foothills", [1425]="The Hinterlands", [1426]="Dun Morogh", [1427]="Searing Gorge",
  [1428]="Burning Steppes", [1429]="Elwynn Forest", [1430]="Deadwind Pass", [1431]="Duskwood", [1432]="Loch Modan",
  [1433]="Redridge Mountains", [1434]="Stranglethorn Vale", [1435]="Swamp of Sorrows", [1436]="Westfall", [1437]="Wetlands",
  [1438]="Teldrassil", [1439]="Darkshore", [1440]="Ashenvale", [1441]="Thousand Needles", [1442]="Stonetalon Mountains",
  [1443]="Desolace", [1444]="Feralas", [1445]="Dustwallow Marsh", [1446]="Tanaris", [1447]="Azshara", [1448]="Felwood",
  [1449]="Un'Goro Crater", [1450]="Moonglade", [1451]="Silithus", [1452]="Winterspring", [1453]="Stormwind City",
  [1454]="Orgrimmar", [1455]="Ironforge", [1456]="Thunder Bluff", [1457]="Darnassus", [1458]="Undercity",
}

-- The Evergreen arrow when the guide module is on, else the game's own map pin (+ TomTom).
function P.Waypoint(map, x, y, title)
  if not map or not x or not y then say("no map position for " .. (title or "that") .. "."); return false end
  if ns.SetExternalTarget and ns.ModuleEnabled and ns.ModuleEnabled("guide") and EvergreenCharDB then
    ns.SetExternalTarget(map, x, y, title)
  else
    if C_Map and C_Map.SetUserWaypoint and UiMapPoint and UiMapPoint.CreateFromCoordinates then
      pcall(function()
        C_Map.SetUserWaypoint(UiMapPoint.CreateFromCoordinates(map, x / 100, y / 100))
        if C_SuperTrack and C_SuperTrack.SetSuperTrackedUserWaypoint then C_SuperTrack.SetSuperTrackedUserWaypoint(true) end
      end)
    end
    if TomTom and TomTom.AddWaypoint then pcall(TomTom.AddWaypoint, TomTom, map, x / 100, y / 100, { title = title }) end
  end
  say("waypoint: " .. HEX.body .. (title or "") .. "|r, " .. (P.ZONES[map] or ("map " .. map)) .. string.format(" %.1f, %.1f", x, y))
  return true
end

function P.WaypointNPC(slug)
  local n = P.NPC(slug)
  if not n then say("no position for that NPC."); return false end
  return P.Waypoint(n.m, n.x, n.y, n.n)
end

function P.NPCLabel(slug)
  local n = P.NPC(slug)
  if not n then return slug end
  local where = n.sub and n.z and n.sub ~= n.z and (n.sub .. ", " .. n.z) or n.z or (n.m and P.ZONES[n.m]) or ""
  return n.n .. (where ~= "" and (HEX.muted .. "  " .. where .. "|r") or "")
end

-- ------------------------------------------------------------------ shopping list ticks (per character)
local function shopKey(g, li, ri) return g.key .. ":" .. li .. ":" .. ri end
function P.ShopChecked(g, li, ri) return CDB and CDB.shop[shopKey(g, li, ri)] or false end
function P.SetShopChecked(g, li, ri, on) if CDB then CDB.shop[shopKey(g, li, ri)] = on and true or nil end end

-- ------------------------------------------------------------------ boot, events, slash
function P.DefaultGuide()
  if DB and DB.prof and P.Guide(DB.prof) then return P.Guide(DB.prof) end
  local learned = P.Learned()
  local secondary = { ["first-aid"] = true, cooking = true, fishing = true, ["fishing-and-cooking"] = true }
  for _, g in ipairs(learned) do if not secondary[g.key] then return g end end
  return learned[1] or P.Guides()[1]
end

function P.Select(key)
  local g = P.Guide(key)
  if not g then return nil end
  P.current = g
  if DB then DB.prof = key end
  if P.ui.Refresh then P.ui.Refresh() end
  return g
end

local pending
function P.Changed()
  if pending then return end
  pending = true
  local function run()
    pending = false
    P.ScanSkills()
    if P.ui.Refresh and P.ui.frame and P.ui.frame:IsShown() then P.ui.Refresh() end
  end
  if C_Timer and C_Timer.After then C_Timer.After(0.2, run) else run() end
end

local ev = CreateFrame("Frame")
ev:RegisterEvent("ADDON_LOADED")
ev:SetScript("OnEvent", function(self, event, name)
  if event == "ADDON_LOADED" then
    if name ~= ADDON then return end
    if not ns.ModuleEnabled("professions") then ns.Professions = nil; self:UnregisterAllEvents(); return end
    EvergreenDB = EvergreenDB or {}
    EvergreenDB.professions = EvergreenDB.professions or {}
    DB = EvergreenDB.professions
    DB.variants = DB.variants or {}
    EvergreenCharDB = EvergreenCharDB or {}
    EvergreenCharDB.professions = EvergreenCharDB.professions or {}
    CDB = EvergreenCharDB.professions
    CDB.shop = CDB.shop or {}
    P.db, P.cdb = DB, CDB
    for _, e in ipairs({ "PLAYER_LOGIN", "SKILL_LINES_CHANGED", "TRADE_SKILL_SHOW", "TRADE_SKILL_LIST_UPDATE",
                         "TRADE_SKILL_UPDATE", "CHAT_MSG_SKILL", "LEARNED_SPELL_IN_TAB", "BAG_UPDATE_DELAYED",
                         "BANKFRAME_OPENED", "PLAYERBANKSLOTS_CHANGED" }) do
      pcall(self.RegisterEvent, self, e)
    end
    P.ScanSkills()
    return
  end
  if event == "PLAYER_LOGIN" then
    P.ScanSkills()
    if ns.Skin.MinimapButton then
      ns.Skin.MinimapButton("professions", "Interface\\Icons\\Trade_BlackSmithing", 200,
        function() P.Slash("") end,
        function(tt)
          tt:AddLine("Evergreen: profession guides", 1, 0.82, 0)
          tt:AddLine("Click: open the guide for your professions", 0.9, 0.9, 0.9)
        end)
    end
    return
  end
  if event == "TRADE_SKILL_SHOW" or event == "TRADE_SKILL_LIST_UPDATE" or event == "TRADE_SKILL_UPDATE" then
    P.ReadTradeSkillWindow()
  end
  P.Changed()
end)

function P.Slash(rest)
  rest = (rest or ""):gsub("^%s+", ""):gsub("%s+$", "")
  local low = rest:lower()
  if low == "help" then
    say("/prof (toggle), /prof <profession> (open it), /prof clear (drop the waypoint), /prof skills (what the client reports)")
    return
  elseif low == "clear" then
    if ns.ClearExternalTarget then ns.ClearExternalTarget() end
    if C_Map and C_Map.ClearUserWaypoint then pcall(C_Map.ClearUserWaypoint) end
    say("waypoint cleared.")
    return
  elseif low == "skills" then
    P.ScanSkills()
    local t = {}
    for n, e in pairs(P.skills) do t[#t + 1] = n .. " " .. e.rank .. (e.max and ("/" .. e.max) or "") end
    table.sort(t)
    say(#t > 0 and table.concat(t, ", ") or "the client reported no skills.")
    return
  end
  if not P.ui.Build then return end
  P.ScanSkills()
  if low ~= "" then
    for _, g in ipairs(P.Guides()) do
      if g.key == low or g.name:lower():find(low, 1, true) then
        P.ui.Open(g.key)
        return
      end
    end
    if P.Data() then say("no profession guide matches '" .. rest .. "'."); return end
  end
  P.ui.Toggle()
end

SLASH_EVERGREENPROF1 = "/prof"
SLASH_EVERGREENPROF2 = "/professions"
SlashCmdList["EVERGREENPROF"] = function(msg)
  if not ns.Professions then
    print(HEX.green .. "Evergreen:|r the Professions module is off. Turn on \"Evergreen - Professions\" in the AddOns list, then /reload.")
    return
  end
  P.Slash(msg)
end

-- /eg prof: the core's /eg handler knows only its own modules, so wrap it (the core loads first)
local egSlash = SlashCmdList["EVERGREEN"]
if egSlash then
  SlashCmdList["EVERGREEN"] = function(msg)
    local cmd, rest = (msg or ""):match("^%s*(%S+)%s*(.-)%s*$")
    cmd = cmd and cmd:lower()
    if cmd == "prof" or cmd == "profs" or cmd == "profession" or cmd == "professions" then
      return SlashCmdList.EVERGREENPROF(rest)
    end
    egSlash(msg)
    if cmd == "help" or cmd == "?" then print(HEX.green .. "Professions|r: /eg prof, /prof") end
  end
end

-- listed by /eg modules
if type(ns.MODULES) == "table" then
  local known = false
  for _, m in ipairs(ns.MODULES) do if m.id == "professions" then known = true end end
  if not known then
    table.insert(ns.MODULES, { id = "professions", addon = "Evergreen_Professions", name = "Professions", slash = "/prof",
      desc = "Profession leveling guides (WoW-Professions.com): steps, materials, trainers, shopping list" })
  end
end
