-- Farming: WoW-Professions' mining, herb and leather routes (Farm_Data.lua, generated by
-- tools/import_wowprof_farming.py) as follow-along routes. Pick one in the window (Farm_UI.lua); it is
-- drawn on the world map and the minimap (Farm_Map.lua) and an arrow leads from point to point,
-- moving on when you get within ARRIVE_YARDS of the point (or with Next / Prev, the minimap button's
-- right click, or the key bindings).
--
-- The arrow: with the Guide module on (and its arrow shown) Farming drives the guide's arrow through
-- ns.SetExternalTarget; otherwise it shows its own arrow (same sprite and look, movable).
-- /farm (or /eg farm): window; /farm next | prev | stop | arrow | minimap | map | help.

local ADDON, ns = ...
local HEX = ns.Skin.HEX

local F = { routes = {}, byId = {}, listeners = {} }
ns.Farm = F

F.ARRIVE_YARDS = 25
F.CATEGORIES = { "Ore", "Herbs", "Leather" }
local TICK = 0.1
local TWO_PI = math.pi * 2

local DB, CDB

local function say(msg) print(HEX.green .. "Evergreen Farming:|r " .. msg) end
F.Say = say

F.NO_DATA = "no routes installed. Run tools/import_wowprof_farming.py (it builds Evergreen_Farming/Farm_Data.lua), then /reload."

-- ------------------------------------------------------------------ data
function F.LoadData()
  wipe(F.routes); wipe(F.byId)
  for _, r in ipairs(type(ns.FarmData) == "table" and ns.FarmData or {}) do
    if type(r) == "table" and r.id and r.map and type(r.points) == "table" and #r.points > 0 then
      F.routes[#F.routes + 1] = r
      F.byId[r.id] = r
    end
  end
  table.sort(F.routes, function(a, b)
    if a.continent ~= b.continent then return (a.continent or 0) < (b.continent or 0) end
    if a.zone ~= b.zone then return a.zone < b.zone end
    return a.id < b.id
  end)
  return #F.routes
end

function F.HasData() return #F.routes > 0 end

function F.On(fn) F.listeners[#F.listeners + 1] = fn end
function F.Notify(what)
  for _, fn in ipairs(F.listeners) do
    local ok, err = pcall(fn, what)
    if not ok and not F.errored then F.errored = true; say("error: " .. tostring(err)) end
  end
end

-- "Copper Vein", or the point's label, or the route's zone
function F.PointName(r, i)
  local p = r and r.points[i]
  if not p then return "" end
  return p[3] or p[4] or (r.category == "Leather" and "Farm here" or "Path")
end

function F.RangeText(r)
  if r.skill then return r.skill[1] .. "-" .. r.skill[2] end
  if r.level then
    -- the page's level line can be a sentence ("Mostly 47-48, with a few 49-50 mobs..."):
    -- show the lowest and highest level in it; the full text is in the route details
    local lo, hi
    for n in r.level:gmatch("%d+") do
      n = tonumber(n)
      if n <= 70 then lo = math.min(lo or n, n); hi = math.max(hi or n, n) end
    end
    if not lo then return "" end
    return "lvl " .. (lo == hi and lo or (lo .. "-" .. hi))
  end
  return ""
end

function F.NodeCount(r)
  local n = 0
  for _, p in ipairs(r.points) do if p[3] then n = n + 1 end end
  return n
end

-- ------------------------------------------------------------------ positions
local function Vec(x, y)
  if CreateVector2D then return CreateVector2D(x, y) end
  return { x = x, y = y, GetXY = function(s) return s.x, s.y end }
end

-- the player's map and position on it (0..1)
function F.PlayerPos()
  if not (C_Map and C_Map.GetBestMapForUnit) then return nil end
  local map = C_Map.GetBestMapForUnit("player")
  if not map then return nil end
  local pos = C_Map.GetPlayerMapPosition(map, "player")
  if not pos then return nil end
  local x, y = pos:GetXY()
  if not x or (x == 0 and y == 0) then return nil end
  return map, x, y
end

-- world position (continent, north, west) of a map point (0..1)
function F.WorldPos(map, x, y)
  if not (C_Map and C_Map.GetWorldPosFromMapPos) then return nil end
  local c, w = C_Map.GetWorldPosFromMapPos(map, Vec(x, y))
  if not w then return nil end
  local wx, wy = w:GetXY()
  return c, wx, wy
end

-- world positions of a route's points, cached on the route
function F.PointWorld(r, i)
  r._w = r._w or {}
  local w = r._w[i]
  if w == nil then
    local p = r.points[i]
    local c, wx, wy = F.WorldPos(r.map, p[1] / 100, p[2] / 100)
    w = c and { c, wx, wy } or false
    r._w[i] = w
  end
  return w or nil
end

-- the continent a map belongs to (walks up the map tree)
function F.ContinentOf(map)
  local guard = 0
  while map and map > 0 and guard < 10 do
    local info = C_Map and C_Map.GetMapInfo and C_Map.GetMapInfo(map)
    if not info then return nil end
    if info.mapType == 2 then return map end
    map = info.parentMapID
    guard = guard + 1
  end
  return nil
end

-- Distance (yards) and bearing (radians, 0 = north, counter-clockwise, like GetPlayerFacing) from
-- the player to point i of route r. mode: "world" (same continent), "map" (same zone, map maths),
-- or nil distance with mode "continent" / "zone" / "noposition".
function F.DistanceTo(r, i, pm, px, py)
  if not pm then pm, px, py = F.PlayerPos() end
  if not pm then return nil, nil, "noposition" end
  local p = r.points[i]
  local pc, pwx, pwy = F.WorldPos(pm, px, py)
  local t = F.PointWorld(r, i)
  if pc and t then
    if pc ~= t[1] then return nil, nil, "continent" end
    local dx, dy = t[2] - pwx, t[3] - pwy
    return math.sqrt(dx * dx + dy * dy), math.atan2(dy, dx), "world"
  end
  if pm == r.map then
    local dx, dy = p[1] / 100 - px, p[2] / 100 - py
    local w, h = r.yards and r.yards[1], r.yards and r.yards[2]
    if C_Map.GetMapWorldSize then
      local mw, mh = C_Map.GetMapWorldSize(pm)
      if mw and mw > 0 then w, h = mw, mh end
    end
    w, h = w or 1000, h or 1000
    return math.sqrt((dx * w) ^ 2 + (dy * h) ^ 2), math.atan2(-dx, -dy), "map"
  end
  return nil, nil, "zone"
end

-- the point nearest the player (same zone), for starting a route where you stand
function F.NearestIndex(r)
  local pm, px, py = F.PlayerPos()
  if not pm then return nil end
  local best, bd
  for i = 1, #r.points do
    local d = F.DistanceTo(r, i, pm, px, py)
    if d and (not bd or d < bd) then best, bd = i, d end
  end
  return best, bd
end

-- ------------------------------------------------------------------ the active route
function F.Active() return F.active, F.index end

function F.Activate(id, index, quiet)
  local r = F.byId[id]
  if not r then return false end
  F.active = r
  CDB.route = r.id
  if not index then
    local near, d = F.NearestIndex(r)
    index = (near and d and d < 600) and near or 1
  end
  F.SetIndex(index, true)
  F.Notify("route")
  if not quiet then
    local pm = F.PlayerPos()
    local where = (pm == r.map) and "" or ("  " .. HEX.muted .. "(in " .. r.zone .. ")|r")
    say("following " .. HEX.gold .. r.zone .. "|r " .. r.name .. ": " .. #r.points .. " points, starting at " .. F.index .. "." .. where)
  end
  return true
end

function F.Stop(quiet)
  if not F.active then return end
  F.active, F.index = nil, nil
  CDB.route, CDB.index = nil, nil
  F.UpdateTarget()
  F.Notify("route")
  if not quiet then say("route stopped.") end
end

function F.SetIndex(i, silent)
  local r = F.active
  if not r then return end
  local n = #r.points
  i = ((math.floor(i) - 1) % n) + 1
  F.index = i
  CDB.index = i
  F.UpdateTarget()
  if not silent then F.Notify("index") end
end

function F.Next() if F.active then F.SetIndex(F.index + 1) end end
function F.Prev() if F.active then F.SetIndex(F.index - 1) end end

-- reached the current point: on to the next one, past any that are already in reach
function F.Advance(pm, px, py)
  local r = F.active
  local n = #r.points
  local i = F.index
  for _ = 1, n do
    i = i + 1
    if i > n then
      i = 1
      say(r.loop and "lap done, round again." or "end of the route, back to the start.")
    end
    local d, _, mode = F.DistanceTo(r, i, pm, px, py)
    if not d or mode ~= "world" and mode ~= "map" or d > F.ARRIVE_YARDS then break end
  end
  F.SetIndex(i)
end

-- ------------------------------------------------------------------ arrow
-- The guide's arrow when the Guide module is on and shows its arrow, else our own.
local guideTarget   -- the table ns.SetExternalTarget made for us

local function GuideAvailable()
  return ns.ModuleEnabled and ns.ModuleEnabled("guide") and ns.SetExternalTarget and ns.GetExternalTarget and ns.ClearExternalTarget and true or false
end

function F.UseGuideArrow()
  if not GuideAvailable() then return false end
  local mode = DB and DB.arrow or "auto"
  if mode == "own" then return false end
  if mode == "guide" then return true end
  return EvergreenDB.arrowShown ~= false
end

local function ReleaseGuide()
  if guideTarget and GuideAvailable() and ns.GetExternalTarget() == guideTarget then ns.ClearExternalTarget() end
  guideTarget = nil
end

function F.TargetTitle()
  local r, i = F.active, F.index
  if not r then return nil end
  return string.format("%s %d/%d", F.PointName(r, i), i, #r.points)
end

function F.UpdateTarget()
  local r, i = F.active, F.index
  if not r then
    ReleaseGuide()
    if F.arrow then F.arrow:Hide() end
    return
  end
  local p = r.points[i]
  if F.UseGuideArrow() then
    local cur = ns.GetExternalTarget()
    if cur == nil or cur == guideTarget then
      ns.SetExternalTarget(r.map, p[1], p[2], "Farming: " .. F.TargetTitle())
      guideTarget = ns.GetExternalTarget()
      F.usingGuide = true
      if F.arrow then F.arrow:Hide() end
      return
    end
  else
    ReleaseGuide()
  end
  -- our own arrow (also while another module has the guide's arrow)
  F.usingGuide = false
  F.ShowArrow()
end

function F.BuildArrow()
  if F.arrow then return F.arrow end
  local a = CreateFrame("Frame", "EvergreenFarmArrow", UIParent)
  a:SetSize(150, 118)
  a:SetPoint("TOP", UIParent, "TOP", 0, -260)
  a:SetMovable(true); a:EnableMouse(true); a:SetClampedToScreen(true)
  a:SetFrameStrata("MEDIUM")
  a:RegisterForDrag("LeftButton")
  a:SetScript("OnDragStart", function(s) if not DB.locked then s:StartMoving() end end)
  a:SetScript("OnDragStop", function(s)
    s:StopMovingOrSizing()
    local pt, _, rp, x, y = s:GetPoint(1); DB.arrowPos = { pt, rp, x, y }
  end)
  -- the guide's sprite sheet: 512x512, 9 x 12 cells of 56x42, 108 rotations
  a.tex = a:CreateTexture(nil, "ARTWORK")
  a.tex:SetSize(108, 81); a.tex:SetPoint("TOP", 0, -2)
  a.tex:SetTexture("Interface\\AddOns\\Evergreen\\arrow")
  a.tex:SetTexCoord(0, 56 / 512, 0, 42 / 512)
  a.title = ns.Skin.Text(a, "GameFontHighlightSmall", "CENTER"); a.title:SetPoint("TOP", a.tex, "BOTTOM", 0, -2)
  a.title:SetWidth(148); a.title:SetWordWrap(false)
  a.dist = ns.Skin.Text(a, "GameFontNormal", "CENTER"); a.dist:SetPoint("TOP", a.title, "BOTTOM", 0, -1)
  a.status = ns.Skin.Text(a, "GameFontDisableSmall", "CENTER"); a.status:SetPoint("TOP", a.dist, "BOTTOM", 0, -1)
  a:SetScript("OnMouseUp", function(_, btn)
    if btn == "RightButton" then if IsShiftKeyDown and IsShiftKeyDown() then F.Prev() else F.Next() end end
  end)
  a:SetScript("OnEnter", function(s)
    GameTooltip:SetOwner(s, "ANCHOR_BOTTOM")
    GameTooltip:AddLine("Evergreen Farming", 1, 0.82, 0)
    if F.active then GameTooltip:AddLine(F.active.zone .. ": " .. F.active.name, 1, 1, 1) end
    GameTooltip:AddLine("Right-click: next point, Shift-right-click: previous", 0.9, 0.9, 0.9)
    GameTooltip:AddLine("Drag to move. /farm stop ends the route.", 0.64, 0.62, 0.58)
    GameTooltip:Show()
  end)
  a:SetScript("OnLeave", function() GameTooltip:Hide() end)
  if DB.arrowPos then a:ClearAllPoints(); a:SetPoint(DB.arrowPos[1], UIParent, DB.arrowPos[2], DB.arrowPos[3], DB.arrowPos[4]) end
  a:Hide()
  F.arrow = a
  return a
end

function F.ShowArrow()
  local a = F.BuildArrow()
  if DB.arrowHidden then a:Hide(); return end
  a.title:SetText(HEX.white .. (F.TargetTitle() or "") .. "|r")
  a:Show()
end

local function SetArrowAngle(rot)
  local cell = math.floor(((rot % TWO_PI) / TWO_PI) * 108 + 0.5) % 108
  local col, row = cell % 9, math.floor(cell / 9)
  F.arrow.tex:SetTexCoord(col * 56 / 512, (col + 1) * 56 / 512, row * 42 / 512, (row + 1) * 42 / 512)
  F.arrowCell = cell
end
F.SetArrowAngle = SetArrowAngle

local function FormatDist(yards)
  if yards >= 1000 then return string.format("%.1f k yd", yards / 1000) end
  return string.format("%d yd", yards)
end
F.FormatDist = FormatDist

local function ArrowTick(r, i, d, bearing, mode)
  local a = F.arrow
  if not a or not a:IsShown() then return end
  if not d then
    a.tex:SetAlpha(0.25); SetArrowAngle(0); a.tex:SetVertexColor(1, 1, 1)
    if mode == "noposition" then
      a.dist:SetText(HEX.muted .. "no position|r"); a.status:SetText("")
    else
      a.dist:SetText(HEX.muted .. r.zone .. "|r")
      a.status:SetText(mode == "continent" and "on another continent" or "in another zone")
    end
    return
  end
  a.tex:SetAlpha(1)
  local facing = GetPlayerFacing and GetPlayerFacing()
  local rot = bearing - (facing or 0)
  SetArrowAngle(rot)
  a.dist:SetText(FormatDist(d))
  a.status:SetText(facing and "" or "no facing: compass bearing")
  if d < F.ARRIVE_YARDS * 1.6 then
    a.tex:SetVertexColor(1, 0.85, 0.35)
  else
    local dev = math.abs(((rot + math.pi) % TWO_PI) - math.pi) / math.pi
    if dev < 0.5 then
      local t = dev * 2; a.tex:SetVertexColor(0.45 + 0.55 * t, 0.85, 0.30 - 0.10 * t)
    else
      local t = (dev - 0.5) * 2; a.tex:SetVertexColor(1.0, 0.85 - 0.60 * t, 0.20)
    end
  end
end

-- ------------------------------------------------------------------ the tick
function F.Tick()
  local r, i = F.active, F.index
  if not r then return end
  local pm, px, py = F.PlayerPos()
  local d, bearing, mode = F.DistanceTo(r, i, pm, px, py)
  F.lastDist, F.lastMode = d, mode
  if d and d <= F.ARRIVE_YARDS then
    F.Advance(pm, px, py)
    r, i = F.active, F.index
    d, bearing, mode = F.DistanceTo(r, i, pm, px, py)
    F.lastDist, F.lastMode = d, mode
  end
  -- the guide's arrow: arrival there clears our target, the journal may take it over
  if F.UseGuideArrow() then
    local cur = ns.GetExternalTarget()
    if F.usingGuide then
      -- cleared (the guide's own arrival check) -> set it again; taken by another module -> own arrow
      if cur ~= guideTarget then F.UpdateTarget() end
    elseif cur == nil then
      F.UpdateTarget()   -- the guide's arrow is free again
    end
  elseif F.usingGuide then
    F.UpdateTarget()
  end
  if not F.usingGuide then ArrowTick(r, i, d, bearing, mode) end
  F.Notify("tick")
end

-- ------------------------------------------------------------------ slash
local HELP = "/farm: routes window. /farm next, /farm prev, /farm stop, /farm <route id>, " ..
  "/farm arrow (auto / own / guide), /farm minimap, /farm map, /farm list"

function F.Slash(msg)
  msg = (msg or ""):gsub("^%s+", ""):gsub("%s+$", "")
  local cmd, rest = msg:match("^(%S*)%s*(.-)$")
  cmd = (cmd or ""):lower()
  if cmd == "" then
    if F.Toggle then F.Toggle() end
    if not F.HasData() then say(F.NO_DATA) end
  elseif cmd == "next" then F.Next()
  elseif cmd == "prev" or cmd == "back" then F.Prev()
  elseif cmd == "stop" or cmd == "clear" then F.Stop()
  elseif cmd == "arrow" then
    local modes = { auto = true, own = true, guide = true }
    DB.arrow = modes[rest] and rest or (DB.arrow == "own" and "auto" or "own")
    if DB.arrow == "guide" and not GuideAvailable() then say("the Guide module is off: using Farming's own arrow.") end
    F.UpdateTarget()
    say("arrow: " .. DB.arrow .. (DB.arrow == "auto" and " (the guide's arrow when the Guide module shows one)" or "") .. ".")
  elseif cmd == "minimap" then
    DB.minimap = not DB.minimap
    F.Notify("options")
    say("minimap points " .. (DB.minimap and "on" or "off") .. ".")
  elseif cmd == "map" then
    DB.worldmap = not DB.worldmap
    F.Notify("options")
    say("world map route " .. (DB.worldmap and "on" or "off") .. ".")
  elseif cmd == "list" then
    if not F.HasData() then say(F.NO_DATA) return end
    for _, r in ipairs(F.routes) do
      print(string.format("  %s%s|r  %s %s  %s%d pts|r", HEX.gold, r.id, r.zone, r.name, HEX.muted, #r.points))
    end
  elseif cmd == "help" or cmd == "?" then
    say(HELP)
  elseif F.byId[msg] then
    F.Activate(msg)
  else
    say("unknown route or command '" .. msg .. "'. " .. HELP)
  end
end

SLASH_EVERGREENFARM1 = "/farm"
SLASH_EVERGREENFARM2 = "/egfarm"
SlashCmdList["EVERGREENFARM"] = function(msg)
  if not DB then say("the Farming module is off (Evergreen - Farming in the AddOns list).") return end
  F.Slash(msg)
end

-- /eg farm: the core's /eg does not know this module, so pass "farm ..." on from in front of it
do
  local core = SlashCmdList["EVERGREEN"]
  if core and not F.egWrapped then
    F.egWrapped = true
    SlashCmdList["EVERGREEN"] = function(msg)
      local c, rest = (msg or ""):match("^%s*(%S+)%s*(.-)%s*$")
      if c and (c:lower() == "farm" or c:lower() == "farming") then return SlashCmdList.EVERGREENFARM(rest) end
      return core(msg)
    end
  end
end

-- key bindings (Bindings.xml)
BINDING_HEADER_EVERGREENFARM = "Evergreen Farming"
BINDING_NAME_EVERGREENFARM_NEXT = "Next route point"
BINDING_NAME_EVERGREENFARM_PREV = "Previous route point"
BINDING_NAME_EVERGREENFARM_TOGGLE = "Routes window"
function EvergreenFarm_Next() if DB then F.Next() end end
function EvergreenFarm_Prev() if DB then F.Prev() end end
function EvergreenFarm_Toggle() if DB and F.Toggle then F.Toggle() end end

-- ------------------------------------------------------------------ boot
local driver = CreateFrame("Frame")
local acc = 0
driver:SetScript("OnUpdate", function(_, e)
  if not F.active then return end
  acc = acc + e
  if acc < TICK then return end
  acc = 0
  F.Tick()
end)

local ev = CreateFrame("Frame")
ev:RegisterEvent("ADDON_LOADED")
ev:RegisterEvent("PLAYER_LOGIN")
ev:SetScript("OnEvent", function(self, event, name)
  if event == "ADDON_LOADED" then
    if name ~= ADDON then return end
    if not ns.ModuleEnabled("farming") then ns.Farm = nil; self:UnregisterAllEvents(); return end
    EvergreenDB.farming = EvergreenDB.farming or {}
    DB = EvergreenDB.farming
    if DB.minimap == nil then DB.minimap = true end
    if DB.worldmap == nil then DB.worldmap = true end
    DB.arrow = DB.arrow or "auto"
    DB.filter = DB.filter or "continent"
    DB.tab = DB.tab or 1
    EvergreenCharDB = EvergreenCharDB or {}
    EvergreenCharDB.farming = EvergreenCharDB.farming or {}
    CDB = EvergreenCharDB.farming
    F.db, F.cdb = DB, CDB
    F.LoadData()
  elseif event == "PLAYER_LOGIN" then
    if not DB then return end
    self:UnregisterEvent("PLAYER_LOGIN")
    F.Notify("login")
    if CDB.route and F.byId[CDB.route] then F.Activate(CDB.route, CDB.index, true) end
  end
end)
