-- Evergreen route: Human ("The King's Road"). Loaded after Data.lua; appends to ns.ROUTES.
-- Step format is documented at the top of Data.lua. Class steps carry cls="PALADIN" etc.
-- This file also defines ns.ALLIANCE_BRACKETS (the shared Alliance 20-60 brackets, ids a4..a11)
-- with every faction-wide Alliance class chain injected; Routes_Dwarf/Gnome/NightElf reuse it
-- and add nothing there. Travel lines in the shared brackets say "your capital" where the
-- races differ, or name Stormwind and Ironforge both.
local ADDON, ns = ...

-- Eastern Kingdoms Alliance map ids (Classic). The rest are already in Data.lua.
ns.MAP_NAMES[1429] = "Elwynn Forest"
ns.MAP_NAMES[1436] = "Westfall"
ns.MAP_NAMES[1433] = "Redridge Mountains"
ns.MAP_NAMES[1431] = "Duskwood"
ns.MAP_NAMES[1426] = "Dun Morogh"
ns.MAP_NAMES[1432] = "Loch Modan"
ns.MAP_NAMES[1437] = "Wetlands"
ns.MAP_NAMES[1438] = "Teldrassil"
ns.MAP_NAMES[1439] = "Darkshore"
ns.MAP_NAMES[1453] = "Stormwind City"
ns.MAP_NAMES[1455] = "Ironforge"
ns.MAP_NAMES[1457] = "Darnassus"
ns.MAP_NAMES[1416] = "Alterac Mountains"
ns.MAP_NAMES[1430] = "Deadwind Pass"

local ELW, WF, RR, DW, DM, LM, WET, DS, SW, IF, DAR, ALT = 1429, 1436, 1433, 1431, 1426, 1432, 1437, 1439, 1453, 1455, 1457, 1416
local ASH, BAR, TN, HIL, STV, DES, STM, ARA, DUS, BAD, SOS, TAN = 1440, 1413, 1441, 1424, 1434, 1443, 1442, 1417, 1445, 1418, 1435, 1446
local FER, HIN, SG, UNG, FEL, BS, AZ, WPL, EPL, WS, SIL, BL, MG = 1444, 1425, 1427, 1449, 1448, 1428, 1447, 1422, 1423, 1452, 1451, 1419, 1450

local SW_CATH = {38,27,"Cathedral of Light, Stormwind",SW}
local SW_RALL = {38,27,"Duthorian Rall, Cathedral of Light, Stormwind",SW}
local SW_SHAW = {76,60,"Master Mathias Shaw, SI:7, Old Town, Stormwind",SW}
local SW_JENNEA = {39,82,"Jennea Cannon, Wizard's Sanctum, Mage Quarter, Stormwind",SW}
local SW_GAKIN = {27,77,"Gakin the Darkbinder, Slaughtered Lamb cellar, Mage Quarter, Stormwind",SW}
local SW_HARRY = {76,53,"Harry Burlguard, Pig and Whistle Tavern, Old Town, Stormwind",SW}

-- ================================================================== Human race-only brackets 1-20
ns.HUMAN_BRACKETS = {
  -- ============================================================ 1-6 Northshire Valley
  {
    id="h1", lv={1,6}, name="Northshire Valley", map=ELW,
    hub="Northshire Abbey", hearth="Already bound to Northshire Abbey", fp="None",
    steps={
      {note="Before you move", t="Turn on Auto Loot. Every class trainer stands inside the abbey; the scroll you spawn with is a free turn-in there. Warlocks need 1s 10c for the Imp. Vendor and repair at the wagon (47,42)."},
      {q="A Threat Within", g={48,43,"Deputy Willem, abbey gate"}, r={49,42,"Marshal McBride, inside the abbey"}},
      {q="Kobold Camp Cleanup", g={49,42,"Marshal McBride"}, o={48,38,"10 Kobold Vermin in the field north of the abbey"}},
      {q="Eagan Peltskinner", g={48,43,"Deputy Willem"}, r={49,40,"Eagan Peltskinner, north-west yard"}},
      {q="Wolves Across the Border", g={49,40,"Eagan Peltskinner"}, o={46,41,"8 Diseased Wolves west of the river (verify count)"}},
      {q="The Stolen Tome", cls="WARLOCK", g={50,43,"Drusilla La Salle, abbey (verify giver)"}, o={54,49,"The tome from Surena Caledon's body among the Defias in the vineyards (verify)"}, r={50,43,"Drusilla La Salle: Summon Imp"}},
      {q="In Favor of the Light", cls="PRIEST", g={50,39,"Priestess Anetta, abbey"}, r={43,66,"Priestess Josetta, upstairs in the Lion's Pride Inn, Goldshire"}},
      {q="Investigate Echo Ridge", g={49,42,"Marshal McBride"}, o={48,32,"10 Kobold Workers at the mouth of Echo Ridge Mine (verify count)"}},
      {q="Brotherhood of Thieves", g={48,43,"Deputy Willem"}, o={54,49,"12 Red Burlap Bandanas from Defias Thugs east across the river (verify count)"}},
      {q="Milly Osworth", g={48,43,"Deputy Willem"}, r={51,39,"Milly Osworth, north-east of the abbey"}},
      {q="Milly's Harvest", g={51,39,"Milly Osworth"}, o={54,49,"8 Milly's Harvest crates in the Northshire Vineyards (verify count)"}},
      {q="Bounty on Garrick Padfoot", g={48,43,"Deputy Willem"}, o={57,48,"Garrick Padfoot at the shack east of the vineyards; loot his head"}},
      {q="Skirmish at Echo Ridge", g={49,42,"Marshal McBride"}, o={48,32,"12 Kobold Laborers inside Echo Ridge Mine (verify count)"}},
      {lv=5},
      {q="Grape Manifest", g={51,39,"Milly Osworth"}, r={50,41,"Brother Neals, top of the abbey spiral stair (verify)"}},
      {q="Report to Goldshire", g={49,42,"Marshal McBride"}, r={42,66,"Marshal Dughan, Goldshire"}},
      {q="Rest and Relaxation", g={46,48,"Falkhaan Isenstrider, fountain outside the valley (verify)"}, r={44,66,"Innkeeper Farley, Lion's Pride Inn, Goldshire"}},
      {forever=true, t="Nothing announced touches Northshire. A Human Hunter presumably starts here in Forever; no trainer or taming chain is published."},
      {lv=6},
    },
  },
  -- ============================================================ 6-12 Goldshire & Elwynn
  {
    id="h2", lv={6,12}, name="Goldshire & Elwynn Forest", map=ELW,
    hub="Goldshire", hearth="Lion's Pride Inn (Innkeeper Farley)", fp="None here; Stormwind (Dungar Longdrink) on the level-11 Westfall hop",
    steps={
      {tr=true, x=42, y=66, t="South-west out of the valley and down the road into Goldshire; kill wolves west of the road on the way."},
      {bind="Goldshire", x=44, y=66},
      {note="Pickup sweep", t="Marshal Dughan outside the inn, William Pestle inside the door, Remy Two Times by the road, Farley for the bind. Learn First Aid (Physician Michelle Belle, upstairs), Skinning and a gathering profession."},
      {q="The Fargodeep Mine", g={42,66,"Marshal Dughan"}, o={39,82,"Scout the upper entrance of Fargodeep Mine"}},
      {q="Kobold Candles", g={43,66,"William Pestle, inside the inn"}, o={39,82,"8 Kobold Candles from the kobolds around Fargodeep (verify count)"}},
      {q="Gold Dust Exchange", g={42,67,"Remy Two Times"}, o={39,82,"10 Gold Dust from kobolds at Fargodeep or Jangolode (verify count)"}},
      {q="Garments of the Light", cls="PRIEST", g={43,66,"Priestess Josetta, upstairs in the inn"}, o={48,68,"Heal Guard Roberts at Crystal Lake with Lesser Heal and Fortitude"}, r={43,66,"Priestess Josetta: Neophyte's Robe"}},
      {q="Lost Necklace", g={34,84,"Bernice Stonefield, Stonefield Farm (verify)"}, r={43,86,"Billy Maclure, Maclure Vineyards"}},
      {q="Princess Must Die!", opt=true, g={35,84,"Ma Stonefield (verify)"}, o={70,79,"Princess, a level-9 boar with two guards at the Brackwell Pumpkin Patch"}},
      {q="Pie for Billy", g={43,86,"Billy Maclure"}, o={33,85,"4 Chunk of Boar Meat from boars in southern Elwynn"}, r={35,84,"Ma Stonefield"}},
      {q="Young Lovers", g={43,90,"Maybell Maclure, house south of the vineyards"}, r={30,86,"Tommy Joe Stonefield; level-9 bears roam here"}},
      {q="Speak with Gramma", g={30,86,"Tommy Joe Stonefield"}, r={35,84,"Gramma Stonefield"}},
      {q="Note to William", g={35,84,"Gramma Stonefield"}, r={43,66,"William Pestle, Goldshire"}},
      {q="Back to Billy", g={35,84,"Ma Stonefield"}, r={43,86,"Billy Maclure"}},
      {q="Goldtooth", g={43,86,"Billy Maclure"}, o={42,78,"Goldtooth inside Fargodeep Mine; hug the left wall"}, r={34,84,"Bernice Stonefield"}},
      {q="A Fishy Peril", g={42,67,"Remy Two Times"}, r={42,66,"Marshal Dughan"}},
      {q="Further Concerns", g={42,66,"Marshal Dughan"}, r={74,72,"Guard Thomas, east bridge"}},
      {q="The Jasperlode Mine", g={42,66,"Marshal Dughan"}, o={62,53,"Scout Jasperlode Mine"}},
      {q="Shipment to Stormwind", g={43,66,"William Pestle"}, r={56,65,"Pestle's Apothecary, Trade District, Stormwind",SW}},
      {q="Collecting Kelp", g={43,66,"William Pestle"}, o={56,69,"4 Crystal Kelp Fronds from the Crystal Lake murlocs; stay on the perimeter (verify count)"}},
      {lv=8},
      {q="Find the Lost Guards", g={74,72,"Guard Thomas"}, o={73,60,"Click the half-eaten body north of the road"}},
      {q="Discover Rolf's Fate", g={73,60,"A half-eaten body"}, o={80,55,"Rolf's corpse in the hills north of Eastvale"}},
      {q="Report to Thomas", g={80,55,"Rolf's corpse"}, r={74,72,"Guard Thomas"}},
      {q="Protect the Frontier", g={74,72,"Guard Thomas"}, o={80,61,"8 Prowlers, 5 Young Forest Bears north of Eastvale (verify counts)"}},
      {q="Red Linen Goods", g={80,69,"Sara Timberlain, Eastvale Logging Camp"}, o={70,79,"6 Red Linen Bandanas from Defias at the Brackwell Pumpkin Patch (verify count)"}},
      {q="A Bundle of Trouble", g={81,66,"Supervisor Raelen, Eastvale"}, o={80,61,"8 Bundles of Wood under the trees around the camp"}},
      {q="Deliver Thomas' Report", g={74,72,"Guard Thomas"}, r={42,66,"Marshal Dughan, Goldshire"}},
      {q="Report to Gryan Stoutmantle", g={74,72,"Guard Thomas"}, r={56,47,"Gryan Stoutmantle, Sentinel Hill tower, Westfall",WF}},
      {lv=10},
      {q="The Escape", g={43,66,"William Pestle (wait a moment after Collecting Kelp)"}, r={43,90,"Maybell Maclure"}},
      {q="Cloth and Leather Armor", g={42,66,"Marshal Dughan"}, r={80,69,"Sara Timberlain, Eastvale"}},
      {q="Westbrook Garrison Needs Help!", g={42,66,"Marshal Dughan"}, r={24,74,"Deputy Rainer, Westbrook Garrison"}},
      {q="Elmore's Task", g={42,66,"Grimand Elmore, Goldshire smithy (verify)"}, r={62,36,"Grimand Elmore, Dwarven District, Stormwind (verify)",SW}},
      {tr=true, x=62, y=70, map=SW, any=true, t="Level 10: Stormwind. Train, then every level-10 class quest below ends here; walk up the road once and do them all."},
      {q="A Warrior's Training", cls="WARRIOR", g={41,66,"Lyria Du Lac, Goldshire smithy (verify)"}, r=SW_HARRY},
      {q="Bartleby the Drunk", cls="WARRIOR", g=SW_HARRY, r={76,53,"Bartleby, same tavern",SW}},
      {q="Beat Bartleby", cls="WARRIOR", g={76,53,"Bartleby",SW}, o={76,53,"Duel Bartleby until he yields; do not kill him",SW}, r={76,53,"Bartleby",SW}},
      {q="Bartleby's Mug", cls="WARRIOR", g={76,53,"Bartleby",SW}, r={76,53,"Harry Burlguard: Defensive Stance, Taunt, Sunder Armor",SW}},
      {q="Marshal Haggard", cls="WARRIOR", g=SW_HARRY, r={82,67,"Marshal Haggard, Eastvale Logging Camp (verify)"}},
      {q="Dead-tooth Jack", cls="WARRIOR", g={82,67,"Marshal Haggard (verify)"}, o={89,79,"Haggard's Badge from Dead-tooth Jack's camp north-east of Eastvale (verify)"}, r={82,67,"Marshal Haggard: Haggard's Axe, Hammer, Dagger or Sword"}},
      {q="Seek out SI:7", cls="ROGUE", g={44,66,"Keryn Sylvius, upstairs in the inn"}, r=SW_SHAW},
      {q="Snatch and Grab", cls="ROGUE", g=SW_SHAW, o={60,86,"Pickpocket the Shipping Schedule from the Defias Dockmaster at Jerod's Landing (verify)"}, r={76,60,"Master Mathias Shaw: Blade of Cunning",SW}},
      {q="Desperate Prayer", cls="PRIEST", g={43,66,"Priestess Josetta, upstairs in the inn (or Nara Meideros, Cathedral of Light)"}, r={43,66,"Priestess Josetta: Desperate Prayer"}},
      {q="Speak with Jennea", cls="MAGE", g={43,66,"Zaldimar Wefhellt, upstairs in the inn (verify)"}, r=SW_JENNEA},
      {q="Mirror Lake", cls="MAGE", g=SW_JENNEA, o={29,62,"Fill the sample at the base of the Mirror Lake waterfall, west of Goldshire"}, r={39,82,"Jennea Cannon: Ley Orb or Ley Staff",SW}},
      {q="The Slaughtered Lamb", cls="WARLOCK", g={44,66,"Maximillion, inn basement (verify giver)"}, r=SW_GAKIN},
      {q="Surena Caledon", cls="WARLOCK", g=SW_GAKIN, o={70,78,"Kill Surena Caledon (9) at the Brackwell Pumpkin Patch; loot her choker (verify)"}, r=SW_GAKIN},
      {q="The Binding", p=1, cls="WARLOCK", g=SW_GAKIN, o={27,77,"Summon and defeat a Voidwalker at Gakin's circle",SW}, r={27,77,"Gakin the Darkbinder: Summon Voidwalker",SW}},
      {q="Wanted: Hogger", opt=true, g={25,75,"Wanted poster, Westbrook Garrison"}, o={27,86,"Hogger (11 elite) at Forest's Edge; group"}, r={42,66,"Marshal Dughan"}},
      {q="Riverpaw Gnoll Bounty", g={24,74,"Deputy Rainer, Westbrook Garrison"}, o={27,86,"8 Painted Gnoll Armbands from Riverpaw gnolls at Forest's Edge (verify count)"}},
      {q="The Collector", g={27,86,"Gold Pickup Schedule, dropped by a Forest's Edge gnoll"}, r={42,66,"Marshal Dughan"}},
      {q="Manhunt", g={42,66,"Marshal Dughan"}, o={71,81,"Morgan the Collector at Brackwell"}},
      {q="Bounty on Murlocs", g={74,72,"Guard Thomas"}, o={70,84,"8 Torn Murloc Fins on the river coast south of the bridge"}},
      {q="Tome of Divinity", p=1, cls="PALADIN", g={41,66,"Brother Wilhelm, Goldshire smithy"}, r=SW_RALL},
      {q="The Tome of Divinity", p=1, cls="PALADIN", g=SW_RALL, o={38,27,"Read the tome Rall hands you",SW}, r=SW_RALL},
      {q="The Tome of Divinity", p=2, cls="PALADIN", g=SW_RALL, o={62,68,"10 Linen Cloth to Stephanie Turner, Trade District",SW}, r=SW_RALL},
      {q="The Tome of Divinity", p=3, cls="PALADIN", g=SW_RALL, r={38,27,"Gazin Tenorm, Cathedral of Light",SW}},
      {q="The Symbol of Life", cls="PALADIN", g={38,27,"Gazin Tenorm",SW}, o={71,43,"Resurrect Henze Faulk on the island at Heroes' Vigil, Stone Cairn Lake (verify)"}, r={71,43,"Henze Faulk"}},
      {q="The Tome of Divinity", p=4, cls="PALADIN", g={71,43,"Henze Faulk"}, o={71,43,"A Defias Script from the Defias Rogue Wizards around the island (verify count)"}, r={38,27,"Gazin Tenorm: Redemption",SW}},
      {tr=true, x=56, y=47, map=WF, t="Westfall hop: road west, Furlbrow's Deed at the Jansen Stead if you have it, Report to Gryan at Sentinel Hill."},
      {q="A Swift Message", g={57,47,"Quartermaster Lewis, Sentinel Hill tower",WF}, r={57,53,"Thor, gryphon master",WF}},
      {fp="Sentinel Hill", x=57, y=53, map=WF},
      {q="Continue to Stormwind", g={57,53,"Thor",WF}, r={66,62,"Dungar Longdrink, Trade District, Stormwind",SW}},
      {fp="Stormwind", x=66, y=62, map=SW},
      {q="Return to Lewis", g={66,62,"Dungar Longdrink",SW}, r={57,47,"Quartermaster Lewis, Sentinel Hill",WF}},
      {forever=true, t="No source reports Elwynn changes beyond the Human Hunter trainer. Wetlands is the announced Alliance expansion and it comes at 20."},
      {lv=12},
    },
  },
  -- ============================================================ 12-17 Westfall
  {
    id="h3", lv={12,17}, name="Westfall", map=WF,
    hub="Sentinel Hill", hearth="Sentinel Hill inn (Innkeeper Heather)", fp="Sentinel Hill (Thor)",
    steps={
      {tr=true, x=59, y=19, t="Ride in on the north road from Elwynn; the Jansen Stead and Saldean's Farm are on the way. Save 5 Hops and 5 Flasks of Oil from the Harvest Watchers."},
      {q="The Forgotten Heirloom", g={59,19,"Farmer Furlbrow, the Jansen Stead"}, o={51,22,"Furlbrow's Pocket Watch in the wardrobe at Furlbrow's Pumpkin Farm; clear the Defias from the house"}},
      {q="Westfall Stew", p=1, g={60,19,"Verna Furlbrow"}, r={56,31,"Salma Saldean, inside the Saldean farmhouse"}},
      {q="Poor Old Blanchy", g={60,19,"Verna Furlbrow"}, o={51,22,"8 Handful of Oats from the sacks in the fields"}},
      {q="The Killing Fields", g={56,30,"Farmer Saldean"}, o={54,26,"20 Harvest Watchers between Saldean's and Furlbrow's"}},
      {q="Westfall Stew", p=2, g={56,31,"Salma Saldean"}, o={54,30,"3 Goretusk Snouts, 3 Stringy Vulture Meat, 3 Murloc Eyes, 3 Okra (Harvest Watchers)"}},
      {q="Goretusk Liver Pie", g={56,31,"Salma Saldean"}, o={50,35,"8 Goretusk Livers from the open fields"}},
      {bind="Sentinel Hill", x=52, y=53},
      {q="The People's Militia", p=1, g={56,47,"Gryan Stoutmantle, top of the tower"}, o={44,25,"15 Defias Trappers, 15 Smugglers at Jangolode Mine and Molsen Farm (46,38)"}},
      {q="Patrolling Westfall", g={56,48,"Captain Danuvin, tower base (verify)"}, o={36,29,"8 Gnoll Paws at the Riverpaw camps"}},
      {q="Red Leather Bandanas", g={54,53,"Scout Galiaan, by the lumber mill"}, o={44,25,"15 Red Leather Bandanas from Defias in Jangolode Mine"}},
      {man="North loop: Furlbrow's farm (51,22), Jangolode Mine (44,25), Longshore murlocs (34,21) for eyes, gnolls (36,29), back through Saldean's fields.", x=44, y=25},
      {lv=14},
      {q="The People's Militia", p=2, g={56,47,"Gryan Stoutmantle"}, o={44,69,"15 Defias Pillagers, 15 Looters at Moonbrook and Alexston Farmstead (38,55)"}},
      {q="Report to Jennea", cls="MAGE", g=SW_JENNEA, r=SW_JENNEA},
      {q="Investigate the Blue Recluse", cls="MAGE", g=SW_JENNEA, o={45,90,"Blue Recluse tavern, Mage Quarter: reveal and capture three Rift Spawn with the cantation and coffers",SW}, r=SW_JENNEA},
      {q="Gathering Materials", cls="MAGE", g=SW_JENNEA, o={35,19,"10 Linen Cloth; 6 Charged Rift Gems from crates in Silver Stream Mine, north Loch Modan (Tram to Ironforge, fly Thelsamar)",LM}, r={44,79,"Wynne Larson, Larson Clothiers, Mage Quarter",SW}},
      {q="Manaweave Robe", cls="MAGE", g={44,79,"Wynne Larson",SW}, r={44,79,"Wynne Larson: Manaweave Robe",SW}},
      {q="Keeper of the Flame", g={30,86,"Captain Grayson, Westfall Lighthouse"}, o={30,86,"Hand in 5 Flasks of Oil saved from the Harvest Watchers"}},
      {q="The Coast Isn't Clear", g={30,86,"Captain Grayson"}, o={35,86,"7 Murloc Tidehunters, 7 Murloc Oracles on the shore"}},
      {q="The Coastal Menace", opt=true, g={30,86,"Captain Grayson"}, o={30,80,"Old Murk-Eye (20 elite) wanders the Gold Coast; soloable at 20"}},
      {q="Thunderbrew Lager", opt=true, g={45,80,"Grimbooze Thunderbrew, Dagger Hills"}, o={45,80,"Hand in 5 Hops"}},
      {lv=16},
      {tr=true, x=49, y=30, map=SW, any=true, t="Stormwind at 16: train. Baros Alexston (Cathedral Square) gives Humble Beginnings. Dwarven District inn: Collecting Memories, Oh Brother, Underground Assault for the Deadmines at 19-20."},
      {q="The People's Militia", p=3, g={56,47,"Gryan Stoutmantle"}, o={38,70,"Defias Highwaymen, Pathstalkers, Knuckledusters at Dermont's Place and the Dagger Hills (verify counts)"}},
      {q="The Defias Brotherhood", p=1, g={56,47,"Gryan Stoutmantle"}, r={26,44,"Wiley the Black, upstairs in the Lakeshire Inn, Redridge",RR}},
      {forever=true, t="Nothing announced touches Westfall or the Deadmines."},
      {lv=17},
    },
  },
  -- ============================================================ 17-20 Redridge
  {
    id="h4", lv={17,20}, name="Redridge Mountains, then the Deadmines", map=RR,
    hub="Lakeshire", hearth="Lakeshire Inn (Innkeeper Brianna)", fp="Lakeshire (Ariena Stormfeather), Darkshire (Felicia Maline) at 19",
    steps={
      {tr=true, x=31, y=60, t="In from Elwynn on the east road. Guard Parker at Three Corners, then Deputy Feldon before the bridge."},
      {q="Encroaching Gnolls", g={20,70,"Guard Parker, Three Corners (verify)"}, r={31,60,"Deputy Feldon, before the bridge"}},
      {q="Assessing the Threat", g={31,60,"Deputy Feldon"}, o={39,32,"10 Redridge Mongrels, 6 Poachers at the gnoll camps in the Redridge Canyons"}},
      {fp="Lakeshire", x=31, y=59},
      {bind="Lakeshire", x=26, y=44},
      {note="Lakeshire sweep", t="Foreman Oslow by the bridge, Shawn on the west dock, Verner Osgood at the smithy, Chef Breanna, Magistrate Solomon in the town hall, Marshal Marris, Dockmaster Baren, Darcy and Barkeep Daniels in the inn, Wiley the Black upstairs, Martie Jainrose."},
      {q="The Lost Tools", g={30,46,"Foreman Oslow, by the bridge (verify)"}, o={41,54,"Oslow's Toolbox in the sunken rowboat on the lake bottom"}},
      {q="Hilary's Necklace", g={29,46,"Shawn, west dock (verify)"}, o={38,54,"Glinting Mud on the lake bottom east under the bridge"}, r={29,46,"Hilary, dock"}},
      {q="The Price of Shoes", g={31,47,"Verner Osgood, smithy"}, r={42,66,"Smith Argus, Goldshire",ELW}},
      {q="Return to Verner", g={42,66,"Smith Argus, Goldshire",ELW}, r={31,47,"Verner Osgood"}},
      {q="Underbelly Scales", g={31,47,"Verner Osgood"}, o={42,32,"Black Dragon Whelps south of the lake (verify count and spot)"}},
      {q="Redridge Goulash", g={28,44,"Chef Breanna, north-west house (verify)"}, o={46,76,"5 Crisp Spider Meat (Tarantulas), 5 Great Goretusk Snouts, 5 Tough Condor Meat (Dire Condors)"}},
      {q="Messenger to Stormwind", g={30,44,"Magistrate Solomon, town hall (verify)"}, r={32,50,"General Marcus Jonathan, Stormwind gate",SW}},
      {q="Messenger to Westfall", g={32,50,"General Marcus Jonathan",SW}, r={56,47,"Gryan Stoutmantle, Sentinel Hill",WF}},
      {q="A Free Lunch", g={26,44,"Darcy, Lakeshire Inn"}, o={41,45,"Follow the quest text (verify)"}},
      {q="Dry Times", g={26,44,"Barkeep Daniels, Lakeshire Inn"}, o={74,45,"Cask of Merlot (Roberto Pupellyverbos, Stormwind Trade District), Skin of Sweet Rum (Barkeep Dobbins, Goldshire), Bottle of Moonshine (Barkeep Hann, Darkshire), Keg of Thunderbrew Lager (Grimbooze, Westfall)",DW}},
      {q="Selling Fish", g={30,47,"Dockmaster Baren (verify)"}, o={41,45,"10 Spotted Sunfish from the lake murlocs"}},
      {q="Murloc Poachers", g={30,47,"Dockmaster Baren (verify)"}, o={48,70,"8 Murloc Fins"}},
      {q="The Defias Brotherhood", p=2, g={26,44,"Wiley the Black, inn upstairs"}, r={56,47,"Gryan Stoutmantle, Sentinel Hill",WF}},
      {q="Redridge Rendezvous", cls="ROGUE", g=SW_SHAW, r={30,45,"Lucius, Lakeshire (verify)"}},
      {q="Alther's Mill", cls="ROGUE", g={30,45,"Lucius"}, o={44,44,"Pick the practice lockboxes at Alther's Mill east of town until Lucius's Lockbox opens; take the Token of Thievery (verify coords)"}, r={30,45,"Lucius: Certificate of Thievery"}},
      {man="Grind south of the lake: Great Goretusks, Tarantulas, Dire Condors (46,76), whelps, lake murlocs for fish and fins.", x=44, y=70},
      {lv=19},
      {tr=true, x=74, y=45, map=DW, t="Road south from Three Corners into Duskwood and along to Darkshire for the flight point and the Moonshine."},
      {fp="Darkshire", x=74, y=45, map=DW},
      {tr=true, x=32, y=50, map=SW, any=true, t="Fly to Stormwind: Marcus Jonathan at the gate, Roberto's Merlot, Shaw at SI:7 for the Defias chain, train. Goldshire on the way out: Smith Argus, Barkeep Dobbins. Hearth to Lakeshire."},
      {q="The Defias Brotherhood", p=3, g={56,47,"Gryan Stoutmantle",WF}, r=SW_SHAW},
      {q="The Defias Brotherhood", p=4, g=SW_SHAW, r={56,47,"Gryan Stoutmantle",WF}},
      {q="Arcane Feedback", cls="PRIEST", g={38,27,"Brother Joshua, Cathedral of Light (verify giver)",SW}, r={38,27,"Brother Joshua: Feedback",SW}},
      {lv=20},
      {tr=true, x=56, y=47, map=WF, t="Fly to Sentinel Hill for the Deadmines finish."},
      {q="The Defias Brotherhood", p=5, g={56,47,"Gryan Stoutmantle",WF}, o={45,69,"Kill the Defias Messenger; spawns at the east end of Moonbrook, patrols to the Gold Coast Quarry and Jangolode",WF}, r={56,47,"Gryan Stoutmantle",WF}},
      {q="The Defias Traitor", g={56,48,"The Defias Traitor, tower base",WF}, o={43,69,"Escort him to Moonbrook",WF}, r={56,47,"Gryan Stoutmantle",WF}},
      {q="The Defias Brotherhood", p=6, opt=true, g={56,47,"Gryan Stoutmantle",WF}, o={43,72,"Edwin VanCleef in the Deadmines (entrance in Moonbrook's barn); group",WF}, r={56,47,"Gryan Stoutmantle",WF}},
      {q="Red Silk Bandanas", opt=true, g={56,47,"Scout Riell, tower top",WF}, o={43,72,"Defias in the Deadmines",WF}},
      {forever=true, t="Nothing announced touches Redridge. Dalaran opens in Alterac at 28-33; it matters from the 25-30 bracket on."},
    },
  },
}

-- ================================================================== Shared Alliance brackets 20-60
-- Defined once here. Faction-wide class chains (paladin Tome of Valor / Verigan's Fist / Warhorse /
-- Chillwind / Charger, rogue Poisons and Ravenholdt, warlock Succubus / Felhunter / Felsteed / Imp's
-- Request / Dreadsteed, warrior Fire Hardened / Islander / Whirlwind / Fallen Hero, mage Tabetha and
-- Xylem, priest Cenarion Aid, hunter Hunter's Charm, druid Torwa Pathfinder) are all in here.
local RAVEN = {76,43,"Lord Jorach Ravenholdt, Ravenholdt Manor, north of Durnholde, Hillsbrad (verify)",HIL}
local STRAHAD = {62,35,"Strahad Farsan, hill above Ratchet, Barrens (verify)",BAR}
local BATHRAH = {80,67,"Bath'rah the Windwatcher, ruins north-east of Tarren Mill, Alterac",ALT}
local TABETHA = {43,57,"Tabetha, her farm, Dustwallow Marsh",DUS}
local XYLEM = {28,50,"Archmage Xylem's tower, Azshara (the elf at 28,50 teleports you up)",AZ}
local OGTINC = {42,43,"Ogtinc, cliff above the Shattered Strand, Azshara",AZ}
local IMPSY = {40,40,"Impsy, just north of Bloodvenom Falls, Felwood (verify)",FEL}
local TORWA = {72,76,"Torwa Pathfinder, bluff by the waterfalls at the bottom of the Tanaris ramp, Un'Goro",UNG}
local ASHLAM = {43,84,"Commander Ashlam Valorfist, Chillwind Camp, Western Plaguelands (verify)",WPL}
local ST = {70,54,"Temple of Atal'Hakkar, Swamp of Sorrows",SOS}
local KLANNOC = {68,48,"Klannoc Macleod, Fray Island south of Ratchet, Barrens",BAR}

ns.ALLIANCE_BRACKETS = {
  -- ============================================================ 20-25 Duskwood / Wetlands / Ashenvale
  {
    id="a4", lv={20,25}, name="Duskwood, the Wetlands, then Ashenvale", map=DW,
    hub="Darkshire, Menethil Harbor, Astranaar", hearth="Darkshire (Trelayne) 20-22, Menethil (Helbrek) in the Wetlands, Astranaar (Kimlya) for Ashenvale", fp="Darkshire, Thelsamar, Menethil, Auberdine, Astranaar",
    steps={
      {tr=true, x=74, y=45, t="Fly to Darkshire from your capital (Stormwind direct; Ironforge via Stormwind). Rebind."},
      {bind="Darkshire", x=74, y=45},
      {q="A Watchful Eye", opt=true, g={64,68,"Theocritus, Tower of Azora, Elwynn",ELW}, o={65,68,"Follow the quest text",ELW}},
      {q="Raven Hill", g={74,45,"Elaine Carevin, Darkshire"}, r={18,56,"Raven Hill"}},
      {q="Deliveries to Sven", g={74,45,"Elaine Carevin"}, r={7,33,"Sven Yorgen, his camp in the north-west"}},
      {q="Eight-Legged Menaces", g={45,66,"Watcher Dodds"}, o={40,60,"Giant spiders along the road (verify)"}},
      {q="Wolves at Our Heels", g={7,33,"Lars, Sven's camp"}, o={12,40,"Wolves around the camp (verify)"}},
      {q="Supplies from Darkshire", g={27,31,"Abercrombie, shack north of Raven Hill"}, r={74,45,"Darkshire"}},
      {q="The Night Watch", p=1, g={74,45,"Commander Althea Ebonlocke"}, o={79,70,"Skeletons at Tranquil Gardens Cemetery"}},
      {q="Seasoned Wolf Kabobs", g={74,45,"Chef Grual"}, o={64,72,"Wolf meat around the Rotting Orchard (verify)"}},
      {q="Gather Rot Blossoms", g={74,45,"Tavernkeep Smitts"}, o={24,36,"Rot Blossoms from the Raven Hill Cemetery undead"}},
      {q="Deliver the Thread", g={74,45,"Madame Eva"}, r={81,59,"Blind Mary"}},
      {q="The Totem of Infliction", g={74,45,"Madame Eva"}, o={20,45,"Skeletal Fiends and Horrors at Raven Hill, Nightbane worgen, spiders (verify)"}},
      {man="The Weathered Grave at Raven Hill Cemetery (17,28) starts the Mor'Ladim chain; read it now.", x=17, y=28},
      {lv=22},
      {tr=true, x=11, y=52, map=WET, t="Fly Darkshire to Thelsamar (via your capital), ride north through Dun Algaz into the Wetlands. Menethil Harbor."},
      {q="The Algaz Gauntlet", g={22,80,"Mountaineer Rockgar, Dun Algaz tunnel (verify)"}, r={11,52,"Menethil Harbor"}},
      {bind="Menethil", x=11, y=52, map=WET},
      {fp="Menethil", x=11, y=52, map=WET},
      {q="Daily Delivery", g={49,39,"Einar Stonegrip, Wetlands road",WET}, r={11,52,"Menethil Harbor",WET}},
      {q="In Search of The Excavation Team", p=1, g={11,52,"Tarrel Rockweaver, Menethil",WET}, r={33,38,"Merrin Rockweaver, Whelgar's Excavation Site",WET}},
      {q="Fiora Longears", g={11,52,"Red Jack Flint, Menethil docks",WET}, r={37,44,"Fiora Longears, Auberdine pier",DS}},
      {q="Young Crocolisk Skins", g={11,52,"James Halloran, Menethil",WET}, o={20,50,"Young Crocolisks in the marsh east of town (verify)",WET}},
      {q="Claws from the Deep", g={11,52,"Karl Boran, Menethil",WET}, o={14,38,"Bluegill murloc camps down the west coast",WET}},
      {q="The Greenwarden", g={11,52,"First Mate Fitzsimmons, Menethil inn",WET}, r={56,40,"Rethiel the Greenwarden",WET}},
      {q="Digging Through the Ooze", g={11,52,"Sida, Menethil",WET}, o={44,24,"Black Oozes",WET}},
      {q="Ormer's Revenge", p=1, g={33,38,"Ormer Ironbraid, Whelgar's",WET}, o={25,47,"Raptors around the excavation",WET}},
      {q="The Test of Righteousness", p=1, cls="PALADIN", g=SW_RALL, r={52,36,"Jordan Stilwell, outside Ironforge's front gate, Dun Morogh",DM}},
      {q="Bailor's Ore Shipment", cls="PALADIN", g={35,49,"Bailor Stonehand, Thelsamar",LM}, o={72,22,"Jordan's Ore Shipment from the Mo'grosh ogres north-east across the loch (verify)",LM}, r={35,49,"Bailor Stonehand: Jordan's Refined Ore Shipment",LM}},
      {q="Seeking the Kor Gem", cls="PALADIN", g={37,42,"Thundris Windweaver, Auberdine (verify)",DS}, o={14,15,"Corrupted Kor Gem from the naga just inside Blackfathom Deeps, Ashenvale",ASH}, r={37,42,"Thundris Windweaver: Purified Kor Gem",DS}},
      {man="Paladin: Whitestone Oak Lumber from the Goblin Woodcarvers in the Deadmines (verify drop) and Jordan's Smithing Hammer on a box in the Shadowfang Keep stables. Loot both on dungeon runs.", cls="PALADIN", x=43, y=72, map=WF},
      {q="The Test of Righteousness", p=2, cls="PALADIN", g={52,36,"Jordan Stilwell, Ironforge gate",DM}, r={52,36,"Jordan Stilwell: Verigan's Fist",DM}},
      {q="Mathias and the Defias", cls="ROGUE", g=SW_SHAW, r={57,73,"Agent Kearnen, abandoned tower south-east of Sentinel Hill, Westfall (verify)",WF}},
      {q="Klaven's Tower", cls="ROGUE", g={57,73,"Agent Kearnen",WF}, o={60,80,"Pickpocket the Defias Tower Key from a Malformed Defias Drone; Sap or kill Klaven Mortwake in the tower on the Duskwood border; take his journal from the chest (verify coords)",WF}, r={76,60,"Master Mathias Shaw: Poisons, Recipe: Thistle Tea",SW}},
      {q="The Touch of Zanzil", cls="ROGUE", opt=true, g=SW_SHAW, o={77,68,"Doc Mixilpixil, Stormwind Barracks cellar: Simple Wildflowers, Leaded Vial, Bronze Tube, Light Chartreuse thread",SW}, r={77,68,"Doc Mixilpixil",SW}},
      {q="Devourer of Souls", cls="WARLOCK", g=SW_GAKIN, r={45,58,"Takar the Seer, near Camp Taurajo, southern Barrens (Horde land; ride the Gold Road)",BAR}},
      {q="Heartswood", cls="WARLOCK", g={45,58,"Takar the Seer",BAR}, o={22,20,"The Heartswood in the ruins of Ordil'Aran, north-west Ashenvale (verify)",ASH}, r=SW_GAKIN},
      {q="The Binding", p=2, cls="WARLOCK", g=SW_GAKIN, o={27,77,"Summon and defeat a Succubus at Gakin's circle",SW}, r={27,77,"Gakin the Darkbinder: Summon Succubus",SW}},
      {tr=true, x=37, y=44, map=DS, t="The Bravery: Menethil to Auberdine. Turn in Fiora Longears on the pier, get the flight point, road south-east into Ashenvale."},
      {fp="Auberdine", x=36, y=46, map=DS},
      {tr=true, x=36, y=50, map=ASH, t="Maestra's Post (26,38) first, then Astranaar. Rebind."},
      {bind="Astranaar", x=36, y=50, map=ASH},
      {fp="Astranaar", x=36, y=50, map=ASH},
      {q="Bathran's Hair", g={26,38,"Orendil Broadleaf, Maestra's Post",ASH}, o={31,22,"Plant bundles at Bathran's Haunt",ASH}},
      {q="Orendil's Cure", g={26,38,"Orendil Broadleaf",ASH}, r={36,50,"Astranaar",ASH}},
      {q="Raene's Cleansing", p=1, g={36,50,"Raene Wolfrunner, Astranaar",ASH}, o={34,37,"Dal Bloodclaw; then Teronis' corpse at Lake Falathim",ASH}},
      {q="The Zoram Strand", g={36,50,"Shindrell Swiftfire, Astranaar",ASH}, o={13,26,"Naga on the Zoram Strand",ASH}},
      {q="On Guard in Stonetalon", g={36,50,"Sentinel Thenysil, Astranaar",ASH}, r={59,66,"Kaela Shadowspear, Webwinder Path camp",ASH}},
      {q="Elemental Bracers", g={50,67,"Sentinel Velene Starstrike, Silverwind Refuge",ASH}, o={50,61,"Foulweald furbolgs (verify)",ASH}},
      {q="The Orb of Soran'ruk", cls="WARLOCK", opt=true, g={49,57,"Doan Karhan, south of Camp Taurajo, Barrens (verify)",BAR}, o={14,15,"3 Soran'ruk Fragments from Twilight Acolytes in Blackfathom Deeps; 1 Large fragment from a Shadowfang Keep wizard",ASH}, r={49,57,"Doan Karhan: Orb or Staff of Soran'ruk",BAR}},
      {q="The Manor, Ravenholdt", cls="ROGUE", opt=true, g=RAVEN, r=RAVEN},
      {forever=true, t="Wetlands is announced as expanded, and a new Menethil-Southshore-Auberdine boat is reported. If the new content is dense it replaces the Ashenvale boat trip (verify)."},
      {lv=25},
    },
  },
  -- ============================================================ 25-30 Duskwood II / Redridge II / Wetlands II / Stonetalon / Hillsbrad
  {
    id="a5", lv={25,30}, name="Duskwood II, Redridge II, the Wetlands, Stonetalon, Hillsbrad", map=DW,
    hub="Darkshire, Lakeshire, Menethil, Astranaar, Southshore", hearth="Darkshire 25-27, Menethil at 28, Southshore (Anderson) once you land there", fp="Stonetalon Peak, Southshore, Thalanaar",
    steps={
      {tr=true, x=74, y=45, t="Fly Astranaar to Auberdine, boat to Menethil, fly to Darkshire. Rebind."},
      {bind="Darkshire", x=74, y=45},
      {q="Look to the Stars", g={74,45,"Viktori Prism'Antras, Darkshire"}, o={74,45,"Needs a Bronze Tube (engineer or auction house)"}},
      {q="Worgen in the Woods", p=1, g={74,45,"Calor, Darkshire"}, o={73,75,"Nightbane worgen at Gutspill's cave"}},
      {q="Worgen in the Woods", p=2, g={74,45,"Calor"}, o={73,75,"Gutspill's cave"}},
      {q="The Night Watch", p=2, g={74,45,"Commander Althea Ebonlocke"}, o={24,36,"Follow the quest text (verify)"}},
      {q="Return to Jitters", g={74,45,"Chef Grual"}, r={18,56,"Jitters, Raven Hill"}},
      {q="Proving Your Worth", g={7,33,"Sven Yorgen"}, o={12,38,"Follow the quest text (verify)"}},
      {q="Seeing What Sven Sees?", g={7,33,"Sven Yorgen"}, o={7,33,"Follow the quest text (verify)"}},
      {q="Sven's Camp", g={7,33,"Sven Yorgen"}, o={7,33,"Follow the quest text (verify)"}},
      {q="Morbent Fel", opt=true, g={7,33,"Sven Yorgen"}, o={17,28,"Morbent Fel at Forlorn Rowe; needs the Lightforged Blade; group"}},
      {q="High Sorcerer Andromath", cls="MAGE", g=SW_JENNEA, r={39,82,"High Sorcerer Andromath, Wizard's Sanctum",SW}},
      {q="Ur's Treatise on Shadow Magic", cls="MAGE", g={39,82,"High Sorcerer Andromath",SW}, o={79,49,"The book in Morganth's library at the top of the Tower of Ilgalar, east Redridge",RR}, r={39,82,"High Sorcerer Andromath",SW}},
      {q="Pristine Spider Silk", cls="MAGE", g={39,82,"High Sorcerer Andromath",SW}, o={40,60,"Pristine Spider Silk from the giant spiders of Duskwood or the Wetlands (verify mob)"}, r={39,82,"High Sorcerer Andromath",SW}},
      {q="Astral Knot Garment", cls="MAGE", g={39,82,"High Sorcerer Andromath",SW}, r={39,82,"Andromath: Astral Knot Garment",SW}},
      {lv=27},
      {tr=true, x=30, y=45, map=RR, t="Fly to Lakeshire."},
      {q="Blackrock Bounty", g={30,45,"Guard Howe, Lakeshire",RR}, o={39,40,"Blackrock orcs",RR}},
      {q="Shadow Magic", g={32,45,"Marshal Marris",RR}, o={63,50,"Midnight Orbs at the tower",RR}},
      {q="Tharil'zun", g={32,45,"Marshal Marris",RR}, o={67,55,"Tharil'zun at Stonewatch Keep",RR}},
      {q="WANTED: Lieutenant Fangore", g={30,45,"Wanted poster, Lakeshire",RR}, o={80,38,"Lieutenant Fangore",RR}},
      {q="An Unwelcome Guest", g={30,45,"Martie Jainrose",RR}, o={16,49,"Bellygrub the boar",RR}},
      {q="Missing in Action", opt=true, g={35,9,"Corporal Keeshan, Render's Camp",RR}, o={30,45,"Escort him to Lakeshire",RR}, r={30,45,"Lakeshire",RR}},
      {q="Retrieval for Mauren", g={43,80,"Collin Mauren, Mage Quarter, Stormwind",SW}, o={32,66,"Blackened Basilisks, Charred Vale, Stonetalon",STM}},
      {q="The Missing Diplomat", p=1, g={49,30,"Thomas, Cathedral Square, Stormwind",SW}, r={38,27,"Bishop Farthing, Cathedral",SW}},
      {man="Warrior: Fire Hardened armor, all three optional. Grimand Elmore (Dwarven District): Burning Blood, 20 from the Nightbane worgen in Roland's Doom plus a Burning Rock from Gutspill, for the Coif. Klockmort Spannerspan (Tinker Town): Iron Coral, 20 clicked in the water south of Menethil, for the Gauntlets. Mathiel (Darnassus): Sunscorched Shells, 20 under the Highperch wyvern nests in Thousand Needles, for the Leggings (verify breadcrumb).", cls="WARRIOR", x=73, y=75},
      {lv=28},
      {tr=true, x=11, y=52, map=WET, t="Fly to Menethil. Rebind."},
      {bind="Menethil", x=11, y=52, map=WET},
      {q="Reclaiming Goods", g={11,52,"Karl Boran, Menethil",WET}, o={14,38,"Bluegill murlocs (verify)",WET}},
      {q="Apprentice's Duties", g={11,52,"James Halloran, Menethil",WET}, o={20,50,"Crocolisks (verify)",WET}},
      {q="Fall of Dun Modr", g={11,52,"Harlo Barnaby, Menethil",WET}, r={33,38,"Captain Stoutfist, Whelgar's Excavation Site",WET}},
      {q="War Banners", g={33,38,"Captain Stoutfist",WET}, o={43,43,"Dragonmaw banners at Angerfang Encampment (verify)",WET}},
      {q="The Third Fleet", g={11,52,"First Mate Fitzsimmons",WET}, o={21,64,"The wrecked ship on the south coast",WET}},
      {q="Uncovering the Past", g={33,38,"Prospector Whelgar",WET}, o={33,38,"Follow the quest text (verify)",WET}},
      {q="A Grim Task", opt=true, g={49,18,"Longbraid the Grim, Dun Modr",WET}, o={61,28,"Balgaras the Foul at the Dark Iron camps; group",WET}},
      {q="The Thandol Span", p=1, g={49,18,"Rhag Garmason, Dun Modr",WET}, o={50,12,"Follow the quest text on the span (verify)",WET}},
      {man="Ashenvale and Stonetalon second pass if the Eastern Kingdoms run dry: Raene's Cleansing at Shael'dryn's moonwell (53,46), Pridewings at Mirkfallon Lake, Ziz Fizziks at Windshear Crag (58,62), Gaxim Rustfizzle at the Webwinder Path camp (59,66), Kaela's Enraged Spirits and Wounded Ancients. Stonetalon Peak (43,16) flight point. Forest Song is not in Era.", x=43, y=16, map=STM},
      {lv=29},
      {tr=true, x=50, y=58, map=HIL, t="Ride north over the Thandol Span into Arathi and west into Hillsbrad, or boat to Menethil and fly once you have Southshore. Southshore: bind, flight point."},
      {bind="Southshore", x=50, y=58, map=HIL},
      {fp="Southshore", x=50, y=58, map=HIL},
      {q="Down the Coast", g={50,58,"Lieutenant Farren Orinelle, Southshore",HIL}, o={60,60,"Naga on the east shore (verify)",HIL}},
      {q="Soothing Turtle Bisque", g={50,58,"Southshore chef (verify giver)",HIL}, o={80,77,"10 Turtle Meat from the Shimmering Flats turtles next bracket",TN}},
      {q="MacKreel's Moonshine", g={50,12,"Foggy MacKreel, Thandol Span",WET}, r={50,58,"Southshore",HIL}},
      {lv=30},
      {q="The Islander", cls="WARRIOR", g={76,53,"Any warrior trainer (Harry Burlguard, Stormwind; Hall of Arms, Ironforge)",SW}, r=KLANNOC},
      {q="The Affray", cls="WARRIOR", g=KLANNOC, o={68,48,"Step on the grate, kill the challenger waves, then Big Will (33)",BAR}, r={68,48,"Klannoc Macleod: Berserker Stance, Intercept",BAR}},
      {q="The Windwatcher", cls="WARRIOR", g=KLANNOC, r=BATHRAH},
      {forever=true, t="Dalaran opens in Alterac with a 28-33 dungeon and its own quests; it sits on the end of this bracket and replaces the Stonetalon second pass if it is dense."},
    },
  },
  -- ============================================================ 30-35 Thousand Needles / Stranglethorn / Hillsbrad / Desolace
  {
    id="a6", lv={30,35}, name="Thousand Needles, Stranglethorn, Hillsbrad, with a Desolace swing", map=STV,
    hub="Mirage Raceway, Booty Bay, Nesingwary's, Rebel Camp, Southshore, Nijel's Point", hearth="Booty Bay (Skindle) 32-34, Southshore at 34-35, Nijel's Point (Lyshaerya) in Desolace", fp="Thalanaar, Gadgetzan, Booty Bay, Nijel's Point",
    steps={
      {tr=true, x=80, y=77, map=TN, t="Fly Southshore to Menethil, boat to Theramore, fly Theramore to Thalanaar, ride into Thousand Needles. Shimmering Flats first."},
      {q="Seeking Strahad", cls="WARLOCK", g={27,77,"Any warlock trainer (Gakin, Stormwind; Forlorn Cavern, Ironforge)",SW}, r=STRAHAD},
      {q="Tome of the Cabal", p=1, cls="WARLOCK", g=STRAHAD, o={44,37,"Tattered Manuscript from the cave north-west of Freewind Post, Thousand Needles",TN}, r=STRAHAD},
      {q="Tome of the Cabal", p=2, cls="WARLOCK", g=STRAHAD, o={43,43,"3 Rods of Channeling from Dragonmaw Bonewarders at Angerfang Encampment, Wetlands",WET}, r=STRAHAD},
      {q="Tome of the Cabal", p=3, cls="WARLOCK", g=STRAHAD, r=STRAHAD},
      {q="The Binding", p=3, cls="WARLOCK", g=STRAHAD, o={62,35,"Summon and defeat a Felhunter at Strahad's circle",BAR}, r={62,35,"Strahad Farsan: Summon Felhunter",BAR}},
      {q="Journey to the Marsh", cls="MAGE", g=SW_JENNEA, r=TABETHA},
      {q="Hidden Secrets", cls="MAGE", g=TABETHA, r={77,76,"Magus Tirth, Mirage Raceway, Thousand Needles",TN}},
      {q="Get the Scoop", cls="MAGE", g={77,76,"Magus Tirth",TN}, o={77,76,"/beckon Plucky Johnson, the chicken",TN}, r={77,76,"Magus Tirth",TN}},
      {q="Rituals of Power", cls="MAGE", g={77,76,"Magus Tirth",TN}, o={85,35,"The book on the Athenaeum shelf, Scarlet Monastery Library",1420}, r=TABETHA},
      {q="Lonebrow's Journal", g={31,24,"Henrig Lonebrow's Journal at the Great Lift",TN}, r={89,45,"Falfindel Waywarder, Thalanaar",FER}},
      {q="Hardened Shells", g={80,77,"Wizzle Brassbolts, Mirage Raceway",TN}, o={80,70,"Turtles on the flats",TN}},
      {q="Salt Flat Venom", g={80,77,"Fizzle Brassbolts",TN}, o={78,72,"Scorpids on the flats",TN}},
      {q="Load Lightening", g={80,77,"Pozzik",TN}, o={82,74,"Basilisks on the flats",TN}},
      {q="Rocket Car Parts", g={80,77,"Kravel Koalbeard",TN}, o={78,78,"Parts scattered on the flats",TN}},
      {q="A Bump in the Road", g={80,77,"Zamek",TN}, o={79,75,"Follow the quest text (verify)",TN}},
      {q="Martek the Exiled", g={80,77,"Fizzle Brassbolts",TN}, r={42,52,"Martek the Exiled, Valley of Fangs, Badlands (hold until 40)",BAD}},
      {fp="Gadgetzan", x=51, y=28, map=TAN},
      {lv=32},
      {tr=true, x=27, y=77, map=STV, t="Fly Gadgetzan to Ratchet is Horde; ride to Ratchet and take the Maiden's Fancy to Booty Bay, or fly Theramore, boat Menethil, fly Booty Bay. Rebind."},
      {bind="Booty Bay", x=27, y=77, map=STV},
      {fp="Booty Bay", x=27, y=77, map=STV},
      {q="Welcome to the Jungle", g={35,10,"Barnil Stonepot, Nesingwary's Expedition"}, r={35,10,"Hemet Nesingwary Jr."}},
      {q="Tiger Mastery", p=1, g={35,10,"Ajeck Rouack"}, o={36,15,"10 Young Stranglethorn Tigers"}},
      {q="Panther Mastery", p=1, g={35,10,"Sir S. J. Erlgadin"}, o={40,15,"10 Young Panthers"}},
      {q="Raptor Mastery", p=1, g={35,10,"Hemet Nesingwary Jr."}, o={42,20,"10 Stranglethorn Raptors"}},
      {q="Tiger Mastery", p=2, g={35,10,"Ajeck Rouack"}, o={36,22,"10 Stranglethorn Tigers"}},
      {q="Panther Mastery", p=2, g={35,10,"Sir S. J. Erlgadin"}, o={38,22,"10 Shadow Panthers"}},
      {q="Raptor Mastery", p=2, g={35,10,"Hemet Nesingwary Jr."}, o={45,30,"10 Lashtail Raptors"}},
      {q="The Second Rebellion", g={37,3,"Sergeant Yohwa, Rebel Camp (verify)"}, o={44,11,"Kurzen's Compound"}},
      {q="Bad Medicine", g={37,3,"Sergeant Yohwa"}, o={44,11,"Kurzen's Compound"}},
      {q="Jungle Secrets", g={37,3,"Private Thorsen, Rebel Camp"}, o={44,11,"Kurzen's Compound"}},
      {q="Bookie Herod", g={37,3,"Lieutenant Doren, Rebel Camp"}, o={44,11,"Bookie Herod in Kurzen's Compound"}},
      {q="Supply and Demand", g={27,77,"Drizzlik, Booty Bay"}, o={33,45,"8 Crocolisk hides on the river"}},
      {q="Bloodscalp Ears", g={27,77,"Kebok, Booty Bay"}, o={28,12,"Bloodscalp trolls, north Stranglethorn"}},
      {q="Singing Blue Shards", g={27,77,"Crank Fizzlebub, Booty Bay"}, o={30,60,"Crystal Spine Basilisks on the coast"}},
      {q="The Stone of the Tides", g={27,77,"Baron Revilgaz, inn balcony"}, o={21,22,"The island off the north-west coast"}},
      {q="Cyclonian", p=1, cls="WARRIOR", g=BATHRAH, o={28,12,"30 Bloodscalp Tusks from the trolls in north Stranglethorn; 8 Liferoot from the auction house. The Essence of the Exile comes from Arathi next bracket"}},
      {lv=34},
      {tr=true, x=50, y=58, map=HIL, t="Fly to Southshore. Rebind."},
      {bind="Southshore", x=50, y=58, map=HIL},
      {q="Farren's Proof", p=1, g={50,58,"Lieutenant Farren Orinelle",HIL}, o={60,60,"Naga on the east shore",HIL}},
      {q="Farren's Proof", p=2, g={50,58,"Lieutenant Farren Orinelle",HIL}, o={60,60,"Naga on the east shore",HIL}},
      {q="Farren's Proof", p=3, g={50,58,"Lieutenant Farren Orinelle",HIL}, o={60,60,"Naga on the east shore",HIL}},
      {q="Stormwind Ho!", g={50,58,"Lieutenant Farren Orinelle",HIL}, r={80,37,"Major Samuelson, Stormwind Keep",SW}},
      {q="Hints of a New Plague?", p=1, g={50,58,"Phin Odelic, Southshore",HIL}, r={60,53,"Quae, Go'Shek Farm, Arathi",ARA}},
      {q="Syndicate Assassins", g={50,58,"Magistrate Henry Maleb, Southshore",HIL}, o={58,67,"Syndicate at Sofera's Naze, Alterac (verify)",ALT}},
      {q="Costly Menace", g={50,58,"Darren Malvew, Southshore",HIL}, o={40,60,"Gray Bears and Grizzled Bears (verify)",HIL}},
      {q="Bartolo's Yeti Fur Cloak", g={50,58,"Bartolo Ginsetti, Southshore",HIL}, o={54,45,"Yetis in the hills (verify)",HIL}},
      {q="Crushridge Bounty", g={50,58,"Marshal Redpath, Southshore",HIL}, o={40,50,"Crushridge ogres, Alterac",ALT}},
      {tr=true, x=63, y=10, map=DES, t="Desolace, any time the jungle thins: boat Menethil to Auberdine, fly to Nijel's Point. Rebind."},
      {bind="Nijel", x=63, y=10, map=DES},
      {fp="Nijel's Point", x=63, y=10, map=DES},
      {q="Centaur Bounty", g={63,10,"Corporal Melkins, Nijel's Point",DES}, o={55,20,"Kolkar and Magram centaur",DES}},
      {q="Vahlarriel's Search", p=1, g={63,10,"Vahlarriel Demonslayer, Nijel's Point",DES}, o={56,30,"Thunder Axe Fortress",DES}},
      {q="Reagents for Reclaimers Inc.", p=1, g={63,10,"Kreldig Ungor, Nijel's Point",DES}, o={30,9,"Slitherblade naga at Ranazjar Isle",DES}},
      {q="The Karnitol Shipwreck", p=1, g={63,10,"Kreldig Ungor",DES}, o={30,9,"Ranazjar Isle",DES}},
      {q="Brother Anton", g={63,10,"Nijel's Point",DES}, r={63,10,"Brother Anton, Nijel's Point",DES}},
      {q="Down the Scarlet Path", p=1, g={63,10,"Brother Anton",DES}, o={50,58,"Raleigh the Devout, Southshore inn",HIL}},
      {q="The Sceptre of Light", g={38,27,"Azore Aldamort, north road",DES}, o={55,32,"Thunder Axe Fortress: Burning Blade cultists",DES}},
      {q="Search for Tyranis", g={38,27,"Azore Aldamort",DES}, o={55,32,"Thunder Axe Fortress",DES}},
      {q="Bone Collector", g={62,39,"Bibbly F'utzbuckle",DES}, o={48,55,"Kodo Graveyard",DES}},
      {q="Kodo Roundup", g={60,61,"Smeed Scrabblescrew",DES}, o={58,58,"Rope six aged kodos back to Smeed",DES}},
      {forever=true, t="Shen'Dralas opens off the Valley of Bones in southern Desolace with no level range yet; if it is 30-35 it replaces the Desolace swing."},
      {lv=35},
    },
  },
  -- ============================================================ 35-40 Arathi / STV II / Dustwallow
  {
    id="a7", lv={35,40}, name="Arathi, Stranglethorn tier two, Dustwallow", map=ARA,
    hub="Refuge Pointe, Booty Bay, Theramore", hearth="Southshore for Arathi (Refuge Pointe has no inn in Era), Booty Bay at 37, Theramore (Janene) at 38", fp="Refuge Pointe, Theramore",
    steps={
      {tr=true, x=46, y=47, t="Fly Southshore, ride north over the Thandol Span into Arathi; or fly Menethil to Refuge Pointe once you have it."},
      {fp="Refuge Pointe", x=46, y=47},
      {q="Northfold Manor", g={46,47,"Captain Nials, Refuge Pointe"}, o={35,35,"Syndicate at Northfold Manor (verify)"}},
      {q="Stromgarde Badges", g={46,47,"Captain Nials"}, o={30,58,"15 badges from the Syndicate inside Stromgarde Keep; elite in places"}},
      {q="Malin's Request", p=1, g={39,82,"Archmage Malin, Wizard's Sanctum, Stormwind",SW}, r={46,47,"Apprentice Kryten, Refuge Pointe"}},
      {q="Worth Its Weight in Gold", g={46,47,"Apprentice Kryten"}, o={50,50,"Follow the quest text (verify)"}},
      {q="Wand over Fist", g={46,47,"Skuerto, Refuge Pointe"}, o={50,50,"Follow the quest text (verify)"}},
      {q="Trelane's Defenses", g={46,47,"Skuerto"}, o={30,58,"Stromgarde Keep, the Tower of Arathor; elite"}},
      {q="An Apprentice's Enchantment", g={46,47,"Skuerto"}, o={46,47,"Follow the quest text (verify)"}},
      {q="Attack on the Tower", g={46,47,"Skuerto"}, o={30,58,"Tower of Arathor; elite"}},
      {q="Hints of a New Plague?", p=2, g={60,53,"Quae, Go'Shek Farm"}, o={60,53,"Escort; then the Forsaken Courier ambush toward the Hillsbrad wall (verify)"}},
      {man="Witherbark Village (63,65) for tusks and pouches; Boulderfist ogres at Boulderfist Hall (73,68). Trol'kalar and the Sigils are Horde-only.", x=63, y=65},
      {q="Cyclonian", p=2, cls="WARRIOR", g=BATHRAH, o={51,49,"8 Burning Charms (Circle of West Binding 26,30), 8 Thundering Charms (Outer 51,49), 8 Cresting Charms (East 67,31) (verify which circle drops which); combine at Bath'rah's cauldron for the Essence of the Exile"}, r=BATHRAH},
      {q="The Summoning", cls="WARRIOR", g=BATHRAH, o={80,67,"Summon Cyclonian (40 elite, stuns) at the altar by the hut; bring a partner",ALT}, r=BATHRAH},
      {q="Whirlwind Weapon", cls="WARRIOR", g=BATHRAH, r={80,67,"Bath'rah: Whirlwind Axe, Sword or Warhammer",ALT}},
      {q="Items of Power", cls="MAGE", g=TABETHA, o={65,65,"1 Jade (auction house); 10 Witherbark Totem Sticks from the Witherbark trolls, used at the Circle of Outer Binding (51,48) in a thunderstorm for the Bolt Charged Bramble"}, r=TABETHA},
      {lv=37},
      {tr=true, x=27, y=77, map=STV, t="Fly Refuge Pointe to Menethil (Dark Iron War and A Grim Task at Dun Modr if you carry them), then to Booty Bay. Rebind."},
      {bind="Booty Bay", x=27, y=77, map=STV},
      {q="The Hidden Key", g={37,3,"Lieutenant Doren, Rebel Camp",STV}, o={44,11,"Kurzen's Compound",STV}},
      {q="Special Forces", g={37,3,"Lieutenant Doren",STV}, o={46,20,"Kurzen's cave",STV}},
      {q="Colonel Kurzen", g={37,3,"Lieutenant Doren",STV}, o={46,20,"Colonel Kurzen in his cave; group",STV}},
      {q="Kurzen's Mystery", g={37,3,"Brother Nimetz, Rebel Camp",STV}, o={44,11,"Kurzen's Compound",STV}},
      {q="Troll Witchery", g={37,3,"Brother Nimetz",STV}, o={49,28,"Mosh'Ogg Ogre Mound",STV}},
      {q="Panther Mastery", p=3, g={35,10,"Sir S. J. Erlgadin",STV}, o={38,30,"10 Elder Shadow Panthers",STV}},
      {q="Tiger Mastery", p=3, g={35,10,"Ajeck Rouack",STV}, o={35,30,"10 Elder Stranglethorn Tigers",STV}},
      {q="Raptor Mastery", p=3, g={35,10,"Hemet Nesingwary Jr.",STV}, o={50,35,"10 Jungle Stalkers",STV}},
      {q="The Mithril Order", g={27,77,"McGavan, Booty Bay",STV}, o={27,77,"Follow the quest text (verify)",STV}},
      {q="Venture Company Mining", g={27,77,"Booty Bay (verify giver)",STV}, o={42,18,"Venture Co. base at Lake Nazferiti",STV}},
      {lv=38},
      {tr=true, x=56, y=50, map=DUS, t="Fly to Menethil, the Lady Mehley to Theramore. Rebind, flight point."},
      {bind="Theramore", x=56, y=50, map=DUS},
      {fp="Theramore", x=56, y=50, map=DUS},
      {q="The Missing Diplomat", p=2, g={11,52,"Mikhail, Menethil inn",WET}, r={56,50,"Commander Samaul, Theramore",DUS}},
      {q="The Missing Diplomat", p=3, g={56,50,"Commander Samaul",DUS}, r={56,50,"Archmage Tervosh, Foothold Citadel",DUS}},
      {q="The Missing Diplomat", p=4, g={56,50,"Archmage Tervosh",DUS}, r={60,40,"Private Hendel, Sentry Point",DUS}},
      {q="The Missing Diplomat", p=5, g={60,40,"Private Hendel",DUS}, r={56,50,"Lady Jaina Proudmoore, Theramore",DUS}},
      {q="James Hyal", g={11,52,"Vincent Hyal, Menethil",WET}, r={56,50,"Clerk Lendry, Theramore",DUS}},
      {q="They Call Him Smiling Jim", g={56,50,"Guard Byron, Theramore",DUS}, o={56,50,"Follow the quest text (verify)",DUS}},
      {q="Mudrock Soup and Bugs", g={56,50,"Morgan Stern, Theramore inn",DUS}, o={50,45,"Mudrock turtles and Darkfang spiders (verify)",DUS}},
      {q="Stinky's Escape", g={59,40,"Stinky Ignatz, North Point Tower",DUS}, o={56,50,"Escort him to Theramore; keep the Elixir of Fortitude",DUS}, r={56,50,"Theramore",DUS}},
      {note="Not in Era", t="Nat Pagle, Alcaz Island and Mudsprocket are TBC. Skip any guide step that uses them; fill with Desolace or the Badlands."},
      {lv=40},
      {q="The Tome of Nobility", cls="PALADIN", g={38,27,"Any paladin trainer",SW}, r={38,27,"Duthorian Rall: Summon Warhorse (train Apprentice Riding first)",SW}},
      {q="Summon Felsteed", p=1, cls="WARLOCK", g={27,77,"Any warlock trainer",SW}, r=STRAHAD},
      {q="Summon Felsteed", p=2, cls="WARLOCK", g=STRAHAD, o={62,35,"Strahad and his acolytes run the ritual",BAR}, r={62,35,"Strahad Farsan: Summon Felsteed",BAR}},
      {q="Mage's Wand", cls="MAGE", g=TABETHA, r={43,57,"Tabetha: Icefury, Ragefire or Nether Force Wand",DUS}},
      {forever=true, t="Riverdale, a new 35-45 zone east of Burning Steppes and the Badlands, sits on top of this bracket. If it is dense it replaces the Dustwallow leg."},
    },
  },
  -- ============================================================ 40-45 Badlands / Swamp / STV III
  {
    id="a8", lv={40,45}, name="Badlands, Swamp of Sorrows, Stranglethorn tier three", map=BAD,
    hub="Thelsamar and Ironforge for the Badlands, the Harborage, Nethergarde Keep, Booty Bay", hearth="Ironforge for the Badlands leg (no Alliance town there), Booty Bay for Stranglethorn", fp="Nethergarde Keep",
    steps={
      {tr=true, x=25, y=44, t="Boat Theramore to Menethil, fly to Thelsamar (Ironforge for the bind), ride east into the Badlands."},
      {bind="Ironforge", x=18, y=51, map=IF},
      {q="Ironband Wants You!", g={75,10,"Prospector Stormpike, Hall of Explorers, Ironforge",IF}, r={65,65,"Prospector Ironband, Ironband's Excavation, Loch Modan",LM}},
      {q="Find Agmond", g={65,65,"Prospector Ironband, Loch Modan",LM}, o={50,62,"Agmond's End"}},
      {q="Agmond's Fate", g={50,62,"Agmond's corpse (verify)"}, o={50,62,"Murdaloc at Agmond's End"}},
      {q="Badlands Reagent Run", g={35,49,"Ghak Healtouch, Thelsamar",LM}, o={40,50,"Buzzards, coyotes and rock elementals (verify)"}},
      {q="A Dwarf and His Tools", g={53,43,"Prospector Ryedol, Hammertoe's Digsite"}, o={53,43,"Follow the quest text (verify)"}},
      {q="A Sign of Hope", g={53,43,"Prospector Ryedol"}, r={53,43,"Hammertoe Grez (verify)"}},
      {q="Indurium", g={42,52,"Martek the Exiled, Valley of Fangs"}, o={45,55,"Indurium from the Uldaman entrance area (verify)"}},
      {q="Study of the Elements: Rock", p=1, g={25,44,"Lotwil Veriatus"}, o={17,83,"Rock elementals in the south-west"}},
      {q="Barbecued Buzzard Wings", g={25,44,"Rigglefuzz"}, o={30,40,"Buzzards"}},
      {q="Power Stones", g={25,44,"Rigglefuzz"}, o={45,55,"Uldaman: Dentrium and An'Alleum Power Stones"}},
      {q="Solution to Doom", g={50,62,"Theldurin the Lost, Agmond's End"}, o={45,55,"Uldaman: the Tablet of Ryun'eh (verify)"}},
      {q="Stone is Better than Cloth", g={25,44,"Lucien Tosselwrench (verify)"}, o={17,83,"Rock elementals"}},
      {q="Return to the Marsh", cls="MAGE", opt=true, g=TABETHA, r=TABETHA},
      {q="The Infernal Orb", cls="MAGE", opt=true, g=TABETHA, o={43,57,"Follow the quest text (verify)",DUS}, r=TABETHA},
      {q="The Exorcism", cls="MAGE", opt=true, g=TABETHA, o={43,57,"Group; follow the quest text",DUS}, r=TABETHA},
      {q="Power in Uldaman", cls="MAGE", opt=true, g=TABETHA, o={45,55,"The Obsidian Sentinel in Uldaman"}, r=TABETHA},
      {q="Mana Surges", cls="MAGE", opt=true, g=TABETHA, o={43,57,"Follow the quest text",DUS}, r=TABETHA},
      {q="Celestial Power", cls="MAGE", opt=true, g=TABETHA, r={43,57,"Tabetha: Celestial Orb or Celestial Stave",DUS}},
      {lv=42},
      {tr=true, x=69, y=40, map=SW, any=true, t="Capital errands: Brohann Caskbelly (Dwarven District, Stormwind) In Search of The Temple; Mazen Mac'Nadir (Cathedral) Mazen's Behest; Watchmaster Sorigal (Darkshire) Supplies for Nethergarde. Ironforge players: Tram over."},
      {q="In Search of The Temple", g={69,40,"Brohann Caskbelly, Dwarven District, Stormwind",SW}, r={14,44,"Falstad Wildhammer, Aerie Peak, Hinterlands (verify)",HIN}},
      {q="Mazen's Behest", p=1, g={40,63,"Mazen Mac'Nadir, Cathedral of Light, Stormwind",SW}, o={13,35,"Essays from Swampwalkers and Tangled Horrors, Misty Valley, Swamp of Sorrows",SOS}},
      {q="Supplies for Nethergarde", g={74,45,"Watchmaster Sorigal, Darkshire",DW}, r={61,14,"Quartermaster Lungertz, Nethergarde Keep (verify)",BL}},
      {tr=true, x=27, y=77, map=STV, t="Fly to Booty Bay. Rebind."},
      {bind="Booty Bay", x=27, y=77, map=STV},
      {q="The Bloodsail Buccaneers", p=1, g={27,77,"First Mate Crazz, Booty Bay",STV}, o={29,80,"Bloodsail camps south of Booty Bay; ships at 34,88",STV}},
      {q="Skullsplitter Tusks", g={27,77,"Kebok, Booty Bay",STV}, o={45,33,"Skullsplitter trolls at Ziata'Jai, Balia'mah, Zul'Mamwe",STV}},
      {q="Akiris by the Bundle", g={27,77,"Privateer Bloads, Booty Bay",STV}, o={24,65,"Naga on the west coast",STV}},
      {q="Zanzil's Secret", g={27,77,"Crank Fizzlebub, Booty Bay",STV}, o={40,57,"Ruins of Aboraz and Jubuwal (33,51): Jon-Jon the Crow, Chucky Ten Thumbs, Maury Club-Foot",STV}},
      {q="Stranglethorn Fever", g={27,77,"Fin Fizracket, Booty Bay",STV}, o={31,67,"Elder Mistvale Gorillas; Witch Doctor Unbagwa's cave at 35,61",STV}},
      {q="Big Game Hunter", opt=true, g={35,10,"Hemet Nesingwary Jr.",STV}, o={38,34,"King Bangalash; bring a partner",STV}},
      {q="Raptor Mastery", p=4, g={35,10,"Hemet Nesingwary Jr.",STV}, o={29,43,"Tethis",STV}},
      {q="Voodoo Dues", g={27,77,"Sea Wolf MacKinley, Booty Bay",STV}, o={33,51,"Follow the quest text (verify)",STV}},
      {q="Tran'Rek", g={27,77,"Krazek, Booty Bay",STV}, r={51,28,"Tran'rek, Gadgetzan",TAN}},
      {lv=44},
      {tr=true, x=26, y=31, map=SOS, t="Ride from Darkshire through Deadwind Pass into the Swamp of Sorrows. The Harborage; no inn or flight point here."},
      {q="Help Watcher Biggs", g={26,31,"Anchorite Avuun, the Harborage",SOS}, r={44,60,"Watcher Biggs, south-east of Splinterspear Junction (verify)",SOS}},
      {q="Encroaching Wildlife", g={44,60,"Watcher Biggs",SOS}, o={40,55,"Swamp beasts around him (verify)",SOS}},
      {q="The Lost Caravan", g={44,60,"Watcher Biggs",SOS}, o={40,60,"Follow the quest text (verify)",SOS}},
      {q="Driftwood", g={44,60,"Watcher Biggs",SOS}, o={50,70,"Driftwood on the south coast (verify)",SOS}},
      {q="Deliver the Shipment", g={44,60,"Watcher Biggs",SOS}, r={61,14,"Nethergarde Keep, Blasted Lands (verify)",BL}},
      {q="Pool of Tears", g={65,45,"Pool of Tears (Atal'ai artifacts underwater; breadcrumb into Sunken Temple; verify giver)",SOS}, o={65,45,"Atal'ai Artifacts underwater; surface between dives",SOS}},
      {q="Noboru the Cudgel", g={26,31,"The Harborage (verify giver)",SOS}, o={50,35,"Noboru the Cudgel (verify)",SOS}},
      {fp="Nethergarde", x=61, y=14, map=BL},
      {q="Nekrum's Medallion", g={61,14,"Thadius Grimshade, top floor, Nethergarde Keep (verify)",BL}, o={39,20,"Zul'Farrak: Nekrum Gutchewer",TAN}},
      {lv=45},
    },
  },
  -- ============================================================ 45-50 Tanaris / Feralas / Hinterlands / Searing Gorge
  {
    id="a9", lv={45,50}, name="Tanaris, Feralas, Hinterlands, Searing Gorge", map=TAN,
    hub="Gadgetzan, Feathermoon Stronghold, Aerie Peak, Thorium Point", hearth="Gadgetzan (Fizzgrimble) 45-49, Feathermoon (Shyria) in Feralas, Aerie Peak (Thulfram) 47-49, your capital for Searing Gorge", fp="Gadgetzan, Feathermoon, Aerie Peak, Thorium Point",
    steps={
      {tr=true, x=51, y=28, t="Fly Booty Bay to Gadgetzan, or Nethergarde to Menethil, boat Theramore, fly Gadgetzan. Rebind."},
      {bind="Gadgetzan", x=51, y=28},
      {q="Thistleshrub Valley", g={51,28,"Tran'rek, Gadgetzan"}, o={28,67,"Thistleshrubs in the valley south-west"}},
      {q="Gadgetzan Water Survey", g={51,28,"Senior Surveyor Fizzledowser"}, o={31,51,"The Noxious Lair"}},
      {q="Noxious Lair Investigation", g={51,28,"Senior Surveyor Fizzledowser"}, o={55,70,"Scrimshank's Surveying Gear in the Gaping Chasm"}},
      {q="Handle with Care", g={51,28,"Curgle Cranklehop"}, r={51,28,"Follow the quest text (verify)"}},
      {q="The Dunemaul Compound", g={51,28,"Andi Lynn"}, o={40,56,"Gor'marok at the Dunemaul Compound"}},
      {q="Wastewander Justice", g={51,28,"Gadgetzan (verify giver)"}, o={63,37,"Wastewander bandits at Waterspring Field"}},
      {q="Water Pouch Bounty", g={51,28,"Spigot Operator Luglunket"}, o={63,37,"Wastewander Water Pouches"}},
      {q="Gahz'ridian", g={52,45,"Marvon Rivetseeker, Broken Pillar"}, o={48,64,"Ornaments at Eastmoon and Southmoon Ruins"}},
      {q="Screecher Spirits", g={66,22,"Yeh'kinya, Steamwheedle Port"}, o={70,45,"Screecher spirits at Lost Rigger Cove and the coast"}},
      {q="Stoley's Shipment", g={66,22,"Stoley, Steamwheedle Port"}, o={68,41,"Lost Rigger Cove"}},
      {q="Scarab Shells", opt=true, g={51,28,"Tran'rek"}, o={39,20,"Zul'Farrak"}},
      {q="Troll Temper", opt=true, g={51,28,"Trenton Lighthammer"}, o={39,20,"Zul'Farrak"}},
      {q="Divino-matic Rod", opt=true, g={51,28,"Chief Engineer Bilgewhizzle"}, o={39,20,"Zul'Farrak: Sergeant Bly"}},
      {q="The Prophecy of Mosh'aru", opt=true, g={66,22,"Yeh'kinya"}, o={39,20,"Zul'Farrak: the two tablets"}},
      {lv=47},
      {tr=true, x=31, y=43, map=FER, t="Fly to Feathermoon Stronghold (the island; ferry to the Forgotten Coast). Rebind."},
      {bind="Feathermoon", x=31, y=43, map=FER},
      {fp="Feathermoon", x=31, y=43, map=FER},
      {q="The Ruins of Solarsal", g={31,43,"Shandris Feathermoon",FER}, o={26,52,"Solarsal, south of the stronghold",FER}},
      {q="Against the Hatecrest", p=1, g={31,43,"Latronicus Moonspear",FER}, o={28,60,"Hatecrest naga on the coast",FER}},
      {q="Against the Hatecrest", p=2, g={31,43,"Latronicus Moonspear",FER}, o={28,60,"Hatecrest naga",FER}},
      {q="Against Lord Shalzaru", g={31,43,"Latronicus Moonspear",FER}, o={26,67,"Lord Shalzaru in the Isle of Dread cave",FER}},
      {q="The Missing Courier", p=1, g={31,43,"Shandris Feathermoon (verify)",FER}, o={45,65,"The row boat wreckage on the coast",FER}},
      {q="The Knife Revealed", g={31,43,"Quintis Jonespyre (verify)",FER}, r={31,43,"Feathermoon",FER}},
      {q="The Woodpaw Gnolls", g={31,43,"Ginro Hearthkindle",FER}, o={70,50,"Woodpaw gnolls in the hills",FER}},
      {q="The Writhing Deep", g={31,43,"Ginro Hearthkindle",FER}, o={74,63,"The Writhing Deep",FER}},
      {q="Freedom for All Creatures", g={65,45,"Kindal Moonweaver, Grimtotem compound",FER}, o={65,45,"Free the caged sprite darters",FER}},
      {q="In Search of Knowledge", g={31,43,"Troyas Moonbreeze",FER}, o={30,43,"Follow the quest text",FER}},
      {q="The Mark of Quality", g={31,43,"Pratt McGrubben",FER}, o={55,56,"Feral Scar yetis",FER}},
      {q="Improved Quality", g={31,43,"Pratt McGrubben",FER}, o={55,56,"Feral Scar yetis",FER}},
      {lv=48},
      {tr=true, x=14, y=44, map=HIN, t="Fly to your capital, then Aerie Peak (Ironforge direct; Stormwind via Ironforge). Rebind."},
      {bind="Aerie Peak", x=14, y=44, map=HIN},
      {fp="Aerie Peak", x=14, y=44, map=HIN},
      {q="To The Hinterlands", g={14,44,"Falstad Wildhammer, Aerie Peak",HIN}, r={14,44,"Gryphon Master Talonaxe",HIN}},
      {q="Rhapsody Shindigger", g={14,44,"Gryphon Master Talonaxe",HIN}, r={26,48,"Rhapsody Shindigger, Shindigger's Camp",HIN}},
      {q="Rhapsody's Kalimdor Kocktail", g={26,48,"Rhapsody Shindigger",HIN}, o={26,48,"Un'Goro Gorilla Pelt, Groddoc Liver, Silithid Egg from Kalimdor (verify list)",HIN}},
      {q="Rhapsody's Tale", g={26,48,"Rhapsody Shindigger",HIN}, r={14,44,"Gryphon Master Talonaxe",HIN}},
      {q="Into The Temple of Atal'Hakkar", g={14,44,"Gryphon Master Talonaxe",HIN}, o={70,54,"The Temple of Atal'Hakkar: the four relics (verify)",SOS}, r={14,44,"Aerie Peak",HIN}},
      {q="Featherbeard's Endorsement", g={14,44,"Aerie Peak (verify giver)",HIN}, r={13,54,"Featherbeard's hovel",HIN}},
      {q="In Pursuit of Featherbeard", g={13,54,"Featherbeard's Journal",HIN}, o={36,64,"Shadra'Alor",HIN}},
      {q="Reclaiming the Eggs", g={14,44,"Aerie Peak",HIN}, o={36,73,"Gryphon eggs at Shadra'Alor",HIN}},
      {q="Gammerita, Mon!", opt=true, g={79,79,"Revantusk (Horde); skip",HIN}, o={82,47,"Gammerita on the coast",HIN}},
      {man="Altar of Zul (49,64): Qiaga the Keeper and Morta'gya drop the Sacred Mallet for Gahz'rilla. Cortello's chest at the waterfall (79,48). Witherbark cages at Zun'watha (23,58) and Hiri'watha (32,57). OOX-09/HL escort (49,37).", x=49, y=64, map=HIN},
      {lv=49},
      {tr=true, x=36, y=27, map=SG, t="Fly to Thorium Point (no inn; hearth your capital)."},
      {fp="Thorium Point", x=36, y=27, map=SG},
      {q="Divine Retribution", g={38,39,"Kalaran Windblade",SG}, o={41,54,"Overseer Maltorius in the Slag Pit",SG}},
      {q="The Flawless Flame", g={38,39,"Kalaran Windblade",SG}, o={40,50,"Follow the quest text (verify)",SG}},
      {q="Forging the Shaft", g={38,39,"Kalaran Windblade",SG}, o={40,50,"Follow the quest text (verify)",SG}},
      {q="The Flame's Casing", g={38,39,"Kalaran Windblade",SG}, o={40,50,"Follow the quest text (verify)",SG}},
      {q="The Torch of Retribution", g={38,39,"Kalaran Windblade",SG}, r={38,39,"Kalaran Windblade",SG}},
      {q="Suntara Stones", p=1, g={40,48,"Dorius Stonetender, Grimesilt Dig Site (verify)",SG}, o={40,48,"Follow the quest text",SG}},
      {q="What the Flux?", g={36,27,"Master Smith Burninate, Thorium Point",SG}, o={40,50,"Dark Iron Slag from Dark Iron dwarves (verify)",SG}},
      {q="Incendosaurs? Whateverosaur is More Like It", g={36,27,"Hansel Heavyhands, Thorium Point",SG}, o={45,50,"Incendosaurs in the Cauldron",SG}},
      {q="Prayer to Elune", p=1, g={35,30,"Zamael Lunthistle, Firewatch Ridge (verify)",SG}, o={35,30,"Follow the quest text",SG}},
      {forever=true, t="Nothing announced touches Tanaris, Feralas or the Hinterlands."},
      {lv=50},
    },
  },
  -- ============================================================ 50-55 Un'Goro / Felwood / Burning Steppes / Azshara
  {
    id="a10", lv={50,55}, name="Un'Goro, Felwood, Burning Steppes, Azshara", map=UNG,
    hub="Marshal's Refuge, Talonbranch Glade, Morgan's Vigil, Talrendis Point", hearth="Gadgetzan while in Un'Goro (Marshal's Refuge has no inn), your capital for Felwood and the Steppes", fp="Marshal's Refuge, Talonbranch Glade, Morgan's Vigil, Talrendis Point",
    steps={
      {tr=true, x=45, y=8, t="Fly to Gadgetzan and ride down the slope (27,57 Tanaris) into Un'Goro. Marshal's Refuge."},
      {fp="Marshal's Refuge", x=45, y=8},
      {q="Williden's Journal", g={63,68,"Williden's Journal by Linken's raft"}, r={45,8,"Williden Marshal, Marshal's Refuge"}},
      {q="Expedition Salvation", g={45,8,"Williden Marshal"}, o={50,50,"Dirt piles across the crater (verify)"}},
      {q="Crystals of Power", g={46,13,"J.D. Collie, the cave"}, o={50,50,"7 Power Crystals, any colour"}},
      {q="Making Sense of It", g={46,13,"J.D. Collie"}, o={54,13,"The Northern Pylon"}},
      {q="Chasing A-Me 01", g={45,8,"Karna Remtravel"}, o={63,16,"Fungal Rock; U'cha"}},
      {q="Roll the Bones", g={45,8,"Spark Nilminer"}, o={50,60,"Bloodpetal and diemetradon (verify)"}},
      {q="Alien Ecology", g={45,8,"Hol'anyee Marshal"}, o={50,76,"Hive wall samples"}},
      {q="Beware of Pterrordax", g={45,8,"Spraggle Frock"}, o={50,20,"Pterrordax (verify)"}},
      {q="Lost!", g={45,8,"Spraggle Frock"}, o={51,45,"Ringo at Fire Plume Ridge"}},
      {q="A Little Help From My Friends", g={51,45,"Ringo"}, o={45,8,"Escort him to Marshal's Refuge"}, r={45,8,"Spraggle Frock"}},
      {q="The Fare of Lar'korwi", g={72,76,"Torwa Pathfinder, the Marshlands"}, o={67,73,"Egg piles"}},
      {q="The Scent of Lar'korwi", g={72,76,"Torwa Pathfinder"}, o={66,67,"Lar'korwi"}},
      {q="The Apes of Un'Goro", g={72,76,"Torwa Pathfinder"}, o={63,17,"Fungal Rock apes"}},
      {q="Haze of Evil", g={40,10,"Muigin, north-west (Alliance)"}, o={50,60,"Bloodpetals"}},
      {q="It's a Secret to Everybody", p=1, g={63,68,"Linken's pack in the tree trunk"}, r={45,8,"Marshal's Refuge (verify)"}},
      {lv=51},
      {tr=true, x=10, y=74, map=AZ, t="Azshara: ride from Ashenvale or Felwood; Talrendis Point has the flight point."},
      {fp="Talrendis Point", x=10, y=74, map=AZ},
      {q="A Land Filled with Hatred", g={10,74,"Loh'atu, Talrendis Point",AZ}, o={13,74,"Satyrs at the Shadowsong Shrine and Haldarr Encampment",AZ}},
      {q="Spiritual Unrest", g={10,74,"Loh'atu",AZ}, o={13,74,"Highborne spirits (verify)",AZ}},
      {q="Kim'jael Indeed!", g={53,21,"Kim'jael, Legash Encampment",AZ}, o={55,26,"Thalassian Base Camp",AZ}},
      {q="Passing the Burden", g={75,10,"Historian Karnik, Hall of Explorers, Ironforge",IF}, r={75,10,"Tymor (verify)",IF}},
      {lv=52},
      {tr=true, x=62, y=24, map=FEL, t="Fly to Talonbranch Glade (no inn in Era). Emerald Sanctuary (51,80) has no flight point."},
      {fp="Talonbranch", x=62, y=24, map=FEL},
      {q="Forces of Jaedenar", g={51,80,"Greta Mosshoof, Emerald Sanctuary",FEL}, o={40,57,"Jaedenar",FEL}},
      {q="Collection of the Corrupt Water", g={51,80,"Greta Mosshoof",FEL}, o={40,57,"Jaedenar",FEL}},
      {q="Seeking Spiritual Aid", g={51,80,"Greta Mosshoof",FEL}, r={66,44,"Islen Waterseer, Barrens coast south of Ratchet",BAR}},
      {q="Cleansed Water Returns to Felwood", g={66,44,"Islen Waterseer",BAR}, r={51,80,"Greta Mosshoof",FEL}},
      {q="The Corruption of the Jadefire", g={51,80,"Eridan Bluewind",FEL}, o={39,22,"Jadefire Run",FEL}},
      {q="Further Corruption", g={51,80,"Eridan Bluewind",FEL}, o={39,22,"Jadefire Run",FEL}},
      {q="A Strange Red Key", g={51,80,"Jessir Moonbow (verify)",FEL}, o={40,57,"Jaedenar: the key",FEL}},
      {q="Rescue From Jaedenar", g={40,57,"Captured Arko'narin, Shadow Hold",FEL}, o={51,80,"Escort her out",FEL}, r={51,80,"Jessir Moonbow",FEL}},
      {q="Timbermaw Ally", g={49,88,"Grazle, south of the sanctuary",FEL}, o={49,88,"Deadwood Village furbolgs",FEL}},
      {q="Speak to Nafien", g={49,88,"Grazle",FEL}, r={65,8,"Nafien, Timbermaw Hold tunnel",FEL}},
      {lv=53},
      {tr=true, x=73, y=66, map=BS, t="Fly to Morgan's Vigil (verify coords; no innkeeper in Era)."},
      {fp="Morgan's Vigil", x=73, y=66, map=BS},
      {q="Extinguish the Firegut", g={73,66,"Oralius, Morgan's Vigil",BS}, o={55,45,"Firegut ogres",BS}},
      {q="Gor'tesh the Brute Lord", g={73,66,"Oralius",BS}, o={55,45,"Gor'tesh",BS}},
      {q="Ogre Head On A Stick = Party", g={73,66,"Oralius",BS}, o={55,45,"Plant the head",BS}},
      {q="Dragonkin Menace", g={73,66,"Helendis Riverhorn, Morgan's Vigil",BS}, o={60,55,"Black dragonkin",BS}},
      {q="The True Masters", p=1, g={73,66,"Helendis Riverhorn",BS}, r={30,44,"Magistrate Solomon, Lakeshire",RR}},
      {q="The True Masters", p=2, g={30,44,"Magistrate Solomon",RR}, r={80,37,"Highlord Bolvar Fordragon, Stormwind Keep",SW}},
      {q="The True Masters", p=3, g={80,37,"Highlord Bolvar Fordragon",SW}, r={73,66,"Marshal Maxwell, Morgan's Vigil",BS}},
      {q="Marshal Windsor", opt=true, g={73,66,"Marshal Maxwell",BS}, o={40,20,"Blackrock Depths: Marshal Windsor in the Detention Block; the Onyxia attunement",SG}},
      {q="Broodling Essence", g={65,24,"Tinkee Steamboil, Flame Crest",BS}, o={50,30,"Draco-Incarcinatrix on Broodlings at the Pillar of Ash",BS}},
      {man="Maraudon and Sunken Temple are the dungeons for this stretch. Sunken Temple carries every level-50 class chain below plus Rhapsody's relics; run it once and clear them all.", x=70, y=54, map=SOS},
      {q="A Troubled Spirit", cls="WARRIOR", g={76,53,"Any warrior trainer (Stormwind Old Town; Ironforge Hall of Arms)",SW}, r={34,66,"Fallen Hero of the Horde, road at the Blasted Lands border, Swamp of Sorrows",SOS}},
      {q="Warrior Kinship", cls="WARRIOR", g={34,66,"Fallen Hero of the Horde",SOS}, o={54,40,"7 Helboar near the Tainted Scar, Blasted Lands (verify)",BL}, r={34,66,"Fallen Hero of the Horde",SOS}},
      {q="War on the Shadowsworn", cls="WARRIOR", g={34,66,"Fallen Hero of the Horde",SOS}, o={65,32,"Shadowsworn cultists around the Altar of Storms (counts verify)",BL}, r={34,66,"Fallen Hero of the Horde",SOS}},
      {q="Voodoo Feathers", cls="WARRIOR", g={34,66,"Fallen Hero of the Horde",SOS}, o={70,54,"Temple of Atal'Hakkar: Gasher, Zul'lor, Hukku, Mijan, Loro, Zolo for 2 Amber, 2 Blue, 2 Green Voodoo Feathers",SOS}, r={34,66,"Fallen Hero: Diamond Flask, Fury Visor or Razorsteel Shoulders",SOS}},
      {q="Chillwind Camp", cls="PALADIN", g={38,27,"Lord Grayson Shadowbreaker, Cathedral of Light, Stormwind (any paladin trainer)",SW}, r=ASHLAM},
      {q="Dispelling Evil", cls="PALADIN", g=ASHLAM, o={45,80,"20 Minion's Scourgestones from any Western Plaguelands Scourge",WPL}, r={52,84,"High Priest Thel'danis, Uther's Tomb, Sorrow Hill (verify)",WPL}},
      {q="Inert Scourgestones", cls="PALADIN", g={52,84,"High Priest Thel'danis",WPL}, r=ASHLAM},
      {q="Forging the Mightstone", cls="PALADIN", g=ASHLAM, o={70,54,"Temple of Atal'Hakkar: the six troll mini-bosses for 2 Amber, 2 Blue, 2 Green Voodoo Feathers",SOS}, r={43,84,"Ashlam: Holy Mightstone plus Lightforged Blade, Chivalrous Signet or Sanctified Orb",WPL}},
      {q="The Hunter's Charm", cls="HUNTER", g={62,36,"Any hunter trainer (Ulfir Ironbeard, Stormwind; Olmin Burningbeard, Ironforge; Dorion, Darnassus)",SW}, r=OGTINC},
      {q="Courser Antlers", cls="HUNTER", g=OGTINC, o={52,27,"2 Perfect Courser Antlers from Mosshoof Coursers, north and south Azshara (low drop)",AZ}, r=OGTINC},
      {q="Wavethrashing", cls="HUNTER", g=OGTINC, o={87,26,"6 Wavethrasher Scales from the hydras on the far north-east and south-east shores",AZ}, r=OGTINC},
      {q="The Green Drake", cls="HUNTER", g=OGTINC, o={70,54,"Kill Morphaz in the Temple of Atal'Hakkar; loot the Tooth",SOS}, r={42,43,"Ogtinc: Devilsaur Eye, Devilsaur Tooth or Hunting Spear",AZ}},
      {q="A Simple Request", cls="ROGUE", g=SW_SHAW, r=RAVEN},
      {q="Sealed Azure Bag", cls="ROGUE", g=RAVEN, o={45,21,"Pickpocket Timbermaw Shamans in Azshara for the bag; the elf at 28,50 teleports you up to Xylem",AZ}, r=XYLEM},
      {q="Encoded Fragments", cls="ROGUE", g=XYLEM, o={64,25,"10 Encoded Fragments from Forest Oozes",AZ}, r=XYLEM},
      {q="The Azure Key", cls="ROGUE", g=XYLEM, o={70,54,"Temple of Atal'Hakkar: the Azure Key from Morphaz",SOS}, r={76,43,"Lord Jorach Ravenholdt: Whisperwalk Boots, Duskbat Drape or Ebon Mask",HIL}},
      {q="Cenarion Aid", cls="PRIEST", g={38,27,"Any capital priest trainer",SW}, r=OGTINC},
      {q="Of Coursers We Know", cls="PRIEST", g=OGTINC, o={52,27,"4 Healthy Courser Glands from Mosshoof Coursers, away from the naga",AZ}, r=OGTINC},
      {q="The Ichor of Undeath", cls="PRIEST", g=OGTINC, o={45,80,"1 Ichor of Undeath, a rare drop from any undead at level (Plaguelands, Scholomance)",WPL}, r=OGTINC},
      {q="Blood of Morphaz", cls="PRIEST", g=OGTINC, o={70,54,"Temple of Atal'Hakkar: kill Morphaz, loot the Blood",SOS}, r={42,43,"Ogtinc: Blessed Prayer Beads, Woestave or Circle of Hope",AZ}},
      {q="Magecraft", cls="MAGE", g=SW_JENNEA, r=XYLEM},
      {q="Magic Dust", cls="MAGE", g=XYLEM, o={57,28,"Dust from the blood elves around the Thalassian Base Camp",AZ}, r=XYLEM},
      {q="The Siren's Coral", cls="MAGE", g=XYLEM, o={44,54,"Naga at the ruins on the Shattered Strand",AZ}, r=XYLEM},
      {q="Destroy Morphaz", cls="MAGE", g=XYLEM, o={70,54,"Temple of Atal'Hakkar: the Arcane Shard from Morphaz",SOS}, r={28,50,"Archmage Xylem: Fire Ruby, Arcane Crystal Pendant or Glacial Spike",AZ}},
      {q="An Imp's Request", cls="WARLOCK", g=SW_GAKIN, o={27,77,"1 Felcloth (auction house or Felwood satyrs)",SW}, r=IMPSY},
      {q="Hot and Itchy", cls="WARLOCK", g=IMPSY, o={40,40,"Follow the quest text (verify objective)",FEL}, r=IMPSY},
      {q="The Wrong Stuff", cls="WARLOCK", g=IMPSY, o={55,15,"10 Rotting Wood from Irontree Wanderers and Stompers; 4 Bloodvenom Essence from Tainted Oozes",FEL}, r=IMPSY},
      {q="Trolls of a Feather", cls="WARLOCK", g=IMPSY, o={70,54,"Temple of Atal'Hakkar: the six troll mini-bosses for 2 Amber, 2 Blue, 2 Green Voodoo Feathers",SOS}, r={40,40,"Impsy: Soul Harvester, Abyss Shard or Robe of Servitude",FEL}},
      {q="Torwa Pathfinder", cls="DRUID", g={38,22,"Mathrengyl Bearwalker, Cenarion Enclave, Darnassus (any druid trainer)",DAR}, r=TORWA},
      {q="Bloodpetal Poison", cls="DRUID", g=TORWA, o={50,80,"8 Bloodcap from Bloodpetal Sprouts, 8 Gorishi Stings from the Gorishi Hive wasps",UNG}, r=TORWA},
      {q="Toxic Test", cls="DRUID", g=TORWA, o={55,45,"Hibernate a Devilsaur, stab it with the Devilsaur Barb, Travel Form away",UNG}, r=TORWA},
      {q="A Better Ingredient", cls="DRUID", g=TORWA, o={70,54,"Putrid Vine from Atal'alarion in the Temple of Atal'Hakkar (light the six altars in order)",SOS}, r={72,76,"Torwa: Grizzled Pelt, Forest's Embrace or Moonshadow Stave",UNG}},
      {forever=true, t="Nothing announced touches Un'Goro, Felwood or Azshara. Riverdale borders the Burning Steppes."},
      {lv=55},
    },
  },
  -- ============================================================ 55-60 Plaguelands / Winterspring / Silithus
  {
    id="a11", lv={55,60}, name="Plaguelands, Winterspring, Silithus", map=WPL,
    hub="Chillwind Camp, Light's Hope Chapel, Everlook, Cenarion Hold", hearth="Your capital for the Plaguelands (Chillwind has no inn), then Everlook (Vizzie)", fp="Chillwind Camp, Light's Hope, Everlook, Cenarion Hold",
    steps={
      {tr=true, x=43, y=85, t="Fly Morgan's Vigil to your capital, then Chillwind Camp (Ironforge direct; Stormwind via Ironforge)."},
      {fp="Chillwind Camp", x=43, y=85},
      {q="Clear the Way", g={43,85,"Commander Ashlam Valorfist, Chillwind Camp"}, o={46,81,"Sorrow Hill skeletons"}},
      {q="All Along the Watchtowers", g={43,85,"Commander Ashlam Valorfist"}, o={45,68,"Plant the beacons on the four Andorhal towers (46,70; 40,71; 42,66; 44,63)"}},
      {q="Target: Felstone Field", g={43,85,"High Priestess MacDonnell, Chillwind Camp"}, o={37,57,"Cauldron Lord Bilemaw at Felstone Field; use the key on the cauldron"}, r={37,57,"Felstone cauldron"}},
      {q="Return to Chillwind Camp", p=1, g={37,57,"Felstone cauldron"}, r={43,85,"High Priestess MacDonnell"}},
      {q="Target: Dalson's Tears", g={43,85,"High Priestess MacDonnell"}, o={46,52,"Cauldron Lord Malvinious at Dalson's Tears"}, r={46,52,"Dalson's cauldron"}},
      {q="Return to Chillwind Camp", p=2, g={46,52,"Dalson's cauldron"}, r={43,85,"High Priestess MacDonnell"}},
      {q="Target: Writhing Haunt", g={43,85,"High Priestess MacDonnell"}, o={53,66,"Cauldron Lord Razarch at the Writhing Haunt"}, r={53,66,"Writhing Haunt cauldron"}},
      {q="Return to Chillwind Camp", p=3, g={53,66,"Writhing Haunt cauldron"}, r={43,85,"High Priestess MacDonnell"}},
      {q="Target: Gahrron's Withering", g={43,85,"High Priestess MacDonnell"}, o={63,59,"Cauldron Lord Soulwrath at Gahrron's Withering"}, r={63,59,"Gahrron's cauldron"}},
      {q="Return to Chillwind Camp", p=4, g={63,59,"Gahrron's cauldron"}, r={43,85,"High Priestess MacDonnell"}},
      {q="Argent Dawn Commission", g={43,85,"Argent Officer Pureheart, Chillwind Camp"}, r={43,85,"Argent Officer Pureheart"}},
      {q="Unfinished Business", p=1, g={42,80,"Kirsta Deepshadow, near Chillwind (verify)"}, o={45,18,"Scarlet Knights and Hunters at Hearthglen"}},
      {q="The Wildlife Suffers Too", p=1, g={53,66,"Mulgris Deepriver, Writhing Haunt"}, o={63,59,"Diseased bears around Gahrron's Withering"}},
      {q="Scholomance", g={43,85,"Alchemist Arbington, Chillwind Camp"}, r={43,85,"Alchemist Arbington"}},
      {q="Skeletal Fragments", g={43,85,"Alchemist Arbington"}, o={45,81,"15 Skeletal Fragments from Sorrow Hill skeletons"}},
      {q="Little Pamela", g={45,84,"Marlene Redpath, Sorrow Hill (verify)"}, r={47,75,"Pamela Redpath, Darrowshire",EPL}},
      {lv=57},
      {tr=true, x=75, y=52, map=EPL, t="Ride east to Light's Hope Chapel, Eastern Plaguelands."},
      {fp="Light's Hope", x=75, y=52, map=EPL},
      {q="Pamela's Doll", g={47,75,"Pamela Redpath, Darrowshire",EPL}, o={46,75,"Doll pieces in the ruined houses",EPL}},
      {q="Auntie Marlene", g={47,75,"Pamela Redpath",EPL}, r={45,84,"Marlene Redpath, Sorrow Hill (verify)",WPL}},
      {q="A Strange Historian", g={45,84,"Marlene Redpath",WPL}, r={39,66,"Chromie, Andorhal inn (verify)",WPL}},
      {q="Demon Dogs", g={8,66,"Tirion Fordring, Thondroril River (verify)",EPL}, o={15,70,"Plaguehound Runts and Plaguehounds",EPL}},
      {q="Blood Tinged Skies", g={8,66,"Tirion Fordring",EPL}, o={15,70,"Plaguebats",EPL}},
      {q="Carrion Grubbage", g={8,66,"Tirion Fordring",EPL}, o={15,70,"Carrion Grubs",EPL}},
      {q="Redemption", g={8,66,"Tirion Fordring",EPL}, o={45,18,"Follow the quest text (verify)",WPL}},
      {q="The Restless Souls", g={75,52,"Egan, Light's Hope (verify)",EPL}, o={27,12,"Stratholme: use the Egan's Blaster on the Restless Souls",EPL}},
      {q="The Flesh Does Not Lie", g={75,52,"Betina Bigglezink, Light's Hope",EPL}, o={40,30,"Plagued creatures for the Flesh Samples",EPL}},
      {q="Villains of Darrowshire", g={75,52,"Carlin Redpath, Light's Hope",EPL}, o={55,45,"Horgus the Ravager and Marduk Blackpool (verify)",EPL}},
      {q="Hidden Treasures", g={75,52,"Carlin Redpath",EPL}, o={47,75,"Joseph's Chest in Darrowshire",EPL}},
      {lv=58},
      {tr=true, x=60, y=50, map=WS, t="Fly to Everlook, Winterspring. Rebind."},
      {bind="Everlook", x=60, y=50, map=WS},
      {fp="Everlook", x=60, y=50, map=WS},
      {q="Winterfall Firewater", g={31,44,"Donova Snowden, Frostfire Hot Springs",WS}, o={66,33,"Winterfall furbolgs at Winterfall Village",WS}},
      {q="Falling to Corruption", g={31,44,"Donova Snowden",WS}, o={66,33,"Winterfall Village",WS}},
      {q="Mystery Goo", g={31,44,"Donova Snowden",WS}, o={66,33,"Winterfall Village",WS}},
      {q="Toxic Horrors", g={31,44,"Donova Snowden",WS}, o={55,50,"Toxic Horrors (verify)",WS}},
      {q="High Chief Winterfall", g={31,44,"Donova Snowden",WS}, o={69,38,"High Chief Winterfall in the cave",WS}},
      {q="Winterfall Activity", g={65,8,"Salfa, Timbermaw tunnel",WS}, o={66,33,"Winterfall Village",WS}},
      {q="Are We There, Yeti?", p=1, g={60,50,"Umi Rumplesnicker, Everlook",WS}, o={65,41,"Ice Thistle yetis",WS}},
      {q="Are We There, Yeti?", p=2, g={60,50,"Umi Rumplesnicker",WS}, o={65,41,"Ice Thistle yetis",WS}},
      {q="The Crystal of Zin-Malor", g={62,38,"Wynd Nightchaser, Starfall Village",WS}, o={53,42,"Lake of Kel'Theril fragments",WS}},
      {q="Guardians of the Altar", opt=true, g={63,59,"Ranshalla",WS}, o={63,59,"Escort her through Owl Wing Thicket",WS}},
      {tr=true, x=54, y=34, map=SIL, t="Silithus for the last bars: fly to Cenarion Hold."},
      {fp="Cenarion Hold", x=54, y=34, map=SIL},
      {q="Securing the Supply Lines", g={54,34,"Windcaller Proudhorn, Cenarion Hold",SIL}, o={55,45,"Hive'Zora silithid (verify)",SIL}},
      {q="Stepping Up Security", g={54,34,"Windcaller Proudhorn",SIL}, o={55,45,"Hive'Zora silithid (verify)",SIL}},
      {q="Deadly Desert Venom", g={54,34,"Beetix Ficklespragg",SIL}, o={50,50,"Scorpids and spiders (verify)",SIL}},
      {q="The Twilight Mystery", g={54,34,"Geologist Larksbane",SIL}, o={58,60,"Twilight's Hammer camps",SIL}},
      {q="Twilight Geolords", g={54,34,"Huum Wildmane",SIL}, o={58,60,"Twilight Geolords",SIL}},
      {man="Dungeons for the finish: Blackrock Depths (Jail Break!, Attunement to the Core), Lower Blackrock Spire (Put Her Down, Bijou), Dire Maul, Scholomance, Stratholme. One Stratholme clear is most of a level at 59.", x=27, y=12, map=EPL},
      {man="Paladin, level 60: Charger. Lord Grayson Shadowbreaker (Stormwind Cathedral): Emphasis on Sacrifice (150 g to High Priest Rohan, Ironforge) then Exorcising Terrordale (25 spirits, north-west Eastern Plaguelands); The Work of Grimand Elmore then Collection of Goods (150 g, 6 Arcanite Bars, 5 Stratholme Holy Water, 40 Runecloth, 10 Arthas' Tears), Manna-Enriched Horse Feed (Merideth Carlson, Southshore), Ancient Equine Spirit (Dire Maul West), Blessed Arcanite Barding; The Divination Scryer (Azerothian Diamond, Pristine Black Diamond); then Judgment and Redemption in the Scholomance Great Ossuary: place the scryer, judge the right Seal on each wave (verify order), kill Death Knight Darkreaver. Summon Charger.", cls="PALADIN", x=38, y=27, map=SW},
      {man="Warlock, level 60: Dreadsteed. Mor'zul Bloodbringer, hill across from the Altar of Storms, north-west Burning Steppes (12,31): Rage of Blood then Wildeyes; Lord Banehollow (Shadow Hold, Jaedenar) then Ulathek the Traitor then Xorothian Stardust; buy the Bell of Dethmoora, Wheel of the Black March, Doomsday Candle and Arcanite from Gorzeeki (about 150 g of materials, verify); Imp Delivery (carry J'eevee to Ras Frostwhisper's room, Scholomance); Dreadsteed of Xoroth in Dire Maul West: kill Immol'thar, drop the pylons, run the ritual, kill the Dreadsteed Spirit and its guards. Summon Dreadsteed.", cls="WARLOCK", x=12, y=31, map=BS},
      {forever=true, t="Mount Hyjal is the new 60 zone and two new 10-20 player raids come with launch. The cap is permanent."},
      {lv=60},
    },
  },
}

-- Human route = the four brackets above, then the shared Alliance brackets.
local ROUTE_BRACKETS = {}
for _, b in ipairs(ns.HUMAN_BRACKETS) do table.insert(ROUTE_BRACKETS, b) end
for _, b in ipairs(ns.ALLIANCE_BRACKETS) do table.insert(ROUTE_BRACKETS, b) end

table.insert(ns.ROUTES, {
  id = "human", name = "The King's Road", faction = "Alliance",
  races = { Human = true }, raceOnly = 4,
  brackets = ROUTE_BRACKETS,
})
