-- Evergreen route data. Each route is a list of level brackets; brackets are lists of atomic steps.
--
-- Step kinds:
--   {q="Quest Name", p=part, id=questID, g={x,y,"Giver NPC",map}, o={x,y,"objective text",map}, r={x,y,"Turn-in NPC",map}, opt=true}
--       quest step. Auto-completes when turned in. Arrow: not on quest -> g; on quest, not complete -> o; complete -> r (defaults to g).
--       p = which occurrence of a repeated chain name this is (A New Plague x3, Arugal's Folly x4 ...). id is optional and only used
--       for quests with a unique name whose Classic quest id is known.
--   {tr=true, x,y,map,t="text", any=true}   travel. Auto-completes within 3 map units of x,y, or (any=true) when you are on that map at all.
--   {bind="Brill", x,y,map}                  hearth bind. Auto-completes when GetBindLocation() contains the string.
--   {fp="Sepulcher", x,y,map}                flight point. Auto-completes when you open the taxi map near it.
--   {lv=10}                                  level gate. Auto-completes at that level.
--   {note="Label", t="text"}                 never current; shown inline.
--   {forever=true, t="text"}                 WoW Forever note; hideable.
--   {man="text", x,y,map}                    manual tick.
-- Any step may add cls="DRUID" (or cls={DRUID=true, SHAMAN=true}): a class quest, shown only to
-- that class. The engine drops the other classes' steps when it selects the route.
-- race="Gnome" (or a set, by UnitRace file name) narrows a step to one race the same way; used for
-- Forever's new race/class combos inside shared brackets (Routes_Forever_Combos.lua).
-- Coordinates without a map use the bracket's map. Coordinates marked (verify) are approximate.

local ADDON, ns = ...

ns.MAP_NAMES = {
  [1420]="Tirisfal Glades", [1421]="Silverpine Forest", [1413]="The Barrens", [1424]="Hillsbrad Foothills",
  [1440]="Ashenvale", [1441]="Thousand Needles", [1434]="Stranglethorn Vale", [1443]="Desolace",
  [1417]="Arathi Highlands", [1445]="Dustwallow Marsh", [1418]="Badlands", [1435]="Swamp of Sorrows",
  [1446]="Tanaris", [1444]="Feralas", [1425]="The Hinterlands", [1427]="Searing Gorge",
  [1449]="Un'Goro Crater", [1448]="Felwood", [1428]="Burning Steppes", [1447]="Azshara",
  [1422]="Western Plaguelands", [1423]="Eastern Plaguelands", [1452]="Winterspring", [1451]="Silithus",
  [1458]="Undercity", [1454]="Orgrimmar", [1456]="Thunder Bluff", [1411]="Durotar",
  [1412]="Mulgore", [1442]="Stonetalon Mountains", [1450]="Moonglade", [1419]="Blasted Lands",
}

local UC = 1458
local UC_APOTH = {48,68,"Apothecarium, Undercity",UC}
local UC_MAGIC = {84,18,"Magic Quarter, Undercity",UC}

ns.BRACKETS = {
  -- ============================================================ 1-6 Deathknell
  {
    id="b1", lv={1,6}, name="Deathknell", map=1420,
    hub="Deathknell", hearth="None yet (no inn)", fp="None",
    steps={
      {note="Before you move", t="Turn on Auto Loot. Bind a key to Cannibalize. All five class trainers stand inside the chapel; the scroll you spawn with is a free turn-in there."},
      {q="Rude Awakening", g={30,72,"Undertaker Mordo"}, r={31,66,"Shadow Priest Sarvis, chapel"}},
      {q="The Mindless Ones", g={31,66,"Shadow Priest Sarvis"}, o={31,69,"8 Mindless Zombies, 8 Wretched Zombies around the chapel yard"}},
      {q="The Damned", g={31,66,"Novice Elreth"}, o={29,62,"6 Scavenger Paws (Young Scavengers), 6 Duskbat Wings, fields west"}},
      {q="Rattling the Rattlecages", g={31,66,"Shadow Priest Sarvis"}, o={34,62,"8 Rattlecage Skeletons in the ruined houses across the road"}},
      {q="Scavenging Deathknell", g={32,66,"Deathguard Saltain"}, o={34,62,"6 Scavenged Goods from crates in the same ruined houses"}},
      {q="Marla's Last Wish", g={31,66,"Novice Elreth"}, o={36,62,"Kill Samuel Fipps by the eastern houses, loot his remains, click Marla's grave at 30,70"}},
      {q="Night Web's Hollow", g={32,66,"Executor Arren"}, o={27,59,"10 Young Night Web Spiders outside, 8 Night Web Spiders inside the cave"}},
      {q="The Scarlet Crusade", g={32,66,"Executor Arren"}, o={36,67,"12 Scarlet Armbands from Scarlet Converts, camp south-east"}},
      {q="The Red Messenger", g={32,66,"Executor Arren"}, o={36,68,"Meven Korgal in the tent; loot the Scarlet Crusade Documents"}},
      {q="A Rogue's Deal", p=1, opt=true, g={38,56,"Calvin Montague, house on the road out of Deathknell"}, r={61,52,"Innkeeper Renee, Brill"}},
      {q="Vital Intelligence", g={32,66,"Executor Arren"}, r={61,52,"Executor Zygand, Brill town hall"}},
      {forever=true, t="Forsaken paladins get a separate branch here: Bandarion Keep in the Whispering Wood, north of the road."},
    },
  },
  -- ============================================================ 6-12 Brill
  {
    id="b2", lv={6,12}, name="Brill & Tirisfal Glades", map=1420,
    hub="Brill", hearth="Gallows' End Tavern (Innkeeper Renee)", fp="None here; Undercity's is inside the city",
    steps={
      {tr=true, x=61, y=52, t="Walk to Brill. Kill scavengers on the road; Solliden Farmstead (37,50) is on the way and you come back for it."},
      {bind="Brill", x=61, y=52},
      {note="Pickup sweep", t="One lap: Zygand and Sevren in the town hall, Johaan behind it, Dillinger at the gate, Gretchen Dedmar, Junior Apothecary Holland, Coleman Farthing by the graveyard, the Wanted poster, Gordo on the road east. Learn First Aid (Nurse Neela), buy Coarse Thread."},
      {q="A Putrid Task", g={60,52,"Deathguard Dillinger"}, o={54,54,"7 Putrid Claws from Ravaged Corpses and Rotting Deads, cemetery west of Brill"}},
      {q="Gordo's Task", g={43,55,"Gordo, on the road west of Brill near Solliden"}, o={56,53,"3 Gloom Weed off the ground around the cemetery"}, r={62,51,"Junior Apothecary Holland"}},
      {q="Doom Weed", g={62,51,"Junior Apothecary Holland"}, o={56,45,"10 Doom Weed off the ground, west and north of Brill toward Garren's Haunt"}},
      {q="A New Plague", p=1, g={61,52,"Apothecary Johaan"}, o={58,54,"5 Vials of Darkhound Blood from Darkhounds on the roads around Brill"}},
      {q="The Chill of Death", g={61,53,"Gretchen Dedmar"}, o={58,56,"5 Duskbat Pelts (Duskbats at night, south of Brill) plus Coarse Thread from the trade vendor"}},
      {q="Fields of Grief", p=1, g={41,54,"Deathguard Simmer, Solliden Farmstead"}, o={37,50,"10 Tirisfal Pumpkins at Solliden Farmstead; pull the farmers and farmhands first"}},
      {q="At War With The Scarlet Crusade", p=1, g={61,52,"Executor Zygand"}, o={50,65,"10 Scarlet Warriors at the camp south-west of Brill"}},
      {q="At War With The Scarlet Crusade", p=2, g={61,52,"Executor Zygand"}, o={51,67,"3 Scarlet Zealots, 3 Scarlet Missionaries at the camp, then Captain Perrine in the tower. WotF for the fears."}},
      {q="The Haunted Mills", id=362, g={60,53,"Coleman Farthing"}, o={44,38,"Devlin Agamand chatters on the road into Agamand Mills; loot Devlin's Remains"}},
      {q="Graverobbers", id=358, g={61,52,"Magistrate Sevren"}, o={55,32,"8 Embalming Ichor from Rot Hide gnolls at Garren's Haunt and the Mass Grave"}},
      {q="Wanted: Maggot Eye", g={61,52,"Wanted poster, Brill"}, o={58,31,"Maggot Eye (level 10) in the tent at Garren's Haunt"}, r={61,52,"Magistrate Sevren"}},
      {q="A New Plague", p=2, g={61,52,"Apothecary Johaan"}, o={61,27,"5 Vile Fin Scales from the murlocs on the north shore"}},
      {q="Deaths in the Family", g={60,53,"Coleman Farthing"}, o={46,31,"Gregor, Nissa and Thurman Agamand inside Agamand Mills (Thurman in the big barn)"}},
      {q="Rear Guard Patrol", id=356, g={65,60,"Deathguard Linnea, on the road east of Brill"}, o={75,60,"8 Bleeding Horrors, 8 Wandering Spirits at Balnir Farmstead"}},
      {lv=10},
      {tr=true, x=65, y=40, map=UC, any=true, t="Level 10: Undercity. Train, learn Skinning plus a gathering profession, do the Apothecarium deliveries. Mage: Anastasia Hartwell. Warlock: Carendin Halgar (Voidwalker). Rogue: Mennet Carkad. Warrior: Deathguard Dillinger in Brill. Priest: buy Devouring Plague and Touch of Weakness."},
      {q="Fields of Grief", p=2, g={61,52,"Apothecary Johaan"}, r=UC_APOTH},
      {q="The Prodigal Lich", g={61,52,"Magistrate Sevren"}, r=UC_MAGIC},
      {q="The Lich's Identity", g=UC_MAGIC, o={68,42,"The Lich's Spellbook (follow the quest text; verify)"}, r=UC_MAGIC},
      {q="Return the Book", g=UC_MAGIC, r={68,41,"Gunther Arcanus, Gunther's Retreat (island in Brightwater Lake)"}},
      {q="Proving Allegiance", g={68,41,"Gunther Arcanus"}, o={68,42,"Kill Lillith Nefara for the Candle of Beckoning"}},
      {q="The Prodigal Lich Returns", id=411, g={68,41,"Gunther Arcanus"}, r=UC_MAGIC},
      {q="At War With The Scarlet Crusade", p=3, g={61,52,"Executor Zygand"}, o={78,55,"Captain Vachon (top of the tower) and 5 Scarlet Friars at the Crusader Outpost"}},
      {q="A New Plague", p=3, g={61,52,"Apothecary Johaan"}, o={85,50,"4 Vicious Night Web Spider Venom at Venomweb Vale (verify)"}},
      {q="A New Plague", p=4, g={61,52,"Apothecary Johaan"}, r={61,51,"Captured Mountaineer, Brill"}},
      {q="At War With The Scarlet Crusade", p=4, g={61,52,"Executor Zygand"}, o={79,25,"Captain Melrache and two bodyguards at the Scarlet Watch Post; pull the guards one at a time"}},
      {q="Speak with Sevren", g={60,53,"Coleman Farthing"}, r={61,52,"Magistrate Sevren"}},
      {q="The Family Crypt", g={61,52,"Magistrate Sevren"}, o={52,27,"Captain Dargol (level 13) at the bottom of the Agamand crypt; clear the Ancestors to him at 12"}},
      {forever=true, t="A new 15-25 Horde zone on the Undercity surface plus a Ruins of Lordaeron dungeon is being built for this stretch. Expect to come back at 15."},
      {lv=12},
    },
  },
  -- ============================================================ 12-18 Silverpine
  {
    id="b3", lv={12,18}, name="Silverpine Forest", map=1421,
    hub="The Sepulcher", hearth="Sepulcher inn (Innkeeper Bates)", fp="Sepulcher (Karos Razok)",
    steps={
      {tr=true, x=45, y=42, t="Road south out of Brill to the Sepulcher."},
      {bind="Sepulcher", x=45, y=42},
      {fp="Sepulcher", x=45, y=42},
      {note="Watch for", t="Sons of Arugal (level 20+) patrol the northern roads and the Skittering Dark. Pull nothing while one is in view. Pyrewood turns into worgen at night; wait until 16 for it."},
      {q="Lost Deathstalkers", g={45,42,"High Executor Hadrec"}, r={53,13,"Rane Yorick, north Silverpine"}},
      {q="The Dead Fields", g={45,42,"High Executor Hadrec"}, o={45,21,"Kill Rot Hide gnolls at the Dead Fields until Nightlash spawns; loot Nightlash's Essence"}},
      {q="A Recipe For Death", p=1, g={45,42,"Apothecary Renferrel"}, o={36,15,"6 Skittering Blood from the spiders in the Skittering Dark, 6 Grizzled Bear Hearts from the bears outside"}, r={48,68,"Master Apothecary Faranell, Apothecarium",UC}},
      {q="Prove Your Worth", id=421, g={44,40,"Dalar Dawnweaver"}, o={55,20,"5 Moonrage Whitescalps in the hills north-east of the Dead Fields"}, r={44,40,"Dalar Dawnweaver"}},
      {q="Arugal's Folly", p=1, g={45,42,"Dalar Dawnweaver"}, o={52,28,"Dusty Spellbooks, second floor of the ruined wheat farm north of the bridge (Remedy of Arugal)"}},
      {q="Border Crossings", id=477, g={45,42,"High Executor Hadrec"}, o={50,60,"Open the crate at the Dalaran camp north of Pyrewood"}, r={50,60,"The crate"}},
      {q="Escorting Erland", g={56,9,"Deathstalker Erland"}, o={54,11,"Escort Erland back to Rane; he stops to fight worgs"}, r={53,13,"Rane Yorick"}},
      {q="Wild Hearts", g={53,13,"Rane Yorick"}, o={55,10,"6 Discolored Worg Hearts from Mottled Worgs"}, r={43,41,"Apothecary Renferrel, Sepulcher"}},
      {q="The Deathstalkers' Report", g={53,13,"Rane Yorick"}, r={45,42,"High Executor Hadrec"}},
      {q="Speak with Renferrel", id=3221, g={43,41,"High Executor Hadrec"}, r={43,41,"Apothecary Renferrel"}},
      {q="Return to Quinn", g={43,41,"Apothecary Renferrel, Sepulcher"}, r={53,13,"Quinn Yorick, Ivar Patch"}},
      {q="Ivar the Foul", g={53,13,"Rane Yorick (after Return to Quinn)"}, o={56,10,"Ivar the Foul and a friend at his patch; back against the fence, one at a time"}, r={53,13,"Rane Yorick"}},
      {q="Maps and Runes", g={50,60,"The Dalaran crate"}, o={50,60,"Dalaran Apprentices and Summoners around the camp"}, r={45,42,"High Executor Hadrec"}},
      {q="Dalar's Analysis", id=481, g={44,41,"Shadow Priest Allister"}, r={44,40,"Dalar Dawnweaver"}},
      {q="Dalaran's Intentions", id=482, g={44,40,"Dalar Dawnweaver"}, r={44,41,"Shadow Priest Allister"}},
      {q="Ambermill Investigations", id=479, g={44,41,"Shadow Priest Allister"}, o={66,60,"Dalaran Apprentices and Summoners in Ambermill; they come in pairs"}},
      {q="The Decrepit Ferry", g={45,42,"High Executor Hadrec"}, r={58,35,"Corpse-laden boat on the lake shore"}},
      {q="Rot Hide Clues", g={58,35,"Corpse-laden boat"}, r={45,42,"High Executor Hadrec"}},
      {q="A Recipe For Death", p=2, g={48,68,"Master Apothecary Faranell, Apothecarium",UC}, o={43,73,"Apothecary Berard's journal in Pyrewood Village (kill Berard, loot the bookshelf)"}, r={45,42,"Apothecary Renferrel"}},
      {q="A Recipe For Death", p=3, g={45,42,"Apothecary Renferrel"}, o={62,38,"6 Lake Skulker Moss, 6 Lake Creeper Moss on the east lake shore, plus a Hardened Tumor from the murlocs"}, r={48,68,"Master Apothecary Faranell, Apothecarium",UC}},
      {q="Arugal's Folly", p=2, g={45,42,"Dalar Dawnweaver"}, o={45,72,"6 Glutton Shackles, 3 Darksoul Shackles from Moonrage Gluttons and Darksouls in the fields around Pyrewood"}},
      {q="Arugal's Folly", p=3, g={45,42,"Dalar Dawnweaver"}, o={60,65,"Grimson the Pale in the Deep Elem Mine, hills south-east of the Sepulcher (verify)"}},
      {q="Arugal's Folly", p=4, g={45,42,"Dalar Dawnweaver"}, o={45,72,"6 Pyrewood Shackles from the Pyrewood villagers after dark"}},
      {q="Zinge's Delivery", g={45,42,"Apothecary Renferrel"}, r={48,68,"Apothecary Zinge, Apothecarium",UC}},
      {q="Rot Hide Ichor", g={45,42,"The Sepulcher"}, o={45,21,"8 Rot Hide Ichor from the gnolls at the Dead Fields"}},
      {q="Rot Hide Origins", g={45,42,"The Sepulcher"}, r=UC_MAGIC},
      {q="Thule Ravenclaw", g=UC_MAGIC, r={45,42,"Apothecary Renferrel"}},
      {q="Report to Hadrec", id=448, g={45,42,"Apothecary Renferrel"}, r={45,42,"High Executor Hadrec"}},
      {lv=17},
      {q="Beren's Peril", g={45,42,"Shadow Priest Allister"}, o={57,72,"6 Ravenclaw Drudgers, 6 Ravenclaw Guardians in the cave south of Ambermill"}},
      {q="Assault on Fenris Isle", id=442, opt=true, g={45,42,"High Executor Hadrec"}, o={65,23,"Thule Ravenclaw in Fenris Keep (level 24; do it with the Shadowfang group)"}},
      {q="Deathstalkers in Shadowfang", opt=true, g={45,42,"High Executor Hadrec"}, o={45,68,"Shadowfang Keep: find Deathstalkers Adamant and Vincent"}},
      {q="Arugal Must Die", opt=true, g={45,42,"Dalar Dawnweaver"}, o={45,68,"Shadowfang Keep: Archmage Arugal"}},
      {q="The Book of Ur", opt=true, g={48,68,"Keeper Bel'dugur, Apothecarium",UC}, o={45,68,"Shadowfang Keep: the Book of Ur in the library"}},
    },
  },
  -- ============================================================ 17-20 Barrens
  {
    id="b4", lv={17,20}, name="The Barrens", map=1413,
    hub="The Crossroads", hearth="Crossroads inn (Boorand Plainswind), this bracket only", fp="Orgrimmar, Crossroads, Ratchet",
    steps={
      {tr=true, x=50, y=60, map=1454, any=true, t="Hearth to the Sepulcher, walk to Undercity, zeppelin (north platform of the tower) to Orgrimmar."},
      {fp="Orgrimmar", x=44, y=59, map=1454},
      {tr=true, x=52, y=30, t="South through Durotar, west at Razor Hill, into the Barrens. Crossroads."},
      {bind="Crossroads", x=52, y=30},
      {fp="Crossroads", x=52, y=30},
      {q="Supplies for the Crossroads", g={51,30,"Thork"}, o={47,29,"6 Crossroads Supply Crates at the wrecked caravans north and west"}},
      {q="Disrupt the Attacks", g={51,30,"Thork"}, o={58,25,"Razormane quilboar at Thorn Hill"}},
      {q="The Disruption Ends", g={51,30,"Thork"}, o={58,25,"Kreenig Snarlsnout at Thorn Hill"}},
      {q="Plainstrider Menace", g={52,30,"Sergra Darkthorn"}, o={50,35,"7 Plainstrider Beaks, all around the Crossroads"}},
      {q="The Zhevra", g={52,30,"Sergra Darkthorn"}, o={49,37,"Zhevra Hooves, south and west"}},
      {q="Prowlers of the Barrens", g={52,30,"Sergra Darkthorn"}, o={46,37,"Savannah Prowlers and Huntresses"}},
      {q="Echeyakee", g={52,30,"Sergra Darkthorn"}, o={52,19,"Blow the horn at the den north of town; kill the white lion"}},
      {q="The Forgotten Pools", g={52,30,"Tonga Runetotem"}, o={45,30,"Visit the Forgotten Pools north-west"}},
      {q="Fungal Spores", g={51,30,"Apothecary Helbrim"}, o={45,30,"8 Fungal Spores from the beasts around the oases"}},
      {q="Lost in Battle", g={51,30,"Mankrik"}, o={51,50,"The Beaten Corpse south of the road, not in the hills"}},
      {q="Centaur Bracers", g={51,30,"Regthar Deathgate, bunker west of town"}, o={42,40,"15 Centaur Bracers from Kolkar centaur at the Forgotten Pools and Lushwater Oasis"}},
      {q="Kolkar Leaders", g={51,30,"Regthar Deathgate"}, o={42,40,"Barak Kodobane at the Kolkar camp near Lushwater Oasis"}},
      {q="Harpy Raiders", g={52,30,"Darsok Swiftdagger"}, o={43,15,"Witchwing harpies at the Dry Hills"}},
      {q="Harpy Lieutenants", g={52,30,"Darsok Swiftdagger"}, o={43,13,"Witchwing Slayers and Roguefeathers at the Dry Hills"}},
      {q="Serena Bloodfeather", g={52,30,"Darsok Swiftdagger"}, o={40,10,"Serena Bloodfeather (level 20 with adds; go at 19)"}},
      {tr=true, x=62, y=37, t="Ratchet."},
      {fp="Ratchet", x=63, y=37},
      {q="Southsea Freebooters", g={62,37,"Gazlowe"}, o={68,45,"Southsea pirates on the coast south of Ratchet"}},
      {q="Samophlange", p=1, g={62,37,"Sputtervalve"}, r={63,30,"Wenikee Boltbucket, road north of Ratchet"}},
      {q="Samophlange", p=2, g={63,30,"Wenikee Boltbucket"}, o={59,8,"Venture Co. rig at the Sludge Fen, far north: control console, then the samophlange parts (verify)"}},
      {q="Raptor Horns", g={62,37,"Mebok Mizzyrix"}, o={60,45,"Sunscale raptors south of Ratchet"}},
      {q="Deviate Hides", opt=true, g={46,36,"Nalpak, outside Wailing Caverns"}, o={46,36,"Wailing Caverns"}},
      {q="Trouble at the Docks", opt=true, g={63,37,"Crane Operator Bigglefuzz"}, o={46,36,"Mad Magglish inside Wailing Caverns"}},
      {q="Serpentbloom", opt=true, g={48,68,"Apothecary Zinge, Apothecarium",UC}, o={46,36,"Wailing Caverns (Horde only)"}},
      {lv=20},
    },
  },
  -- ============================================================ 20-25 Hillsbrad
  {
    id="b5", lv={20,25}, name="Hillsbrad Foothills", map=1424,
    hub="Tarren Mill", hearth="Tarren Mill inn (Innkeeper Shay)", fp="Tarren Mill (Zarise)",
    steps={
      {tr=true, x=62, y=20, t="Fly Crossroads to Orgrimmar, zeppelin to Undercity, fly to the Sepulcher, road east into Hillsbrad. Tarren Mill."},
      {bind="Tarren Mill", x=62, y=20},
      {fp="Tarren Mill", x=62, y=20},
      {note="PvP note", t="Southshore is a mile south. On a PvP realm this bracket is a war zone; quest in off-hours."},
      {q="Battle of Hillsbrad", p=1, g={62,19,"Deathguard Samsa"}, o={30,42,"6 Hillsbrad Farmhands, 6 Farmers, Farmer Ray and Farmer Getz at Hillsbrad Fields"}, r={62,19,"High Executor Darthalia"}},
      {q="Elixir of Suffering", id=496, g={62,19,"Apothecary Lydon"}, o={60,25,"10 Gray Bear Tongues, 1 Creeper Ichor (Forest Moss Creepers) around Tarren Mill"}},
      {q="Elixir of Pain", g={62,19,"Apothecary Lydon"}, o={50,30,"Mountain Lion Blood from Starving Mountain Lions in the hills west and north (verify)"}},
      {q="Stone Tokens", g={62,19,"Krusk"}, o={64,58,"Stone Tokens from Daggerspine naga on the coast south-east"}},
      {q="WANTED: Syndicate Personnel", g={62,19,"Wanted poster, Tarren Mill"}, o={76,46,"Jailor Marigen, Jailor Eston and Drull inside Durnholde Keep; Syndicate packs here are the best grind at 22-24"}},
      {q="Battle of Hillsbrad", p=2, g={62,19,"High Executor Darthalia"}, o={30,44,"15 Hillsbrad Peasants in the fields"}},
      {q="Battle of Hillsbrad", p=3, g={62,19,"High Executor Darthalia"}, o={31,42,"Blacksmith Verringtan and 4 Apprentice Blacksmiths in the forge house; loot the Shipment of Iron"}},
      {q="Battle of Hillsbrad", p=4, g={62,19,"High Executor Darthalia"}, o={30,40,"Hillsbrad town hall: Magistrate Burnside and 4 Councilmen, destroy the Proclamation, steal the Town Registry. Pull each room to the doorway."}},
      {q="Battle of Hillsbrad", p=5, g={62,19,"High Executor Darthalia"}, o={26,58,"Azurelode Mine: 10 Hillsbrad Miners, then Foreman Bonds at the entrance (he calls two dwarves)"}},
      {q="Elixir of Agony", p=1, g={62,19,"Apothecary Lydon"}, o={65,60,"6 Mudsnout Blossoms in the Mudsnout gnoll camp"}},
      {q="Elixir of Agony", p=2, g={62,19,"Apothecary Lydon"}, r={48,68,"Master Apothecary Faranell, Apothecarium",UC}},
      {q="Elixir of Agony", p=3, opt=true, g={48,68,"Master Apothecary Faranell",UC}, o={64,58,"5 Daggerspine Scales and 5 Torn Fin Eyes on the coast, plus a Strong Troll's Blood Potion (alchemist or auction house)"}, r={62,19,"Apothecary Lydon"}},
      {q="Helcular's Revenge", p=1, g={63,19,"Novice Thaivand, Tarren Mill"}, o={45,25,"Helcular's Rod drops from the yetis in the hills north-west (verify)"}},
      {q="Helcular's Revenge", p=2, g={63,19,"Novice Thaivand"}, o={52,53,"Charge the rod at the Flames of Azel, Veraz and Uzel (Questie or the map marks them), then use it on Helcular's Grave in the Southshore graveyard"}, r={52,53,"Helcular's Grave"}},
      {man="Shadowfang Keep (22-25) with the Silverpine quests, plus Assault on Fenris Isle on the way. Two hours for two levels and a weapon.", x=45, y=68, map=1421},
      {q="Battle of Hillsbrad", p=6, opt=true, g={62,19,"High Executor Darthalia"}, o={75,80,"Dun Garok: 8 Mountaineers, 4 Riflemen, 2 Priests and Captain Ironhill. Group job at 27-28."}},
      {q="Battle of Hillsbrad", p=7, opt=true, g={62,19,"High Executor Darthalia"}, r={58,90,"Varimathras, Royal Quarter",UC}},
      {forever=true, t="Nothing announced touches Hillsbrad. The new Undercity-surface zone may push this bracket to start at 22."},
      {lv=25},
    },
  },
  -- ============================================================ 25-30 Ashenvale -> Needles
  {
    id="b6", lv={25,30}, name="Ashenvale, then Thousand Needles", map=1440,
    hub="Splintertree Post, then Freewind Post", hearth="Tarren Mill until 27, then Freewind Post", fp="Splintertree, Zoram'gar, Sun Rock, Freewind, Thunder Bluff",
    steps={
      {tr=true, x=73, y=61, t="Fly Tarren Mill to Undercity, zeppelin to Orgrimmar, fly or ride to Splintertree Post."},
      {fp="Splintertree", x=73, y=61},
      {q="Ashenvale Outrunners", g={73,61,"Kadrak"}, o={60,60,"8 stealthed Ashenvale Outrunners on the road west; fast XP"}},
      {q="Warsong Supplies", g={73,61,"Kadrak"}, o={84,68,"Warsong Labor Camp, east"}},
      {q="Torek's Assault", g={73,61,"Torek"}, o={66,73,"Five-orc raid on Silverwing Outpost; stay behind the pack"}},
      {q="Sharptalon's Claw", g={57,47,"Loot: Sharptalon, level 31 hippogryph. Pull him to the Forsaken camp guards at 75,71"}, r={73,61,"Senani Thunderheart"}},
      {q="Ursangous's Paw", g={40,65,"Loot: Ursangous, named bear (verify)"}, r={73,61,"Senani Thunderheart"}},
      {q="Shadumbra's Head", g={58,55,"Loot: Shadumbra, named cat near the Laughing Sisters camp (verify)"}, r={73,61,"Senani Thunderheart"}},
      {q="Satyr Horns", g={73,61,"Splintertree Post"}, o={81,52,"Satyrs at Satyrnaar"}},
      {q="Naga at the Zoram Strand", opt=true, g={12,34,"Muglash, Zoram'gar Outpost"}, o={12,30,"20 Wrathtail Heads on the strand; Underwater Breathing makes it painless"}},
      {lv=27},
      {tr=true, x=46, y=51, map=1441, t="Fly to Freewind Post, Thousand Needles."},
      {bind="Freewind", x=46, y=51, map=1441},
      {fp="Freewind", x=46, y=51, map=1441},
      {q="Pacify the Centaur", g={46,51,"Cliffwatcher Longhorn, Freewind Post",1441}, o={30,32,"15 Galak centaur west along the canyon",1441}},
      {q="Grimtotem Spying", g={46,51,"Cliffwatcher Longhorn",1441}, o={31,36,"Three secret notes in chests on Darkcloud Pinnacle (wooden bridges)",1441}},
      {q="Wanted - Arnak Grimtotem", g={46,50,"Wanted poster, Freewind Post",1441}, o={31,36,"Arnak Grimtotem on Darkcloud Pinnacle; watch for adds",1441}, r={45,50,"Cliffwatcher Longhorn",1441}},
      {q="Alien Egg", g={46,51,"Katu, Freewind Post",1441}, o={56,50,"Find the egg on the ground (56,50 / 52,55 / 38,55)",1441}},
      {q="Homeward Bound", g={12,32,"Pao'ka Swiftmountain, Highperch",1441}, o={20,40,"Escort Pao'ka out of Highperch",1441}, r={46,51,"Freewind Post",1441}},
      {q="Test of Faith", g={54,44,"Dorn Plainstalker, cave",1441}, o={54,44,"Jump off the wooden planks; no fall damage",1441}},
      {q="Test of Endurance", g={54,44,"Dorn Plainstalker",1441}, o={54,44,"Local test; follow the quest text",1441}},
      {q="Test of Strength", g={54,44,"Dorn Plainstalker",1441}, o={54,44,"Local test; follow the quest text (skip Test of Lore)",1441}},
      {tr=true, x=78, y=76, map=1441, t="Shimmering Flats: the Mirage Raceway at 29-31. Flat ground, no travel, no downtime."},
      {q="Hardened Shells", g={78,77,"Fizzle Brassbolts, Mirage Raceway",1441}, o={82,72,"Saltstone tortoises on the flats",1441}},
      {q="Salt Flat Venom", g={78,77,"Fizzle Brassbolts",1441}, o={85,70,"Scorpids on the flats",1441}},
      {q="Load Lightening", g={78,77,"Pozzik",1441}, o={75,70,"Basilisk hides on the flats",1441}},
      {q="Rocket Car Parts", g={78,77,"Zamek",1441}, o={80,76,"Rocket Car Parts lying on the flats",1441}},
      {q="Goblin Sponsorship", p=1, g={78,77,"Pozzik",1441}, r={62,37,"Gazlowe, Ratchet",1413}},
      {q="Going, Going, Guano!", opt=true, g={48,68,"Master Apothecary Faranell",UC}, o={42,90,"Razorfen Kraul (29-33)",1413}},
      {lv=30},
    },
  },
  -- ============================================================ 30-35 STV + Desolace
  {
    id="b7", lv={30,35}, name="Stranglethorn Vale, with a Desolace swing", map=1434,
    hub="Grom'gol, then Shadowprey Village", hearth="Grom'gol (Innkeeper Thulbek), then Shadowprey", fp="Grom'gol, Booty Bay, Shadowprey",
    steps={
      {tr=true, x=32, y=29, t="Hearth to Freewind, fly Orgrimmar, zeppelin to Undercity, zeppelin to Grom'gol."},
      {bind="Grom'gol", x=32, y=29},
      {fp="Grom'gol", x=32, y=29},
      {note="Buy food", t="Beasts leave nothing to Cannibalize. This is the first zone where you carry food and drink."},
      {q="Welcome to the Jungle", g={32,29,"Nimboya, Grom'gol"}, r={35,10,"Hemet Nesingwary, expedition camp"}},
      {q="Panther Mastery", p=1, g={35,10,"Sir S. J. Erlgadin"}, o={40,15,"10 Young Panthers"}},
      {q="Tiger Mastery", p=1, g={35,10,"Ajeck Rouack"}, o={36,15,"10 Young Stranglethorn Tigers"}},
      {q="Raptor Mastery", p=1, g={35,10,"Barnil Stonepot"}, o={42,20,"10 Stranglethorn Raptors"}},
      {q="Panther Mastery", p=2, g={35,10,"Sir S. J. Erlgadin"}, o={38,22,"10 Shadow Panthers"}},
      {q="Tiger Mastery", p=2, g={35,10,"Ajeck Rouack"}, o={36,22,"10 Stranglethorn Tigers"}},
      {q="Raptor Mastery", p=2, g={35,10,"Barnil Stonepot"}, o={45,30,"10 Lashtail Raptors"}},
      {q="Hunt for Yenniku", g={32,29,"Nimboya"}, o={20,20,"Bloodscalp trolls north-west toward Zul'Kunda (verify)"}},
      {q="Headhunting", g={32,29,"Nimboya"}, o={20,15,"Bloodscalp and Skullsplitter heads (verify)"}},
      {q="Trollbane", g={32,28,"Kin'weelay"}, o={20,18,"Bloodscalp Speaker heads (verify)"}},
      {q="The Defense of Grom'gol", p=1, g={32,29,"Commander Aggro'gosh"}, o={30,35,"Raptors and trolls beside the camp"}},
      {tr=true, x=27, y=77, t="Booty Bay, by road south or the Grom'gol flight once you have it."},
      {fp="Booty Bay", x=27, y=77},
      {q="Supply and Demand", g={27,77,"Drizzlik, Booty Bay"}, o={33,45,"8 Crocolisk hides on the river north of Grom'gol"}},
      {q="Scaring Shaky", g={27,77,"Sea Wolf MacKinley"}, o={32,72,"Follow the quest text (verify)"}},
      {q="Singing Blue Shards", g={28,76,"Brikk Keencraft"}, o={52,36,"Mosh'Ogg ogres, 36+"}},
      {lv=32},
      {tr=true, x=24, y=70, map=1443, t="Desolace: zeppelin to Orgrimmar, fly to Shadowprey Village via Sun Rock."},
      {bind="Shadowprey", x=24, y=70, map=1443},
      {fp="Shadowprey", x=24, y=70, map=1443},
      {q="Clam Bait", g={24,68,"Jinar'Zillen, Shadowprey",1443}, o={21,72,"Clams underwater off the village",1443}},
      {q="Kodo Roundup", g={62,38,"Smeed Scrabblescrew, Kodo Graveyard",1443}, o={60,40,"Rope six aged kodos back to Smeed",1443}},
      {q="Ghost-o-plasm Round Up", g={24,70,"Shadowprey Village (verify giver)",1443}, o={62,38,"Ghosts at the Kodo Graveyard (verify)",1443}},
      {q="Sceptre of Light", g={38,27,"Ethel Rethor, north road",1443}, o={55,32,"Thunder Axe Fortress: Burning Blade cultists",1443}},
      {q="Book of the Ancients", g={38,27,"Ethel Rethor",1443}, o={28,16,"Ranazjar Isle, underwater (verify)",1443}},
      {q="Hand of Iruxos", g={38,27,"Ethel Rethor",1443}, o={51,37,"Demon crystal (verify)",1443}},
      {q="Claim Rackmore's Treasure!", g={36,30,"Rackmore's Log on the wreck, north coast",1443}, o={30,8,"Find Rackmore's Silver and Golden Keys, then open Rackmore's Chest underwater at Ranazjar Isle; Underwater Breathing",1443}, r={30,8,"Rackmore's Chest",1443}},
      {lv=35},
    },
  },
  -- ============================================================ 35-40 Arathi / STV / Dustwallow
  {
    id="b8", lv={35,40}, name="Arathi, Stranglethorn tier two, Dustwallow", map=1417,
    hub="Hammerfall, Grom'gol, Brackenwall", hearth="Hammerfall, then Grom'gol at 37, then Brackenwall at 38", fp="Hammerfall, Brackenwall",
    steps={
      {tr=true, x=73, y=36, t="Fly Shadowprey to Orgrimmar, zeppelin to Undercity, fly to Tarren Mill, road east into Arathi. Hammerfall."},
      {bind="Hammerfall", x=73, y=36},
      {fp="Hammerfall", x=73, y=36},
      {q="Foul Magics", p=1, g={73,36,"Tor'gan"}, o={62,73,"Witherbark trolls at Witherbark Village"}},
      {q="Call to Arms", p=1, g={73,36,"Hammerfall"}, o={30,58,"Stromgarde Keep: humans outside the walls (35-38); the inner keep is elite"}},
      {man="Drum Fel's Boulderfist chain: ogres at Boulderfist Hall (73,68) and Boulder'gor (42,45).", x=73, y=68},
      {man="Circles of Binding: four stone circles in the corners of the zone, each a turn-in. Worth the walk (verify).", x=50, y=50},
      {lv=37},
      {tr=true, x=32, y=29, map=1434, t="Zeppelin Undercity to Grom'gol. Rebind."},
      {bind="Grom'gol", x=32, y=29, map=1434},
      {q="Panther Mastery", p=3, g={35,10,"Sir S. J. Erlgadin",1434}, o={38,30,"10 Elder Shadow Panthers",1434}},
      {q="Tiger Mastery", p=3, g={35,10,"Ajeck Rouack",1434}, o={35,30,"10 Elder Stranglethorn Tigers",1434}},
      {q="Raptor Mastery", p=3, g={35,10,"Barnil Stonepot",1434}, o={50,35,"10 Jungle Stalkers",1434}},
      {q="Panther Mastery", p=4, g={35,10,"Sir S. J. Erlgadin",1434}, o={46,26,"Bhag'thera (verify)",1434}},
      {q="Tiger Mastery", p=4, g={35,10,"Ajeck Rouack",1434}, o={37,27,"Sin'Dall (verify)",1434}},
      {q="Raptor Mastery", p=4, g={35,10,"Barnil Stonepot",1434}, o={40,17,"Tethis (verify)",1434}},
      {q="Split Bone Necklace", g={32,29,"Nimboya",1434}, o={55,42,"Skullsplitter trolls at the Ruins of Zul'Mamwe",1434}},
      {lv=38},
      {tr=true, x=36, y=31, map=1445, t="Zeppelin to Orgrimmar, fly to Brackenwall Village, Dustwallow."},
      {bind="Brackenwall", x=36, y=31, map=1445},
      {fp="Brackenwall", x=36, y=31, map=1445},
      {q="Theramore Spies", g={36,31,"Nazeer Bloodpike",1445}, o={55,30,"Theramore Infiltrators along the road east (verify)",1445}},
      {q="Hungry!", g={36,31,"Ogron",1445}, o={40,45,"Follow the quest text",1445}},
      {q="Jarl Needs Eyes", g={36,31,"Jarl",1445}, o={33,49,"Darkmist spiders in Darkmist Cavern",1445}},
      {q="The Brood of Onyxia", p=1, g={36,31,"Draz'Zilb",1445}, o={55,75,"Dragonkin at Wyrmbog; pull singles",1445}},
      {q="The Brood of Onyxia", p=2, g={36,31,"Draz'Zilb",1445}, o={55,75,"Wyrmbog",1445}},
      {q="Overlord Mok'Morokk's Concern", g={36,31,"Draz'Zilb",1445}, o={36,31,"Three items around Brackenwall; ends in a level-40 group fight with Mok'Morokk",1445}},
      {q="Stinky's Escape", opt=true, g={45,17,"Stinky Ignatz, north marsh",1445}, o={40,25,"Escort Stinky to the road",1445}, r={36,31,"Brackenwall",1445}},
      {forever=true, t="Riverdale, a new 35-45 zone east of Burning Steppes and the Badlands, may replace this Dustwallow leg."},
      {lv=40},
      {man="Buy Apprentice Riding (Velma Warnam) and the Skeletal Horse (Zachariah) in Brill. 100 gold before discounts.", x=61, y=52, map=1420},
    },
  },
  -- ============================================================ 40-45 Badlands / Swamp / STV
  {
    id="b9", lv={40,45}, name="Badlands, Swamp of Sorrows, Stranglethorn tier three", map=1418,
    hub="Kargath, then Stonard", hearth="Kargath, then Stonard at 42", fp="Kargath (Gorrik), Stonard (Breyk)",
    steps={
      {tr=true, x=3, y=47, t="Fly Undercity to Kargath."},
      {bind="Kargath", x=3, y=47},
      {fp="Kargath", x=3, y=47},
      {q="Broken Alliances", g={3,47,"Kargath"}, o={22,78,"Boss Tho'grun at the southern ogre camps (verify)"}},
      {q="Barbecued Buzzard Wings", g={42,53,"Rigglefuzz"}, o={45,50,"4 Buzzard Wings"}},
      {q="Study of the Elements: Rock", p=1, g={25,44,"Lotwil Veriatus (verify)"}, o={50,42,"Rock elementals"}},
      {q="Indurium", g={42,53,"Martek the Exiled"}, o={42,10,"Uldaman (group)"}},
      {q="Power Stones", opt=true, g={42,53,"Rigglefuzz"}, o={42,10,"Uldaman: 8 Dentrium, 8 An'Alleum Power Stones"}},
      {q="Solution to Doom", opt=true, g={52,43,"Theldurin the Lost"}, o={42,10,"Uldaman"}},
      {q="Reclaimed Treasures", opt=true, g={3,47,"Kargath"}, o={42,10,"Uldaman"}},
      {lv=42},
      {tr=true, x=46, y=56, map=1435, t="Fly to Stonard, Swamp of Sorrows."},
      {bind="Stonard", x=46, y=56, map=1435},
      {fp="Stonard", x=46, y=56, map=1435},
      {q="Pool of Tears", g={47,55,"Fel'zerul",1435}, o={68,58,"10 Atal'ai Artifacts underwater in the Pool of Tears",1435}},
      {q="The Atal'ai Exile", g={47,55,"Fel'zerul",1435}, r={33,75,"Atal'ai Exile, southern Hinterlands",1425}},
      {q="Return to Fel'Zerul", g={33,75,"Atal'ai Exile",1425}, r={47,55,"Fel'zerul",1435}},
      {q="Draenethyst Crystals", g={25,31,"Magtoor, Fallow Sanctuary",1435}, o={30,35,"Lost Ones around the sanctuary",1435}},
      {q="Noboru the Cudgel", g={46,56,"Stonard",1435}, o={65,55,"Noboru at the Misty Reed coast (verify)",1435}},
      {tr=true, x=32, y=29, map=1434, t="Zeppelin to Grom'gol for the last Stranglethorn layer."},
      {q="Big Game Hunter", g={35,10,"Hemet Nesingwary",1434}, o={40,17,"King Bangalash, level 43 elite; bring a partner (verify)",1434}},
      {q="The Bloodsail Buccaneers", p=1, g={27,77,"Baron Revilgaz, Booty Bay",1434}, o={32,88,"Bloodsail pirates at the Wild Shore (verify)",1434}},
      {q="Hearts of Zeal", opt=true, g={48,68,"Master Apothecary Faranell",UC}, o={85,32,"Scarlet Monastery: 20 Hearts of Zeal",1420}},
      {q="Into The Scarlet Monastery", opt=true, g={58,90,"Varimathras, Royal Quarter",UC}, o={85,32,"Scarlet Monastery: Doan, Herod, Mograine, Whitemane",1420}},
      {lv=45},
    },
  },
  -- ============================================================ 45-50 Tanaris / Feralas / Hinterlands / Searing Gorge
  {
    id="b10", lv={45,50}, name="Tanaris, Feralas, Hinterlands, Searing Gorge", map=1446,
    hub="Gadgetzan, Camp Mojache, Revantusk, Thorium Point", hearth="Gadgetzan, then Camp Mojache, then Revantusk", fp="Gadgetzan, Camp Mojache, Revantusk, Thorium Point",
    steps={
      {tr=true, x=51, y=28, t="Zeppelin to Orgrimmar, fly to Gadgetzan."},
      {bind="Gadgetzan", x=51, y=28},
      {fp="Gadgetzan", x=51, y=28},
      {q="Wastewander Justice", g={52,28,"Security Chief Bilgewhizzle"}, o={60,25,"Wastewander bandits and thieves at Waterspring Field"}},
      {q="Water Pouch Bounty", g={52,28,"Spigot Operator Luglunket"}, o={60,25,"Wastewander Water Pouches"}},
      {q="Thistleshrub Valley", g={51,26,"Tran'rek"}, o={30,65,"Thistleshrub Valley, south-west"}},
      {q="Gahz'ridian", g={52,45,"Marvon Rivetseeker, Broken Pillar"}, o={45,50,"Gahz'ridian ornaments with the detector (verify)"}},
      {q="Gadgetzan Water Survey", g={52,28,"Chief Engineer Bilgewhizzle"}, o={41,33,"Abyssal Sands"}},
      {q="Southsea Shakedown", g={52,28,"Security Chief Bilgewhizzle"}, o={72,45,"Southsea pirates at Lost Rigger Cove"}},
      {q="The Scrimshank Redemption", g={51,28,"Senior Surveyor Fizzledowser"}, o={41,33,"Scrimshank's Surveying Gear inside the Noxious Lair"}},
      {q="Screecher Spirits", g={66,22,"Yeh'kinya, Steamwheedle Port"}, o={50,35,"Screecher spirits with the Divination Scryer"}},
      {q="Divino-matic Rod", opt=true, g={52,28,"Chief Engineer Bilgewhizzle"}, o={39,20,"Zul'Farrak (44-54)"}},
      {q="Scarab Shells", opt=true, g={51,26,"Tran'rek"}, o={39,20,"Zul'Farrak"}},
      {q="The Prophecy of Mosh'aru", opt=true, g={66,22,"Yeh'kinya"}, o={39,20,"Zul'Farrak"}},
      {lv=47},
      {tr=true, x=75, y=44, map=1444, t="Fly to Camp Mojache, Feralas."},
      {bind="Camp Mojache", x=75, y=44, map=1444},
      {fp="Camp Mojache", x=75, y=44, map=1444},
      {q="The Ogres of Feralas", g={75,44,"Camp Mojache",1444}, o={68,38,"Gordunni ogres at Lariss Pavilion",1444}},
      {q="Gordunni Cobalt", g={75,44,"Camp Mojache",1444}, o={68,38,"Gordunni ogres",1444}},
      {q="The Gordunni Scroll", g={75,44,"Camp Mojache",1444}, o={68,38,"Gordunni ogres",1444}},
      {q="The Mark of Quality", g={75,44,"Hadoken Swiftstrider",1444}, o={55,50,"10 Thick Yeti Hides at Feral Scar Vale",1444}},
      {q="War on the Woodpaw", g={75,44,"Camp Mojache",1444}, o={70,55,"Woodpaw gnolls in the Woodpaw Hills (verify)",1444}},
      {q="Alpha Strike", g={75,44,"Camp Mojache",1444}, o={70,55,"Woodpaw Alphas (verify)",1444}},
      {q="Zukk'ash Infestation", g={75,44,"Witch Doctor Uzer'i",1444}, o={68,70,"Zukk'ash silithid at the Writhing Deep",1444}},
      {lv=48},
      {tr=true, x=79, y=79, map=1425, t="Fly Undercity to Revantusk Village, the Hinterlands."},
      {bind="Revantusk", x=79, y=79, map=1425},
      {fp="Revantusk", x=79, y=79, map=1425},
      {q="Snapjaws, Mon!", g={79,79,"Katoom the Angler",1425}, o={78,72,"Saltwater Snapjaws on the beach",1425}},
      {q="Gammerita, Mon!", g={79,79,"Katoom the Angler",1425}, o={78,58,"Gammerita walks the beach north; use the camera (verify)",1425}},
      {q="Vilebranch Hooligans", g={79,79,"Primal Torntusk",1425}, o={48,66,"Vilebranch trolls around the Altar of Zul",1425}},
      {q="Cannibalistic Cousins", g={79,79,"Primal Torntusk",1425}, o={48,66,"Vilebranch trolls (verify)",1425}},
      {tr=true, x=39, y=28, map=1427, t="Fly to Thorium Point, Searing Gorge."},
      {fp="Thorium Point", x=39, y=28, map=1427},
      {q="What the Flux?", g={38,28,"Master Smith Burninate",1427}, o={45,45,"Dark Iron in the Cauldron drop Flux (verify)",1427}},
      {q="Incendosaurs? Whateverosaur is More Like It", g={38,28,"Master Smith Burninate",1427}, o={45,45,"Incendosaur scales in the Cauldron",1427}},
      {q="Fiery Menace!", g={38,28,"Hansel Heavyhands",1427}, o={45,45,"Incendosaurs",1427}},
      {q="JOB OPPORTUNITY: Culling the Competition", g={39,28,"Poster, Thorium Point",1427}, o={42,47,"Dark Iron Lookouts in the Slag Pit (verify)",1427}},
      {q="STOLEN: Smithing Tuyere and Lookout's Spyglass", g={39,28,"Poster, Thorium Point",1427}, o={42,47,"Slag Pit (verify)",1427}},
      {q="Divine Retribution", g={38,28,"Kalaran Windblade",1427}, r={38,28,"Kalaran Windblade",1427}},
      {q="The Flawless Flame", g={38,28,"Kalaran Windblade",1427}, o={45,45,"Follow the quest text through the Cauldron (verify)",1427}},
      {lv=50},
    },
  },
  -- ============================================================ 50-55 Un'Goro / Felwood / Steppes / Azshara
  {
    id="b11", lv={50,55}, name="Un'Goro, Felwood, Burning Steppes, Azshara", map=1449,
    hub="Marshal's Refuge, Bloodvenom Post, Flame Crest, Valormok", hearth="Gadgetzan while in Un'Goro, then Flame Crest", fp="Bloodvenom Post, Flame Crest",
    steps={
      {tr=true, x=44, y=8, t="Ride into Un'Goro from Tanaris or Feralas (no Horde flight point). Marshal's Refuge."},
      {q="Crystals of Power", g={44,8,"J.D. Collie"}, o={45,25,"7 crystals of each color; pick up every one you see"}},
      {q="The Northern Pylon", g={44,8,"J.D. Collie"}, o={56,12,"Northern Pylon"}},
      {q="The Eastern Pylon", g={44,8,"J.D. Collie"}, o={77,50,"Eastern Pylon"}},
      {q="The Western Pylon", g={44,8,"J.D. Collie"}, o={23,60,"Western Pylon"}},
      {q="Beware of Pterrordax", g={44,8,"Spraggle Frock"}, o={55,40,"Pterrordax and Frenzied Pterrordax"}},
      {q="Lost!", g={44,8,"Spraggle Frock"}, o={51,45,"Find Ringo at Fire Plume Ridge"}, r={51,45,"Ringo"}},
      {q="A Little Help From My Friends", g={51,45,"Ringo"}, o={47,25,"Escort Ringo back to the Refuge; he faints, keep him up"}, r={44,8,"Spraggle Frock"}},
      {q="Williden's Journal", g={45,25,"Loot: the journal from a dirt pile or crate"}, r={44,8,"Williden Marshal"}},
      {q="Expedition Salvation", g={44,8,"Williden Marshal"}, o={45,25,"Expedition supplies from Un'Goro dirt piles"}},
      {q="Chasing A-Me 01", g={44,8,"Karna Remtravel"}, o={63,17,"A-Me 01 in Fungal Rock; watch the gorillas"}},
      {q="The Apes of Un'Goro", g={72,76,"Torwa Pathfinder (verify)"}, o={63,17,"Gorillas in Fungal Rock"}},
      {q="Volcanic Activity", g={50,44,"Krakle, Fire Plume Ridge (verify)"}, o={51,45,"Follow the quest text"}},
      {lv=52},
      {tr=true, x=35, y=52, map=1448, t="Fly Orgrimmar to Bloodvenom Post, Felwood."},
      {fp="Bloodvenom Post", x=35, y=52, map=1448},
      {q="Cleansing Felwood", g={51,82,"Eridan Bluewind, Emerald Sanctuary",1448}, r={51,82,"Emerald Sanctuary",1448}},
      {q="Timbermaw Ally", g={51,82,"Grazle, Emerald Sanctuary",1448}, o={48,93,"Deadwood furbolgs at Deadwood Village",1448}},
      {q="Speak to Nafien", g={51,82,"Grazle",1448}, r={65,8,"Nafien, Timbermaw Hold entrance",1448}},
      {q="Deadwood of the North", g={65,8,"Nafien",1448}, o={62,15,"Deadwood furbolgs at Felpaw Village; repeatable for rep",1448}},
      {lv=53},
      {tr=true, x=65, y=24, map=1428, t="Fly to Flame Crest, Burning Steppes."},
      {bind="Flame Crest", x=65, y=24, map=1428},
      {fp="Flame Crest", x=65, y=24, map=1428},
      {q="Broodling Essence", g={65,24,"Tinkee Steamboil",1428}, o={50,30,"Draco-Incarcinatrix on Broodlings at the Pillar of Ash (verify)",1428}},
      {q="Kibler's Exotic Pets", opt=true, g={65,24,"Kibler",1428}, o={40,50,"Lower Blackrock Spire",1428}},
      {tr=true, x=22, y=50, map=1447, t="Azshara any time in this bracket: ride from Orgrimmar to Valormok (no flight point)."},
      {q="Stealing Knowledge", g={22,50,"Jediga, Valormok",1447}, o={32,55,"Highborne tablets at the Ruins of Eldarath",1447}},
      {q="A Land Filled with Hatred", g={11,78,"Loh'atu, Ashenvale border",1447}, o={12,75,"6 Haldarr Satyrs, 2 Tricksters, 2 Felsworn at the Haldarr Encampment",1447}},
      {q="Betrayed", p=1, g={22,50,"Ag'tor Bloodfist",1447}, o={32,55,"Ruins of Eldarath",1447}},
      {q="Kim'jael Indeed!", g={23,61,"Kim'jael (verify)",1447}, o={46,44,"Kim'jael's equipment (verify)",1447}},
      {lv=55},
    },
  },
  -- ============================================================ 55-60 Plaguelands / Winterspring / Silithus
  {
    id="b12", lv={55,60}, name="Plaguelands, Winterspring, Silithus", map=1422,
    hub="The Bulwark, Light's Hope, Everlook, Cenarion Hold", hearth="Undercity for the Plaguelands, then Everlook", fp="The Bulwark, Light's Hope, Everlook, Cenarion Hold",
    steps={
      {tr=true, x=83, y=68, map=1420, t="Fly Flame Crest to Undercity, then to The Bulwark on the Tirisfal border. Bind in Undercity (no inn here)."},
      {fp="The Bulwark", x=83, y=68, map=1420},
      {q="Scarlet Diversions", g={83,68,"High Executor Derrington, The Bulwark",1420}, o={36,52,"Scarlet camp north of Felstone Field (verify)"}},
      {q="Mission Accomplished!", g={83,68,"High Executor Derrington",1420}, o={36,52,"Scarlet camp (verify)"}},
      {q="The Scourge Cauldrons", g={83,71,"Shadow Priestess Vandis, The Bulwark",1420}, r={83,71,"Shadow Priestess Vandis",1420}},
      {q="Target: Felstone Field", g={83,71,"Shadow Priestess Vandis",1420}, o={37,56,"Cauldron Lord Bilemaw at Felstone Field; use the key on the cauldron"}, r={37,56,"Felstone cauldron"}},
      {q="Return to the Bulwark", p=1, g={37,56,"Felstone cauldron"}, r={83,71,"Shadow Priestess Vandis",1420}},
      {q="Target: Dalson's Tears", g={83,71,"Shadow Priestess Vandis",1420}, o={46,51,"Cauldron Lord Malvinious at Dalson's Tears"}, r={46,51,"Dalson's cauldron"}},
      {q="Return to the Bulwark", p=2, g={46,51,"Dalson's cauldron"}, r={83,71,"Shadow Priestess Vandis",1420}},
      {q="Target: Writhing Haunt", g={83,71,"Shadow Priestess Vandis",1420}, o={53,65,"Cauldron Lord Razarch at the Writhing Haunt"}, r={53,65,"Writhing Haunt cauldron"}},
      {q="Return to the Bulwark", p=3, g={53,65,"Writhing Haunt cauldron"}, r={83,71,"Shadow Priestess Vandis",1420}},
      {q="Target: Gahrron's Withering", g={83,71,"Shadow Priestess Vandis",1420}, o={62,58,"Cauldron Lord Soulwrath at Gahrron's Withering"}, r={62,58,"Gahrron's cauldron"}},
      {q="Return to the Bulwark", p=4, g={62,58,"Gahrron's cauldron"}, r={83,71,"Shadow Priestess Vandis",1420}},
      {q="All Along the Watchtowers", g={83,68,"The Bulwark",1420}, o={45,68,"Plant the beacons on the four Andorhal towers (verify)"}},
      {q="Alas, Andorhal", opt=true, g={83,68,"The Bulwark",1420}, o={45,70,"Araj the Summoner, elite; group"}},
      {lv=57},
      {tr=true, x=81, y=59, map=1423, t="Ride east to Light's Hope Chapel, Eastern Plaguelands."},
      {fp="Light's Hope", x=81, y=59, map=1423},
      {q="Argent Dawn Commission", g={81,59,"Argent Officer Pureheart",1423}, r={81,59,"Argent Officer Pureheart",1423}},
      {q="Pamela's Doll", g={47,75,"Pamela Redpath, Darrowshire",1423}, o={46,75,"Doll pieces in the ruined houses",1423}},
      {q="Auntie Marlene", g={47,75,"Pamela Redpath",1423}, r={10,44,"Marlene Redpath, west of Darrowshire (verify)",1423}},
      {q="A Strange Historian", g={10,44,"Marlene Redpath",1423}, r={39,66,"Chromie, Andorhal inn (verify)",1422}},
      {q="Villains of Darrowshire", g={81,59,"Carlin Redpath, Light's Hope",1423}, o={55,45,"Horgus the Ravager and Marduk Blackpool (verify)",1423}},
      {q="Hidden Treasures", g={81,59,"Carlin Redpath",1423}, o={47,75,"Joseph's Chest in Darrowshire",1423}},
      {q="Marauders of Darrowshire", g={81,59,"Carlin Redpath",1423}, o={50,60,"Follow the quest text (verify)",1423}},
      {q="Un-Life's Little Annoyances", g={81,59,"Lord Maxwell Tyrosus",1423}, o={55,55,"Plaguebats and Plaguehounds (verify)",1423}},
      {q="The Ranger Lord's Behest", g={58,90,"Varimathras, Royal Quarter",UC}, r={26,74,"Nathanos Blightcaller, Marris Stead",1423}},
      {q="Duskwing, Oh How I Hate Thee...", opt=true, g={26,74,"Nathanos Blightcaller",1423}, o={44,52,"Duskwing, elite bat (verify)",1423}},
      {lv=58},
      {tr=true, x=60, y=50, map=1452, t="Fly to Everlook, Winterspring."},
      {bind="Everlook", x=60, y=50, map=1452},
      {fp="Everlook", x=60, y=50, map=1452},
      {q="Threat of the Winterfall", g={54,35,"Donova Snowden",1452}, o={67,37,"Winterfall furbolgs at Winterfall Village",1452}},
      {q="Winterfall Activity", g={54,35,"Donova Snowden",1452}, o={67,37,"Winterfall Village",1452}},
      {q="Winterfall Runners", g={54,35,"Donova Snowden",1452}, o={68,32,"Runners on the road north of the village (verify)",1452}},
      {q="Are We There, Yeti?", p=1, g={61,38,"Umi Thorson, Everlook",1452}, o={68,55,"Ice Thistle yetis (verify)",1452}},
      {tr=true, x=50, y=40, map=1451, t="Silithus for the last bars: fly to Cenarion Hold."},
      {fp="Cenarion Hold", x=50, y=40, map=1451},
      {q="Wanted - Deathclasp, Terror of the Sands", opt=true, g={51,38,"Wanted poster, Cenarion Hold",1451}, o={52,58,"Deathclasp roams the south (verify)",1451}, r={50,33,"Vish Kozus, Cenarion Hold",1451}},
      {man="Dungeons for the finish: Blackrock Depths, Lower Blackrock Spire, Dire Maul, Scholomance, Stratholme. One Stratholme clear is most of a level at 59.", x=27, y=12, map=1423},
      {forever=true, t="Mount Hyjal is the new 60 zone and two new 10-20 player raids come with launch. The cap is permanent."},
      {lv=60},
    },
  },
}

ns.RACIALS = {
  {"Will of the Forsaken", "Removes Charm, Fear and Sleep. Era: 5 s immunity. Forever: no immunity window."},
  {"Cannibalize", "Eat a Humanoid or Undead corpse: 7% health per 2 s for 10 s. Forever: also 7% mana per tick."},
  {"Underwater Breathing", "Breath lasts 300% longer. Do the water quests other races skip."},
  {"Shadow Resistance / Touch of the Grave", "Era: +10 shadow resistance. Forever: chance to drain health on hit."},
}

-- ------------------------------------------------------------------ route registry
-- A route is picked automatically by race, then faction. raceOnly = number of leading
-- brackets that only make sense for the listed races (their starting-zone chapters);
-- other races of the same faction join the route at the bracket after that.
ns.ROUTES = {
  {
    id = "forsaken", name = "The Forsaken Road", faction = "Horde",
    races = { Scourge = true }, raceOnly = 3,
    brackets = ns.BRACKETS,
  },
}
-- Other routes live in Routes_<Race>.lua (listed after this file in the TOC) and append to ns.ROUTES.

-- Active racial abilities to show in the footer, by race file name. Each entry lists
-- candidate spell ids (they differ by class or client build); the first one the character
-- actually knows is displayed.
ns.RACIAL_SPELLS = {
  Scourge  = { { "Cannibalize", 20577 }, { "WotF", 7744 } },
  Orc      = { { "Blood Fury", 20572, 33697, 33702 } },
  Troll    = { { "Berserking", 20554, 26296, 26297 } },
  Tauren   = { { "War Stomp", 20549 } },
  Human    = { { "Perception", 20600 } },
  Dwarf    = { { "Stoneform", 20594 } },
  NightElf = { { "Shadowmeld", 20580, 58984 } },
  Gnome    = { { "Escape Artist", 20589 } },
}
