-- Evergreen route: Tauren ("The Long Walk"). Loaded after Data.lua; appends to ns.ROUTES.
-- Step format is documented at the top of Data.lua. Class steps carry cls="DRUID" etc.
local ADDON, ns = ...

-- ================================================================== Tauren route: The Long Walk
-- Five race-only brackets (Mulgore x2, Barrens, Stonetalon/Ashenvale, Thousand Needles), then the
-- shared Horde brackets from 30 on. Class steps carry cls=.
local MUL, BAR, STM, ASH, TN, DUR, TB, MG = 1412, 1413, 1442, 1440, 1441, 1411, 1456, 1450
local TB_ELDER = {76,27,"Turak Runetotem, Elder Rise, Thunder Bluff",TB}
local TB_SPIRIT = {22,20,"Xanis Flameweaver, Spirit Rise, Thunder Bluff",TB}
local TB_HUNTER = {57,89,"Hunter Rise, Thunder Bluff",TB}
local MG_DENDRITE = {56,30,"Dendrite Starblaze, Nighthaven, Moonglade",MG}

ns.TAUREN_BRACKETS = {
  -- ============================================================ 1-6 Red Cloud Mesa
  {
    id="t1", lv={1,6}, name="Red Cloud Mesa", map=MUL,
    hub="Camp Narache", hearth="Already bound to Camp Narache", fp="None",
    steps={
      {note="Before you move", t="Turn on Auto Loot. Bind a key to War Stomp. All four class trainers stand around the camp; the scroll you spawn with is a free turn-in there."},
      {q="The Hunt Begins", g={45,77,"Grull Hawkwind, Camp Narache"}, o={48,79,"7 Plainstrider Meat, 7 Plainstrider Feathers from the plainstriders around camp"}},
      {q="A Humble Task", p=1, g={44,76,"Chief Hawkwind, the big hut"}, r={50,81,"Greatmother Hawkwind at the well"}},
      {q="A Humble Task", p=2, g={50,81,"Greatmother Hawkwind"}, o={50,81,"Loot the Water Pitcher from the well beside her"}, r={44,76,"Chief Hawkwind"}},
      {q="Rites of the Earthmother", p=1, g={44,76,"Chief Hawkwind"}, r={42,92,"Seer Graytongue, hut in the hills south-west"}},
      {q="The Hunt Continues", g={45,77,"Grull Hawkwind"}, o={42,92,"10 Mountain Cougar Pelts in the hills south"}},
      {q="Rite of Strength", g={42,92,"Seer Graytongue"}, o={62,78,"12 Bristleback Belts from the quilboar in Brambleblade Ravine (cave entrance 58,85)"}},
      {q="Call of Earth", p=1, cls="SHAMAN", g={45,75,"Seer Ravenfeather, Camp Narache"}, o={59,77,"2 Ritual Salve from Bristleback Shamans at the back of the ravine camps"}},
      {q="Call of Earth", p=2, cls="SHAMAN", g={45,75,"Seer Ravenfeather"}, o={54,80,"Drink the Earth Sapta at Kodo Rock, the dirt patch between camp and the ravine; talk to the Minor Manifestation of Earth"}, r={54,80,"Minor Manifestation of Earth"}},
      {q="Call of Earth", p=3, cls="SHAMAN", g={54,80,"Minor Manifestation of Earth"}, r={45,75,"Seer Ravenfeather: Earth Totem, Stoneskin Totem"}},
      {q="The Battleboars", g={45,77,"Grull Hawkwind"}, o={59,84,"8 Battleboar Snouts, 8 Battleboar Flanks in the mouth of Brambleblade Ravine"}},
      {q="Break Sharptusk!", g={45,77,"Brave Windfeather, by the camp fire"}, o={62,78,"Chief Sharptusk Thornmantle in the big tent; loot his head"}},
      {q="Attack on Camp Narache", g={60,82,"Dirt-stained Map on the ravine cave floor"}, r={44,76,"Chief Hawkwind"}},
      {q="Rites of the Earthmother", p=2, g={44,76,"Chief Hawkwind"}, r={48,60,"Baine Bloodhoof, Bloodhoof Village"}},
      {q="A Task Unfinished", g={46,73,"Antur Fallow, on the road out of camp"}, r={47,61,"Innkeeper Kauth, Bloodhoof Village"}},
      {forever=true, t="Nothing announced touches Red Cloud Mesa. Plainsrunning should be active from level 1."},
      {lv=6},
    },
  },
  -- ============================================================ 6-12 Bloodhoof Village
  {
    id="t2", lv={6,12}, name="Bloodhoof Village & Mulgore", map=MUL,
    hub="Bloodhoof Village", hearth="Bloodhoof inn (Innkeeper Kauth)", fp="None here; Thunder Bluff (Tal) at 10",
    steps={
      {tr=true, x=48, y=59, t="North on the road out of the mesa into Bloodhoof Village."},
      {bind="Bloodhoof", x=47, y=61},
      {note="Pickup sweep", t="Baine in the big tent, Mull Thunderhorn, Harken Windtotem, Ruul Eagletalon, Maur Raincaller, Zarlman Two-Moons, and Morin Cloudstalker on the road east. Learn First Aid (Vira Younghoof), Skinning and Herbalism. Skip Kyle's Gone Missing!: not in Era."},
      {q="Rite of Vision", p=1, g={48,60,"Baine Bloodhoof"}, r={48,58,"Zarlman Two-Moons"}},
      {q="Poison Water", g={49,60,"Mull Thunderhorn"}, o={46,66,"6 Prairie Wolf Paws, 4 Plainstrider Talons south and west of the village"}},
      {q="Swoop Hunting", g={49,59,"Harken Windtotem"}, o={44,62,"8 Trophy Swoop Quills from Swoops around the village"}},
      {q="Mazzranache", g={47,57,"Maur Raincaller"}, o={45,64,"A Prairie Wolf Heart, Swoop Gizzard, Plainstrider Scale and Flatland Cougar Femur as they drop (verify)"}},
      {q="Sharing the Land", g={48,60,"Baine Bloodhoof"}, o={35,64,"10 Palemane Tanners, 8 Palemane Skinners at Palemane Rock; 5 Poachers at the small camp east of the village"}},
      {q="Winterhoof Cleansing", g={49,60,"Mull Thunderhorn"}, o={53,66,"Kill the Venture Co. goblins at Winterhoof Water Well, use the totem at the water"}},
      {q="Dangers of the Windfury", g={47,62,"Ruul Eagletalon"}, o={62,70,"8 Windfury Talons from the harpies south-east"}},
      {q="Thunderhorn Totem", g={49,60,"Mull Thunderhorn"}, o={47,50,"Prairie Stalkers and Flatland Cougars, central Mulgore"}},
      {q="Dwarven Digging", g={48,60,"Baine Bloodhoof"}, o={34,47,"5 Prospector's Picks from the dwarves at the Bael'dun Digsite; break them at the Thunder Bluff forge"}},
      {lv=8},
      {q="Rite of Vision", p=2, g={48,58,"Zarlman Two-Moons"}, o={32,36,"Use the Water of the Seers at the Tribal Fire, follow the ghost wolf to the cave north-west"}, r={32,36,"Seer Wiserunner, in the cave"}},
      {q="Rite of Wisdom", g={32,36,"Seer Wiserunner"}, r={61,21,"Ancestral Spirit at Red Rocks"}},
      {q="Thunderhorn Cleansing", g={49,60,"Mull Thunderhorn"}, o={44,46,"Thunderhorn Water Well"}},
      {q="A Sacred Burial", g={59,25,"Lorekeeper Raintotem, Red Rocks"}, o={60,22,"8 Bristleback Interlopers around Red Rocks"}},
      {q="Journey into Thunder Bluff", g={61,21,"Ancestral Spirit, Red Rocks"}, r={60,52,"Cairne Bloodhoof, High Rise, Thunder Bluff",TB}},
      {lv=10},
      {tr=true, x=46, y=50, map=TB, any=true, t="Level 10: Thunder Bluff. Train, learn professions, get the flight point from Tal on the Wind Rider Roost. Break the picks at the forge on the lower rise (40,56)."},
      {fp="Thunder Bluff", x=46, y=50, map=TB},
      {q="Preparation for Ceremony", g={42,60,"Eyahn Eagletalon, lower rise, Thunder Bluff",TB}, o={51,10,"6 Azure Feathers, 6 Bronze Feathers from Windfury harpies at Windfury Ridge, north Mulgore"}},
      {q="The Barrens Oases", g={78,29,"Archdruid Hamuul Runetotem, Elder Rise",TB}, r={52,30,"Tonga Runetotem, the Crossroads",BAR}},
      {q="The Hunter's Way", g={57,88,"Melor Stonehoof, Hunter Rise",TB}, r={52,31,"Sergra Darkthorn, the Crossroads",BAR}},
      {q="Veteran Uzzek", cls="WARRIOR", g={47,60,"Krang Stonehoof, Bloodhoof warrior trainer"}, r={62,31,"Uzzek, under a tree south-west of Far Watch Post (verify)",BAR}},
      {q="The Hunter's Path", cls="HUNTER", g={45,75,"Lanka Farshot, Camp Narache (or Kary Thunderhorn, Thunder Bluff)"}, r={47,57,"Yaw Sharpmane, north edge of Bloodhoof Village"}},
      {q="Taming the Beast", p=1, cls="HUNTER", g={47,57,"Yaw Sharpmane"}, o={49,63,"Use the Taming Rod on an Adult Plainstrider around Stonebull Lake"}},
      {q="Taming the Beast", p=2, cls="HUNTER", g={47,57,"Yaw Sharpmane"}, o={43,55,"Tame a Prairie Stalker, the wolves west and north of the village"}},
      {q="Taming the Beast", p=3, cls="HUNTER", g={47,57,"Yaw Sharpmane"}, o={47,40,"Tame a Swoop toward Windfury Ridge. Reward: Tame Beast, Call Pet, Dismiss Pet"}},
      {q="Training the Beast", cls="HUNTER", g={47,57,"Yaw Sharpmane"}, r={57,89,"Holt Thunderhorn, Hunter Rise, Thunder Bluff",TB}},
      {q="Call of Fire", p=1, cls="SHAMAN", g=TB_SPIRIT, r={56,20,"Kranal Fiss, Grol'dom Farm north of the Crossroads (verify)",BAR}},
      {q="Heeding the Call", cls="DRUID", g={47,60,"Gennia Runetotem, Bloodhoof druid trainer"}, r=TB_ELDER},
      {q="Moonglade", cls="DRUID", g=TB_ELDER, r=MG_DENDRITE},
      {q="Great Bear Spirit", cls="DRUID", g=MG_DENDRITE, o={39,27,"Talk to the Great Bear Spirit west along the mountains, finish its dialogue",MG}, r=MG_DENDRITE},
      {q="Back to Thunder Bluff", cls="DRUID", g=MG_DENDRITE, r=TB_ELDER},
      {q="Wildmane Totem", g={49,60,"Mull Thunderhorn"}, o={52,18,"Flatland Prowler claws, north Mulgore"}},
      {q="Wildmane Cleansing", g={49,60,"Mull Thunderhorn"}, o={43,13,"Wildmane Water Well, north of Thunder Bluff"}},
      {q="The Ravaged Caravan", p=1, g={57,60,"Morin Cloudstalker, road east of the village"}, o={54,48,"Open the Sealed Supply Crate at the caravan ruins north"}},
      {q="The Ravaged Caravan", p=2, g={54,48,"Sealed Supply Crate"}, r={57,60,"Morin Cloudstalker"}},
      {q="The Venture Co.", g={57,60,"Morin Cloudstalker"}, o={62,47,"14 Venture Co. Workers, 6 Supervisors in the Venture Co. Mine"}},
      {q="Supervisor Fizsprocket", g={57,60,"Morin Cloudstalker"}, o={62,47,"Fizsprocket at the bottom of the mine; loot his clipboard"}},
      {forever=true, t="No source reports Mulgore changes. Shen'Dralas opens off Desolace, not Mulgore."},
      {lv=12},
    },
  },
  -- ============================================================ 12-20 The Barrens
  {
    id="t3", lv={12,20}, name="The Barrens", map=BAR,
    hub="Camp Taurajo, the Crossroads, Ratchet", hearth="Crossroads (Boorand Plainswind), then Camp Taurajo (Byula) at 16", fp="Camp Taurajo, Crossroads, Ratchet",
    steps={
      {tr=true, x=44, y=59, t="Out through the Great Gate (71,61 Mulgore) onto the road; Camp Taurajo is first."},
      {fp="Camp Taurajo", x=44, y=59},
      {q="Journey to the Crossroads", g={44,59,"Kirge Sternhorn, Camp Taurajo"}, r={51,30,"Thork, the Crossroads"}},
      {q="Body and Heart", cls="DRUID", g=TB_ELDER, o={42,60,"Moonkin Stone west of Camp Taurajo (verify): Lunardust, Lunaclaw"}, r=TB_ELDER},
      {bind="Crossroads", x=52, y=30},
      {fp="Crossroads", x=51, y=30},
      {q="Plainstrider Menace", g={52,31,"Sergra Darkthorn"}, o={50,35,"7 Plainstrider Beaks around town"}},
      {q="The Zhevra", g={52,31,"Sergra Darkthorn"}, o={49,37,"4 Zhevra Hooves south and west"}},
      {q="Disrupt the Attacks", g={51,30,"Thork"}, o={58,25,"8 Razormane Water Seekers, 8 Thornweavers, 3 Hunters at Thorn Hill"}},
      {q="Supplies for the Crossroads", g={51,30,"Thork"}, o={47,29,"5 Crossroads Supply Crates at the wrecked caravans"}},
      {q="Raptor Thieves", g={51,30,"Gazrog"}, o={56,36,"12 Raptor Heads south-east of town"}},
      {q="Fungal Spores", g={51,30,"Apothecary Helbrim"}, o={45,30,"8 Fungal Spores from the beasts at the Forgotten Pools"}},
      {q="The Forgotten Pools", g={52,30,"Tonga Runetotem"}, o={45,30,"Visit the Forgotten Pools north-west"}},
      {q="Centaur Bracers", g={45,28,"Regthar Deathgate, bunker west of town"}, o={44,31,"15 Centaur Bracers from Kolkar centaur around the Forgotten Pools"}},
      {q="Kolkar Leaders", g={45,28,"Regthar Deathgate"}, o={43,30,"Barak Kodobane (16 elite) west of the pools; pull him alone"}},
      {q="Path of Defense", cls="WARRIOR", g={62,31,"Uzzek, Far Watch Post (verify)"}, o={39,32,"5 Singed Scales from thunder lizards at Thunder Ridge, across the bridge into Durotar",DUR}, r={62,31,"Uzzek: Defensive Stance, Sunder Armor, Taunt"}},
      {q="Thun'grim Firegaze", cls="WARRIOR", g={62,31,"Uzzek"}, r={57,30,"Thun'grim Firegaze, top of Thorn Hill (path up from 55,32)"}},
      {q="Forged Steel", cls="WARRIOR", g={57,30,"Thun'grim Firegaze"}, o={55,26,"Stolen Iron Chest by the broken wagon north-west, guarded by quilboar"}, r={57,30,"Thun'grim: pick a weapon"}},
      {q="Call of Fire", p=2, cls="SHAMAN", g={56,20,"Kranal Fiss, Grol'dom Farm (verify)"}, r={37,58,"Telf Joolam, Shrine of the Dormant Flame, mountain north-west of the Valley of Trials (verify)",DUR}},
      {q="Call of Fire", p=3, cls="SHAMAN", g={37,58,"Telf Joolam",DUR}, o={55,33,"1 Fire Tar from Razormane Mystics/Geomancers; 1 Reagent Pouch from Burning Blade Cultists in the coven cave south-west of Razor Hill, Durotar"}, r={37,58,"Telf Joolam",DUR}},
      {q="Call of Fire", p=4, cls="SHAMAN", g={37,58,"Telf Joolam",DUR}, o={37,58,"Click the brazier, drink the Fire Sapta, kill the Minor Manifestation of Fire, loot the Torch",DUR}, r={37,58,"Telf Joolam",DUR}},
      {q="Call of Fire", p=5, cls="SHAMAN", g={37,58,"Telf Joolam",DUR}, r={37,58,"Telf Joolam: Fire Totem, Searing Totem",DUR}},
      {q="Prowlers of the Barrens", g={52,31,"Sergra Darkthorn"}, o={60,35,"7 Savannah Prowler claws east toward Ratchet"}},
      {tr=true, x=63, y=37, t="Ratchet."},
      {fp="Ratchet", x=63, y=37},
      {q="Southsea Freebooters", g={62,37,"Gazlowe"}, o={68,45,"Southsea pirates on the coast south of Ratchet"}},
      {q="Samophlange", p=1, g={62,37,"Sputtervalve"}, r={63,30,"Wenikee Boltbucket, road north of Ratchet"}},
      {q="Raptor Horns", g={62,37,"Mebok Mizzyrix"}, o={60,45,"Sunscale raptors south of Ratchet"}},
      {q="The Guns of Northwatch", opt=true, g={63,37,"Captain Thalo'thas Brightsun, Ratchet"}, o={60,55,"Northwatch Hold, south along the coast (do it at 18)"}},
      {q="Lost in Battle", g={51,30,"Mankrik"}, o={51,50,"The Beaten Corpse south of the road, not in the hills"}},
      {lv=14},
      {q="Lessons Anew", cls="DRUID", g=TB_ELDER, r=MG_DENDRITE},
      {q="The Principal Source", cls="DRUID", g=MG_DENDRITE, o={47,20,"Fill the sampler at the pool on top of Dreadmist Peak, north-west of the Crossroads (verify)"}, r={52,30,"Tonga Runetotem, the Crossroads"}},
      {q="Gathering the Cure", cls="DRUID", g={52,30,"Tonga Runetotem"}, o={50,22,"5 Earthroot, 5 Kodo Horns from Lost Barrens Kodos north of town"}},
      {q="Curing the Sick", cls="DRUID", g={52,30,"Tonga Runetotem"}, o={55,32,"Use the salve on 10 Sickly Gazelles along the east-west road"}, r=MG_DENDRITE},
      {q="Power over Poison", cls="DRUID", g=MG_DENDRITE, r=TB_ELDER},
      {q="Samophlange", p=2, g={63,30,"Wenikee Boltbucket"}, o={52,12,"Control Console at the Sludge Fen: turn the three valves, then Tinkerer Sniggles in the hut at 53,11"}},
      {q="Echeyakee", g={52,31,"Sergra Darkthorn"}, o={55,16,"Blow the horn at the den; kill the white lion"}},
      {q="The Disruption Ends", g={51,30,"Thork"}, o={58,24,"Kreenig Snarlsnout at the Razormane camp"}},
      {q="Harpy Raiders", g={52,30,"Darsok Swiftdagger"}, o={43,15,"Witchwing harpies at the Dry Hills"}},
      {q="Harpy Lieutenants", g={52,30,"Darsok Swiftdagger"}, o={43,13,"Witchwing Slayers and Roguefeathers at the Dry Hills"}},
      {lv=16},
      {q="A Lesson to Learn", cls="DRUID", g=TB_ELDER, r=MG_DENDRITE},
      {q="Trial of the Lake", cls="DRUID", g=MG_DENDRITE, o={52,40,"Shrine Bauble from the bottom of Lake Elune'ara; use it at the Shrine of Remulos (36,41), talk to Tajarri. 30 minutes",MG}, r={36,40,"Tajarri, Shrine of Remulos",MG}},
      {q="Trial of the Sea Lion", cls="DRUID", g={36,40,"Tajarri",MG}, o={57,8,"Lockbox underwater at the Sludge Fen; the other is on the sea floor west of the derelict boat at North Tide's Run, Silverpine (30,30). Combine at the shrine"}, r=MG_DENDRITE},
      {q="Aquatic Form", cls="DRUID", g=MG_DENDRITE, r=TB_ELDER},
      {q="The Stagnant Oasis", g={52,30,"Tonga Runetotem"}, o={55,42,"Use the Bubbly Fissure at the Stagnant Oasis"}},
      {q="Altered Beings", g={52,30,"Tonga Runetotem"}, o={55,42,"6 Altered Snapjaw Shells at the Stagnant Oasis"}},
      {q="Verog the Dervish", g={45,28,"Regthar Deathgate"}, o={53,41,"Kill Kolkar at the Stagnant Oasis until Verog spawns; grind Bloodchargers here to 16"}},
      {bind="Taurajo", x=44, y=59},
      {q="Report to Kadrak", g={51,30,"Thork"}, r={48,5,"Kadrak at the Ashenvale road, Mor'shan Rampart"}},
      {q="The Warsong Reports", g={48,5,"Kadrak"}, o={73,61,"Deliver to Splintertree Post, the Satyrnaar patrol and Zoram'gar in Ashenvale; collect all three flight points",ASH}, r={48,5,"Kadrak"}},
      {q="Samophlange", p=3, g={50,11,"Wenikee Boltbucket, Mor'shan Rampart"}, o={57,9,"Sludge Fen: Supervisor Lugwizzle and the shredder"}},
      {q="Avenge My Village", g={81,88,"Camp Aparaje, Stonetalon border"}, o={81,88,"8 Grimtotem Ruffians, 6 Grimtotem Mercenaries around the camp"}},
      {q="Kill Grundig Darkcloud", g={81,88,"Camp Aparaje"}, o={80,87,"Grundig Darkcloud in the camp"}},
      {q="Blood Feeders", g={71,95,"Malaka'jin"}, o={57,76,"10 Deepmoss Creepers, 7 Venomspitters in Sishir Canyon, Stonetalon",STM}},
      {fp="Sun Rock", x=47, y=64, map=STM},
      {lv=18},
      {q="Enraged Thunder Lizards", g={44,59,"Jorn Skyseer, Camp Taurajo"}, o={48,64,"3 Thunder Lizard Blood south of camp"}},
      {q="Tribes at War", g={44,60,"Mangletooth, caged in Camp Taurajo"}, o={44,51,"6 Water Seekers, 12 Thornweavers, 12 Geomancers at the Bristleback camps north of camp"}},
      {q="Free From the Hold", g={59,55,"Gilthares Firebough, Northwatch Hold"}, o={63,37,"Escort him to Ratchet"}, r={63,37,"Ratchet"}},
      {q="Ishamuhale", g={52,31,"Sergra Darkthorn"}, o={59,30,"Ishamuhale at the dead tree"}},
      {q="Lakota'mani", g={44,59,"Camp Taurajo"}, o={46,50,"Lakota'mani north of camp"}},
      {q="Speak with Ruga", cls="WARRIOR", g={57,87,"Torm Ragetotem, Hunter Rise, Thunder Bluff",TB}, r={44,59,"Ruga Ragetotem, Camp Taurajo (verify)"}},
      {q="Trial at the Field of Giants", cls="WARRIOR", g={44,59,"Ruga Ragetotem"}, o={48,80,"5 Twitching Antennae from silithids in the Field of Giants; 30 minutes from the first drop"}, r={44,59,"Ruga: Ruga's Bulwark"}},
      {q="Speak with Thun'grim", cls="WARRIOR", g={44,59,"Ruga Ragetotem"}, r={57,30,"Thun'grim Firegaze, Thorn Hill"}},
      {q="Call of Water", p=1, cls="SHAMAN", g=TB_SPIRIT, r={66,44,"Islen Waterseer, hut on the coast south of Ratchet (verify)"}},
      {q="Call of Water", p=2, cls="SHAMAN", g={66,44,"Islen Waterseer"}, r={43,77,"Brine, hill at the north end of Blackthorn Ridge"}},
      {q="Deviate Hides", opt=true, g={46,36,"Nalpak, outside Wailing Caverns"}, o={46,36,"Wailing Caverns"}},
      {q="Trouble at the Docks", opt=true, g={63,37,"Crane Operator Bigglefuzz"}, o={46,36,"Mad Magglish inside Wailing Caverns"}},
      {forever=true, t="Shen'Dralas is confirmed between Mulgore and Desolace with no level range yet. If it turns out to be 15-25 it slots in here."},
      {lv=20},
    },
  },
  -- ============================================================ 20-25 Stonetalon, Ashenvale
  {
    id="t4", lv={20,25}, name="Stonetalon, then Ashenvale", map=STM,
    hub="Sun Rock Retreat, Splintertree Post, Zoram'gar", hearth="Sun Rock (Innkeeper Jayka), then Splintertree (Kaylisk) at 22", fp="Sun Rock, Splintertree, Zoram'gar",
    steps={
      {tr=true, x=47, y=64, t="Fly Camp Taurajo to Sun Rock Retreat."},
      {bind="Sun Rock", x=47, y=64},
      {q="Ziz Fizziks", g={62,37,"Sputtervalve, Ratchet",BAR}, r={59,62,"Ziz Fizziks, Windshear Crag"}},
      {q="Deepmoss Spider Eggs", g={62,37,"Mebok Mizzyrix, Ratchet",BAR}, o={57,76,"15 Deepmoss Spider Eggs in Sishir Canyon and Windshear Crag"}},
      {q="Boulderslide Ravine", g={47,64,"Mor'rogal, Sun Rock"}, o={62,91,"10 Resonite Crystals from the kobold cave. Warriors: loot the Smoky Iron Ingots for Brutal Armor"}},
      {q="Cycle of Rebirth", g={47,64,"Tammra Windfield, Sun Rock"}, o={50,52,"10 Gaea Seeds at Mirkfallon Lake"}},
      {q="Super Reaper 6000", g={59,62,"Ziz Fizziks, Windshear Crag"}, o={60,58,"15 Venture Co. Loggers for the blueprints"}},
      {q="Further Instructions", g={59,62,"Ziz Fizziks"}, r={62,37,"Sputtervalve, Ratchet",BAR}},
      {q="Gerenzo's Orders", g={61,55,"Piznik, Windshear Mine"}, o={61,55,"Gerenzo Wrenchwhistle in the mine (verify)"}},
      {lv=22},
      {tr=true, x=73, y=61, map=ASH, t="Fly Sun Rock to Splintertree Post. Rebind."},
      {bind="Splintertree", x=73, y=61, map=ASH},
      {q="The Ashenvale Hunt", g={73,61,"Senani Thunderheart, Splintertree",ASH}, r={73,61,"Senani Thunderheart",ASH}},
      {q="Ashenvale Outrunners", g={73,61,"Kuray'bin, Splintertree",ASH}, o={65,62,"9 stealthed Ashenvale Outrunners on the road west",ASH}},
      {q="Satyr Horns", g={73,61,"Pixel, Splintertree",ASH}, o={66,56,"Satyrs at Night Run",ASH}},
      {q="Stonetalon Standstill", g={73,61,"Mastok Wrilehiss, Splintertree",ASH}, o={58,57,"Silverwing Sentinels around the Laughing Sisters (verify)",ASH}},
      {q="Warsong Supplies", opt=true, g={73,61,"Locke Okarr, Splintertree",ASH}, o={27,77,"The Warsong Axe Shipment near the Booty Bay docks (do it at 30)",1434}},
      {q="Torek's Assault", g={73,61,"Torek, Splintertree",ASH}, o={66,73,"Clear Silverwing Outpost, then start the escort",ASH}},
      {q="Ursangous's Paw", g={73,61,"Senani Thunderheart",ASH}, o={40,65,"Ursangous the bear",ASH}},
      {q="Shadumbra's Head", g={73,61,"Senani Thunderheart",ASH}, o={58,55,"Shadumbra at the Laughing Sisters",ASH}},
      {q="Sharptalon's Claw", g={73,61,"Senani Thunderheart",ASH}, o={75,71,"Sharptalon (31) at the Forsaken camp; pull him to the guards",ASH}},
      {tr=true, x=12, y=34, map=ASH, t="Fly to Zoram'gar Outpost."},
      {fp="Zoram'gar", x=12, y=34, map=ASH},
      {q="Naga at the Zoram Strand", g={12,34,"Marukai, Zoram'gar",ASH}, o={14,25,"20 Wrathtail Heads on the strand; grind here to 23",ASH}},
      {q="Vorsha the Lasher", g={12,34,"Muglash, Zoram'gar",ASH}, o={11,30,"Escort Muglash, three naga waves, then Vorsha",ASH}},
      {q="Between a Rock and a Thistlefur", g={12,34,"Karang Amakkar, Zoram'gar",ASH}, o={30,45,"Thistlefur Village furbolgs",ASH}},
      {q="Troll Charm", g={12,34,"Mitsuwa, Zoram'gar",ASH}, o={30,45,"8 Troll Charms from chests in Thistlefur Village",ASH}},
      {q="Je'neu of the Earthen Ring", g={12,34,"Je'neu Sancrea, Zoram'gar",ASH}, o={52,70,"12 Befouled Water Elementals at Mystral Lake, then Tideress for the globe",ASH}},
      {q="Call of Water", p=3, cls="SHAMAN", g={43,77,"Brine, Blackthorn Ridge",BAR}, o={33,67,"Blue skin at the Ruins of Stardust fountain, south-west Ashenvale; Brown at the pond below Brine; Red at the Tarren Mill well (Hillsbrad 62,20)",ASH}, r={43,77,"Brine",BAR}},
      {q="Call of Water", p=4, cls="SHAMAN", g={43,77,"Brine",BAR}, r={66,44,"Islen Waterseer, south of Ratchet",BAR}},
      {q="Call of Water", p=5, cls="SHAMAN", g={66,44,"Islen Waterseer",BAR}, o={38,45,"Brazier of Everfount, Silverpine coast west of the Sepulcher: drink the Water Sapta, kill the Corrupt Manifestation, place its bracers on the brazier, take the Shard of Water",1421}, r={38,45,"Minor Manifestation of Water",1421}},
      {q="Call of Water", p=6, cls="SHAMAN", g={38,45,"Minor Manifestation of Water",1421}, r={66,44,"Islen Waterseer: Water Totem, Healing Stream Totem",BAR}},
      {q="Egg Hunt", opt=true, g={51,30,"Korran, the Crossroads",BAR}, o={48,80,"12 Silithid Eggs from the mounds in the Field of Giants",BAR}},
      {q="Gann's Reclamation", opt=true, g={44,73,"Gann Stonespire, road west of Bael Modan",BAR}, o={46,84,"15 Bael'dun Excavators, 5 Foremen, Khazgorm's Journal; enter from the south slope",BAR}},
      {forever=true, t="Nothing announced touches Stonetalon or Ashenvale."},
      {lv=25},
    },
  },
  -- ============================================================ 25-30 Thousand Needles
  {
    id="t5", lv={25,30}, name="Thousand Needles", map=TN,
    hub="Freewind Post", hearth="Freewind Post (Innkeeper Abeqwa)", fp="Freewind Post (Nyse)",
    steps={
      {tr=true, x=46, y=51, t="Fly Splintertree to Camp Taurajo, ride south down the Gold Road to the Great Lift. Brave Moonhorn at the top gives Message to Freewind Post."},
      {q="Message to Freewind Post", g={32,22,"Brave Moonhorn, the Great Lift"}, r={46,51,"Cliffwatcher Longhorn, Freewind Post"}},
      {bind="Freewind", x=46, y=51},
      {fp="Freewind", x=46, y=51},
      {q="Pacify the Centaur", g={46,51,"Cliffwatcher Longhorn"}, o={41,39,"12 Galak Scouts, 10 Wranglers, 6 Windchasers at Splithoof Crag north (verify)"}},
      {q="Alien Egg", g={46,51,"Hagar Lightninghoof"}, o={45,45,"Follow the quest text; three possible spots"}},
      {q="Wind Rider", opt=true, g={46,51,"Elu, Freewind Post"}, o={12,32,"Highperch wyvern eggs (verify)"}},
      {q="WANTED: Arnak Grimtotem", g={46,51,"Wanted poster, Freewind Post"}, o={34,36,"Arnak Grimtotem on Darkcloud Pinnacle"}},
      {q="Test of Faith", g={54,44,"Dorn Plainstalker, the Weathered Nook cave in the northern cliffs"}, o={54,44,"Jump off the planks; no fall damage"}},
      {q="Test of Endurance", g={54,44,"Dorn Plainstalker"}, o={53,45,"Follow the quest text"}},
      {q="Test of Strength", g={54,44,"Dorn Plainstalker"}, o={53,45,"Follow the quest text"}},
      {q="Homeward Bound", g={12,32,"Pao'ka Swiftmountain, Highperch"}, o={21,32,"Escort him out of Highperch to Whitereach Post"}, r={21,32,"Whitereach Post"}},
      {q="Sacred Fire", g={21,32,"Motega Firemane, Whitereach Post"}, r={40,56,"Zangen Stonehoof, Thunder Bluff",TB}},
      {q="Protect Kanati", g={21,32,"Kanati Greycloud, Whitereach Post"}, o={21,32,"Defend Kanati after the Assassination Note drops from the Galak"}},
      {q="Grimtotem Spying", g={46,51,"Freewind Post"}, o={34,36,"Three Secret Notes from chests on Darkcloud Pinnacle (path up from 31,37)"}},
      {q="Free At Last", g={34,36,"Lakota Windsong, Darkcloud Pinnacle"}, o={46,51,"Escort her down to Freewind Post"}, r={46,51,"Freewind Post"}},
      {lv=30},
      {q="Call of Air", cls="SHAMAN", g=TB_SPIRIT, r={54,43,"Prate Cloudseer, the Weathered Nook: Air Totem, Swift Wind"}},
      {q="The Islander", cls="WARRIOR", g={57,87,"Torm Ragetotem, Thunder Bluff",TB}, r={68,48,"Klannoc Macleod, Fray Island south of Ratchet; swim from the sand bar",BAR}},
      {q="The Affray", cls="WARRIOR", g={68,48,"Klannoc Macleod, Fray Island",BAR}, o={68,48,"Step on the grate, kill the challenger waves, then Big Will (33)",BAR}, r={68,48,"Klannoc: Berserker Stance, Intercept",BAR}},
      {q="The Windwatcher", cls="WARRIOR", g={68,48,"Klannoc Macleod",BAR}, r={80,67,"Bath'rah the Windwatcher, ruins on the east bank north-east of Tarren Mill, Alterac (do it on the Stranglethorn leg)",1424}},
      {man="Shimmering Flats (78,76) at 29-31: the Mirage Raceway beast-part quests, done in circles around the track. Finish 30 here.", x=78, y=76},
      {forever=true, t="Plainsrunning cuts out in combat and instances, but the Needles are the zone it was made for."},
    },
  },
}

-- Class steps that belong in the shared Horde brackets (all Horde classes use the same Sunken
-- Temple and Whirlwind chains). Appended to the Forsaken brackets below.
local SHARED_CLASS_STEPS = {
  b7 = {
    {q="Cyclonian", p=1, cls="WARRIOR", g={80,67,"Bath'rah the Windwatcher, Alterac",1424}, o={36,14,"30 Bloodscalp Tusks from the trolls north-west of Grom'gol; 8 Liferoot from the auction house. The Essence of the Exile comes from Arathi next bracket"}},
  },
  b8 = {
    {q="Cyclonian", p=2, cls="WARRIOR", g={80,67,"Bath'rah the Windwatcher",1424}, o={51,49,"8 Burning Charms (Circle of West Binding 26,30), 8 Thundering Charms (Outer 51,49), 8 Cresting Charms (East 67,31); combine at Bath'rah's cauldron"}, r={80,67,"Bath'rah the Windwatcher",1424}},
    {q="The Summoning", cls="WARRIOR", g={80,67,"Bath'rah the Windwatcher",1424}, o={80,67,"Summon Cyclonian (40 elite, stuns) at the altar by the hut; loot the Whirlwind Heart. Bring a partner",1424}, r={80,67,"Bath'rah",1424}},
    {q="Whirlwind Weapon", cls="WARRIOR", g={80,67,"Bath'rah the Windwatcher",1424}, r={80,67,"Bath'rah: Whirlwind Axe, Sword or Warhammer",1424}},
  },
  b11 = {
    {q="A Troubled Spirit", cls="WARRIOR", g={57,87,"Torm Ragetotem, Thunder Bluff (any capital warrior trainer)",1456}, r={34,66,"Fallen Hero of the Horde, road at the Blasted Lands border, Swamp of Sorrows",1435}},
    {q="Warrior Kinship", cls="WARRIOR", g={34,66,"Fallen Hero of the Horde",1435}, o={45,30,"7 Helboar in the Blasted Lands (verify)",1419}},
    {q="War on the Shadowsworn", cls="WARRIOR", g={34,66,"Fallen Hero of the Horde",1435}, o={40,45,"20 Shadowsworn Adepts, 10 Cultists, 20 Thugs around the Altar of Storms and Dreadmaul Hold (verify)",1419}},
    {q="Voodoo Feathers", cls="WARRIOR", g={34,66,"Fallen Hero of the Horde",1435}, o={70,54,"Temple of Atal'Hakkar: Gasher, Loro, Hukku, Zul'Lor, Mijan, Zolo for 2 Amber, 2 Blue, 2 Green Voodoo Feathers",1435}, r={34,66,"Fallen Hero: Fury Visor, Diamond Flask or Razorsteel Shoulders",1435}},
    {q="The Hunter's Charm", cls="HUNTER", g={57,89,"Holt Thunderhorn, Thunder Bluff (any capital hunter trainer)",1456}, r={42,43,"Ogtinc, cliffs above the Ruins of Eldarath, Azshara",1447}},
    {q="Courser Antlers", cls="HUNTER", g={42,43,"Ogtinc",1447}, o={52,27,"2 Perfect Courser Antlers from Mosshoof Coursers (verify)",1447}},
    {q="Wavethrashing", cls="HUNTER", g={42,43,"Ogtinc",1447}, o={87,26,"6 Wavethrasher Scales in the water off the north-east coast",1447}},
    {q="The Green Drake", cls="HUNTER", g={42,43,"Ogtinc",1447}, o={70,54,"Kill Morphaz in the Temple of Atal'Hakkar; loot the Tooth",1435}, r={42,43,"Ogtinc: Devilsaur Eye, Devilsaur Tooth or Hunting Spear",1447}},
    {q="Elemental Mastery", cls="SHAMAN", g={22,20,"Any Spirit Rise shaman trainer, Thunder Bluff",1456}, o={22,20,"1 Elemental Air, Fire, Earth and Water (auction house or the Arathi circles)",1456}, r={80,67,"Bath'rah the Windwatcher, Alterac",1424}},
    {q="Spirit Totem", cls="SHAMAN", g={80,67,"Bath'rah the Windwatcher",1424}, o={34,59,"8 Bloodshot Spider Eyes (lurkers), 8 Thick Black Claws (diseased bears), Western Plaguelands",1422}, r={80,67,"Bath'rah",1424}},
    {q="Da Voodoo", cls="SHAMAN", g={80,67,"Bath'rah the Windwatcher",1424}, o={70,54,"Temple of Atal'Hakkar: the six troll mini-bosses for 2 Amber, 2 Blue, 2 Green Voodoo Feathers",1435}, r={80,67,"Bath'rah: Azurite Fists, Enamored Water Spirit or Wildstaff",1424}},
    {q="Torwa Pathfinder", cls="DRUID", g={76,27,"Turak Runetotem, Elder Rise, Thunder Bluff",1456}, r={72,76,"Torwa Pathfinder, bluff by the waterfalls at the bottom of the Tanaris ramp, Un'Goro",1449}},
    {q="Bloodpetal Poison", cls="DRUID", g={72,76,"Torwa Pathfinder",1449}, o={50,80,"8 Bloodcap from Bloodpetal Sprouts, 8 Gorishi Stings from the Slithering Scar wasps",1449}},
    {q="Toxic Test", cls="DRUID", g={72,76,"Torwa Pathfinder",1449}, o={55,45,"Hibernate a Devilsaur, stab it with the Devilsaur Barb, Travel Form away",1449}},
    {q="A Better Ingredient", cls="DRUID", g={72,76,"Torwa Pathfinder",1449}, o={70,54,"Putrid Vine from Atal'alarion in the Temple of Atal'Hakkar (light the six altars in order)",1435}, r={72,76,"Torwa: Grizzled Pelt, Forest's Embrace or Moonshadow Stave",1449}},
  },
}
for _, b in ipairs(ns.BRACKETS) do
  local extra = SHARED_CLASS_STEPS[b.id]
  if extra then
    -- insert before the closing level gate so the class chain sits inside the bracket
    local at = #b.steps
    for i = #b.steps, 1, -1 do if b.steps[i].lv then at = i - 1; break end end
    for j, s in ipairs(extra) do table.insert(b.steps, at + j, s) end
  end
end

-- Tauren route = the five brackets above, then the shared Horde brackets from 30-35 on.
local TAUREN_ROUTE_BRACKETS = {}
for _, b in ipairs(ns.TAUREN_BRACKETS) do table.insert(TAUREN_ROUTE_BRACKETS, b) end
for i = 7, #ns.BRACKETS do table.insert(TAUREN_ROUTE_BRACKETS, ns.BRACKETS[i]) end


table.insert(ns.ROUTES, {
  id = "tauren", name = "The Long Walk", faction = "Horde",
  races = { Tauren = true }, raceOnly = 5,
  brackets = TAUREN_ROUTE_BRACKETS,
})
